var resourceInfo={
ids_fota_upgradingTips:'Please don\'t power off during upgrading.The device will be restarted after an upgrade.',
ids_usage_billingDay:'Billing Day',
ids_sms_phoneNumberInvalid:'Phone number invalid',
ids_btn_logout:'Logout',
ids_wifi_ssidBroadcast:'SSID Broadcast',
ids_wifi_wpaDescription:'The WPA Pre-Shared Key (PSK) should be 8-63 ASCII characters.',
ids_dlg_pb_nameRule:'The Name cannot include the following characters:"\\","\\\'".',
ids_usage_GB:'GB',
ids_UserNameRule32:'The maximum length of User name is 32, except for: " : ; & .',
ids_pdpTimer_120seconds:'120 seconds',
ids_profile_profileNameRule:'The maximum length of Profile name is 31,except for: , " : ; \\ & % + < > ?.',
ids_security_ipFilterDescription:'The value range of Port is 0-65535.',
ids_back:'Back',
ids_usage_dataUsageReach:'When data usage reaches Monthly Data Plan',
ids_router_startIpInvalid:'Start IP Address is invalid. Please input again!',
ids_iptype:'IP type',
ids_net_selectWarn:'Please select one network!',
ids_login_inputCurrPwd:'Current Password is wrong.',
ids_sim_autoPin:'PIN Code Auto Validation',
ids_wifi_offTip:'The Wifi is disable, Please try again after open the wifi.',
ids_net_3g4gOnly:'3G / 4G Only',
ids_wifi_wifiOffTime_30min:'30 minutes',
ids_fota_batteryTips:'Battery is low,the device can not be upgraded',
ids_wifi_wpa:'WPA PSK',
ids_wifi_cipher:'Cipher Type',
ids_sim_initializing:'SIM is Initializing.',
ids_success:'Successful',
ids_sim_lockCodeRule:'SIM Lock code should be 10 digits.',
ids_sim_pinRequired:'PIN Required',
ids_router_endIpInvalid:'End IP Address is invalid. Please input again!',
ids_security_macFilterDescription:'Control and manage the device accessing the WLAN. (improve the security of WLAN).',
ids_net_lteOnlyVal:'LTE Only',
ids_security_PowerSavingSmartTips:'All LED light off automatically except Power LED when no WiFi access or manual operation within 30s.',
ids_wan_tips:'Failed! Usage history overflow,you can reset the Monthly Data Plan and then reconnect.',
ids_wan_roamingWarningMessage:'Data Roaming enables you to browse the web, use email, MMS and other data services while abroad. Check with your network provider for pricing',
ids_title_preferredDnsServer:'Preferred DNS Server',
ids_modify:'Modify',
ids_title_connectMode:'Connection Mode',
ids_net_noService:'No Service',
ids_net_2g3gOnly:'2G / 3G Only',
ids_sms_chatInputConfirm:'Please press Enter to complete',
ids_sms_mobileNumRule:'The maximum length of Mobile number is 20 digits, including "+0123456789",please input again.',
ids_dlg_pb_NumberNullWarning:'The Phone number should not be null.',
ids_usage_hours:'hours',
ids_usage_timePassed:'Time Passed',
ids_wifi_country:'Country',
ids_wifi_wlan_mode:'Wlan Mode',
ids_net_umts:'3G',
ids_fail:'Failed!',
ids_wifi_wpsPin:'WPS PIN',
ids_wan_inputDeviceName:'please input device name',
ids_sms_sendFail:'SMS sent failed',
ids_sim_pukCode:'PUK code',
ids_sms_newMessageOn:'unread of',
ids_tr069_inputConReqPassword:'Please input the connection request password before saving it.',
ids_sys_swVersion:'Software Version',
ids_sim_simlockError:'Simlock error!',
ids_security_ipFilterPort:'The value range of Port is 0-65535.',
ids_wifi_inputSsid:'Please input the SSID.',
ids_clearCode_Thirtythree:'No services data',
ids_sim_confirmPinCode:'Confirm PIN code',
ids_security_dmzStatus:'DMZ status',
ids_security_macAddrNameWarn:'The MAC Address already existed.',
ids_security_portRule:'The value range of Port is 1-65535.',
ids_router_startIP:'Start IP',
ids_fotaUpdate_openRoaming_meg:'Additional charges may apply for downloading while in Roaming, please check with your Operator. Would you like to continue?',
ids_net_forbid:'Forbidden',
ids_btn_loginTimeout:'re-register',
ids_security_wanIpAddr:'WAN IP Address',
ids_profile_userName:'User name',
ids_profile_password:'Password',
ids_btn_restore:'Restore',
ids_tips_livechat:'Live chat',
ids_login_inputPwd:'Please input the password.',
ids_login_inputUserName:'Please input the user name.',
ids_pdpTimer_20seconds:'20 seconds',
ids_btn_previous:'Previous',
ids_sys_restoreBackupWarn:'This action will update the settings and restart the device once the upload is completed. Are you sure to continue?',
ids_security_ipLanWan:'Note: The value range of LAN/WAN Port is 0-65535 and 0 means any.',
ids_usage_KB:'KB',
ids_login_remenberPassword:'Remember password',
ids_security_firewallDes:'This page gives information on how to enable firewall filter functions. The IP address filter functions are only available when the firewall is enabled.',
ids_title_wifiSettings:'WiFi Settings',
ids_sim_invalidSimCard:'Invalid SIM Card',
ids_sim_unknown:'Unknown',
ids_wan_disconnecting:'Disconnecting......',
ids_btn_delete:'Delete',
ids_tr069_client:'TR-069 client – Configuration',
ids_wifi_channel:'WiFi Channel',
ids_title_dnsSetting:'DNS',
ids_pb_name:'Name',
ids_btn_apply:'Apply',
ids_fota_latestVersion:'It\'s already the latest version.',
ids_security_urlAddrInvalid:'URL Address is invalid.',
ids_wan_cannotBlock:'The Mac Filter is Allow right now, can’t process this option.',
ids_deny:'Deny',
ids_sms_saveDraftSuccess:'SMS is saved as a draft',
ids_network_notAvailableFunctionWarn:'Please disconnect data connection before initiating Profile management',
ids_usage_duration:'Duration Time',
ids_sim_rck:'RCK',
ids_sms_deleteWarning:'Are you sure to delete the message(s)?',
ids_icon_uploaded:'Uploaded',
ids_orange_sim_pinOperationWarn:'You cannot update the PIN Code settings while you are connected to the internet.',
ids_dlg_pb_mobileNumRule:'The maximum length of Mobile number is 40 digits, including "+0123456789",please input again.',
ids_title_profilesManagement:'Profile Management',
ids_wifi_wifiOffTime_20min:'20 minutes',
ids_sim_lockForbidden:'SIM LOCK is forbidden!',
ids_sim_pinRule:'PIN code should be 4-8 digits.',
ids_security_dmzTips:'DMZ allows the selected device to bypass the firewall features of the gateway and permits unrestricted access from the Internet to that device.',
ids_router_startSameSubnet:'Start IP Address and "IP Address" should belong to the same subnet.',
ids_btn_help:'Help',
ids_menu_smsSettings:'SMS Settings',
ids_profile_nameWarn:'The profile name already existed.',
ids_wifi_wifiOffTime_10min:'10 minutes',
ids_sim_newPinRule:'New PIN code should be 4-8 digits.',
ids_sim_comfirmPinRule:'Confirmed PIN code should be 4-8 digits.',
ids_sim_enterValidCode:'Please enter a valid PIN code.',
ids_btn_send:'Send',
ids_net_available:'Available',
ids_profile_numRule:'Note: The max number of the profile you can create is 15.',
ids_gsm7_text:'GSM 7',
ids_dlg_sms_smsForwardNumEmpty:'Mobile Number is empty. Please input the number.',
ids_wifi_wepDescription:'WEP Key is 5 or 13 ASCII characters,or 10 or 26 hexadecimal digits.',
ids_sd_sdCard:'SD Card',
ids_sys_deviceName:'Device Name',
ids_days:'days',
ids_sys_ipAddress:'IP Address',
ids_login_nameOrPwdWrong:'User name or password is wrong!',
ids_profile_userNameRule:'The maximum length of User name is 31, except for: " : ; & .',
ids_wifi_cannotSet:'The WiFi is disable right now, can’t process this option.',
ids_router_ipAddrEmpty:'IP Address is empty. Please input again!',
ids_wifi_pinDecription:'WPS PIN (WPS setup by entering special 8-digit code):<br/>1. If at least one client is connect to the router, then open browser on connected device and go to http://192.168.0.1/, enter password and click More > WPS. Select WPS PIN.<br/>2. On device which you want to connect to the router (e.g. PC or smartphone) open Wi-Fi Setup Utility which supports WPS (should be provided by the vendor of this device), and choose WPS PIN mode. 8-digit WPS PIN will be generated.<br/>3. Go back to router Web interface, enter 8-digit WPS PIN in WPS PIN field and click Apply.<br/>4. Connection between the router and client will be automatically established in about 2 minutes.',
ids_tr069_tips:'Select the desired values and click “Apply/Save” to configure the TR-069 client options.',
ids_more_onlineUpdate:'Online Update',
ids_security_btnAdd:'Add',
ids_sms_autoForward:'SMS Forwarding to Mobile Phone',
ids_sim_simLockCode:'SIMLock Code',
ids_router_restartWarn:'This action requires the device to be restarted. Are you sure to continue?',
ids_sms_saveSimCard:'SIM card',
ids_automatic:'Automatic',
ids_security_portTips:'Note: Please specify the port and port group,example:30 or 65500-65510.',
ids_wifi_wpsNotSuppotSSIDHidden:'SSID Hidden,can not set WPS.',
ids_netMode_Automatic3g2g:'Automatic(3G & 2G)',
ids_wifi_apIsotation:'AP Isolation',
ids_security_portForwarding:'Port Forwarding',
ids_btn_add:'Add',
ids_usage_billingTimeTips:'Please input the day between 1-31.',
ids_minutes:'minutes',
ids_ussd_inputDescription:'Please input USSD code',
ids_fota_upgrading:'Upgrading…',
ids_router_dhcpServer:'DHCP Server',
ids_sim_pinRequiredTips:'For more information, please click "PIN required" to unlock at first.',
ids_login_checkPwdRule:'Invalid password!The length of login password is 4-16, including 0-9, a-z, A-Z,"-+!@$#^&*",please input again.',
ids_wifi_wifiOffTime:'Wi-Fi Off Time',
ids_sd_sdShareMode:'SD Share Mode',
ids_btn_continue:'Continue',
ids_profile_protocal:'Protocol',
ids_security_lanPort:'LAN Port',
ids_dlg_sms_reInputCenterNum:'SMS Center Number is invalid. Please input again!',
ids_btn_backup:'Backup',
ids_wan_connected_num:'Connected',
ids_sms_centerNum:'SMS Center',
ids_fota_downloading:'Downloading…',
ids_wifi_wpaWpa2Psk:'WPA/WPA2 PSK',
ids_usage_of:'of',
ids_sys_rebootDecription:'Click this button to restart the device.',
ids_title_about:'About',
ids_sim_nck:'NCK',
ids_net_operator:'Operator',
ids_router_endIpEmpty:'End IP Address is empty. Please input again!',
ids_btn_cancel:'Cancel',
ids_dlg_pb_nameNullWarning:'The Name should not be null.',
ids_dlg_sms_inputCenterNum:'The SMS Center Number is empty. Please input the number.',
ids_ussd_rule:'Only "*" "#" and numbers can be input.',
ids_wifi_wifi:'WiFi',
ids_sms_selectSomeOptions:'3 contacts at most',
ids_btn_new:'New',
ids_fota_findNewVersion:'Find new version',
ids_security_pfNumRule:'Note: The max number of the Port Forwarding you can create is 16.',
ids_wifi_showPwd:'Show Password',
ids_security_urlFilterList:'URL Filter List',
ids_loginTimeout:'Login timeout, the need to re-login',
ids_title_alternateDnsServer:'Alternate DNS Server',
ids_login_inputNewPwd:'Please input the new password.',
ids_fota_updateTitle:'System Updates',
ids_login_inputConfirmPwd:'Please input the Confirmed Password.',
ids_hours:'hours',
ids_wifi_maxUser:'Max Number of Users',
ids_pb_addNew:'Add',
ids_usage_timeLimit:'Time Limit',
ids_sim_pinCode:'PIN code',
ids_wifi_wpaTkip:'TKIP',
ids_sim_autoPinState:'Current Status',
ids_security_dmzTitle:'DMZ',
ids_security_dmzIpInvalid:'DMZ IP Address is not a valid IP address.',
ids_btn_unblock:'Unblock',
ids_fota_checkUpdate:'Update',
ids_title_advanced:'Advanced Settings',
ids_security_ipFilterWarn:'The Ip Filter already exists.',
ids_fota_updateDescription:'click "Update" to update to new version.',
ids_btn_reset:'Reset',
ids_tr069_acsUrlRule:'Acs url format:eg:http://ip address:port/xxx',
ids_show_again:'Do not show this again',
ids_usage_hrs:'Hrs',
ids_icon_battery:'Battery',
ids_sms_saveDevice:'Device',
ids_roamAppear:'Slide to use data while roaming. Check with your network provider for pricing.',
ids_sys_chooseFile:'Choose file',
ids_btn_refresh:'Refresh',
ids_pb_phoneBook:'Phonebook',
ids_net_select:'Network Selection',
ids_sim_pinError:'Pin error!',
ids_sms_saveDraftFailed:'Draft save failed',
ids_sms_delivered:'Delivered',
ids_usage_autoDisconnected:'Auto Disconnected',
ids_login_confirmPwd:'Confirm Password',
ids_security_addMacAddress:'Add MAC Address',
ids_sim_noSimCard:'No SIM card',
ids_wifi_notSuppotWepWpa:'WPS is not available under WEP, WPA, WPA2 TKIP !',
ids_security_pfWarn:'The Port Forwarding already exists.',
ids_fota_checking:'Checking…',
ids_dlg_pb_lenWarning:'The input is too long',
ids_sim_newPinCode:'New PIN code',
ids_sim_pinNotAvailable:'PIN code is not available.',
ids_usage_clear:'Clear history',
ids_wifi_maxSsid:'The maximum length of SSID is 32 characters, including 0-9, a-z, A-Z, "-", "_", "." ," ".',
ids_usage_startTimeTips:'Please input the data between 1-43200.',
ids_wifi_pbcConfiguration:'Push Button Configuration',
ids_usage_dataConsumption:'Data Consumption',
ids_disable:'Disable',
ids_ucs2Orgsm7_text:'UCS2 Or GSM7',
ids_login_loginPwd:'Login Password',
ids_btn_save:'Save',
ids_wifi_802mode:'802.11 Mode',
ids_pb_phoneNumber:'Phone number',
ids_ussd_timeOut:'Time out!Please try again.',
ids_btn_reboot:'Reboot',
ids_minute:'minute',
ids_router_ipAddrInvalid:'IP Address is invalid. Please input again!',
ids_router_startIpEmpty:'Start IP Address is empty. Please input again!',
ids_sim_pinEnable:'PIN auto validation is enabled.',
ids_sim_pinCodeOperation:'PIN Code Operation',
ids_security_dmzInvalidLanSubnet:'DMZ IP Address is not on the LAN subnet.',
ids_net_service:'Service',
ids_router_ipRule:'Error!Please be noticed, 10 after the Home Address is System pre-reserved IP,and it can not be included in DHCP IP Pool.',
ids_usage_roaming:'Roaming',
ids_title_ussd:'USSD',
ids_btn_ok:'OK',
ids_sys_resetDecription:'Restore Factory Default settings.',
ids_tr069_inputInformInterval:'Please input the inform interval before saving it.',
ids_security_dmzIpAddr:'DMZ IP address',
ids_profile_inputApn:'Please input the APN!',
ids_sys_restoreFactoryWarn:'This action will restore the default factory settings and restart the device. Are you sure you want to continue?',
ids_net_registing:'Registering......',
ids_sys_backupDecription:'Download(Backup) the configuration.',
ids_sms_selectAnOption:'Select an Option',
ids_tr069_inputAcsUrl:'Please input the acs url before saving it.',
ids_tr069_acsUsername:'ACS User Name',
ids_pdpTimer_0seconds:'0 second',
ids_usage_home:'Home',
ids_profile_deleteWarn:'Are you sure to delete it?',
ids_sms_smsFull:'SMS box is full, please delete some SMS to be able to send/save new SMS.',
ids_tr069_connRqPw:'Connection Request Password',
ids_sim_pukError:'Puk error!',
ids_sys_system:'System',
ids_security_PowerSavingSmart:'Smart',
ids_login_timeuseout:'The login times used out.Please reboot and try again.',
ids_usage_minutesTimes:'min(s)',
ids_sim_pukRule:'PUK code should be 8 digits.',
ids_net_3gOnly:'3G Only',
ids_sim_nsck:'NSCK',
ids_subnetMask:'Subnet Mask',
ids_pdpTimer_60seconds:'60 seconds',
ids_sim_pinDisable:'PIN auto validation is disabled.',
ids_sys_macAddress:'MAC Address',
ids_menu_connection:'Connection',
ids_dlg_pb_tooManyNumbers:'To start editing, please, select only one number.',
ids_password:'Password',
ids_security_virtualServer:'Virtual server(static port forwarding)',
ids_security_ipFilterDes:'Filter packets using the following rules specified with protocol, port and IP address.',
ids_ussd_checkBlance:'Check balance',
ids_title_tr069:'TR069',
ids_sms_draft:'Draft',
ids_wifi_encryption:'Encryption',
ids_title_ping:'Ping',
ids_foot_copyright:'Copyright 2016-2018 TCL Communication Ltd.All Rights Reserved.',
ids_tr069_acsPw:'ACS Password',
ids_help_userManual:'User Manual',
ids_security_pfDescription:'Port forwarding enables external computers to access WWW, FTP or other services provided by the LAN.',
ids_wifi_notSuppotMacFilter:'WPS (2.0 version) procedure cannot be activated if Mac address filter is enabled.',
ids_title_blockDevice:'Block Device',
ids_router_endGeaterStart:'End IP Address should be greater than "Start IP Address".',
ids_net_2gOnly:'2G Only',
ids_clearCode_Twentynine:'Authentication failure',
ids_usage_day:'day',
ids_wifi_wepShare:'Share',
ids_sms_messageSending:'There is a sms is sending',
ids_wan_roamingPopCloseConntectTips:'Data roaming will be deactivated.',
ids_sd_currentFolder:'Current Folder',
ids_wan_disconnected:'Disconnected',
ids_security_numRule:'<b>Note:</b>The max number of the Ip Filter you can create is 16.',
ids_dns_manual_mode:'DNS manual mode',
ids_login:'Login',
ids_security_PowerSavingTitle:'Power Saving',
ids_security_lanIpAddr:'LAN IP Address',
ids_menu_settings:'Settings',
ids_wifi_disconWarning:'This action will disconnect the Wi-Fi. Are you sure to continue?',
ids_wifi_wpsActiveWarn:'WPS procedure is going on.Please try again two minutes later!',
ids_login_loginUserName:'Login Username',
ids_wifi_wepWifiCertification:'WEP Key is 5 or 13 or 10 or 26.',
ids_connect:'Connect',
ids_btn_block:'Block',
ids_pb_number:'NO.',
ids_login_wrongPwd:'Wrong password!',
ids_sms_smsForwarding:'SMS Forwarding',
ids_sys_selectFilePrompt:'Please select a file before uploading.',
ids_wifi_wifiSecurity:'WiFi Security',
ids_btn_edit:'Edit',
ids_security_firewallSwitch:'Firewall Switch',
ids_router_endIP:'End IP',
ids_sys_imei:'IMEI',
ids_sim_remainTime:'Remaining Attempt(s)',
ids_update_Confirm:'The file has been downloaded,are you sure you want to update?',
ids_sim_pinConfirmed:'The confirmed PIN code should be the same as new PIN code.',
ids_filter_urlAddress:'URL Address',
ids_validate:'Validate',
ids_security_subnetWarn:'LAN IP Address and "IP Address" should belong to the same subnet.',
ids_sms_inputNum:'Please input a mobile number.',
ids_tr069_informInterval:'Inform Interval (s)',
ids_fota_haveNewVersion:'A new SW available, click to update.',
ids_sim_pukRequiredTips:'For more information, please click "PUK Required" to unlock at first.',
ids_sms_emptyMessageWarn:'Message is empty. Are you sure to send this null message?',
ids_sim_pck:'PCK',
ids_usage_clearHistory:'Are you sure to reset all statistics?',
ids_hour:'hour',
ids_tr069_connRqAuth:'Connection Request Authentication',
ids_wifi_off:'Off',
ids_pb_storageStatus:'Storage Status',
ids_wan_connectedRule:'This setting cannot be used in connected mode, please click “Disconnect” and retry.',
ids_menu_usage:'Usage',
ids_security_dmzDescription:'If a PC cannot run network applications through the gateway, enable the DMZ function and enter the IP address of the PC below.',
ids_title_networkMode:'Network Mode',
ids_wifi_wifiOffTime_5min:'5 minutes',
ids_wifi_pbc:'PBC',
ids_error:'Error!',
ids_sim_changePinError:'Change pin error!',
ids_security_wanPort:'WAN Port',
ids_security_ipFilter:'IP Filter',
ids_tr069_inputConReqUserName:'Please input the connection request user name before saving it.',
ids_tr069_informIntervalRule:'Inform interval should be 0-2678400,including "0123456789".',
ids_login_newPwd:'New Password',
ids_pdpTimer_10seconds:'10 seconds',
ids_security_virtualServerList:'Virtual Server List',
ids_security_urlAddrNameWarn:'The URL Address already existed.',
ids_btn_select:'Select',
ids_router_endSameSubnet:'End IP Address and "IP Address" should belong to the same subnet.',
ids_ussd_CodeEmpty:'Input box can not be empty!',
ids_sim_autoPinError:'Auto pin verfiy error!',
ids_usage_cancelLimitTips:'Set data limit as 0 and save to cancel any data limit.',
ids_sim_simLocked:'SIM Lock Required',
ids_icon_timeElapsed:'Time elapsed',
ids_sms_sendingPrompt:'Sending......, please wait!',
ids_tr069_inputAcsPassword:'Please input the acs password before saving it.',
ids_requestError:'No response, the device may have been disconnected, Please restart the device and try again.',
ids_profile_inputRule:'APN & Dial Number should be ASCII characters ranging from 32-127, except for: " : ; & .',
ids_net_active:'Active',
ids_sms_numberWarning:'The input is too much. Please delete some.',
ids_data:'Data',
ids_pdpTimer:'PDP Timer',
ids_menu_sharing:'Sharing',
ids_sd_noSdCard:'No SD Card',
ids_wifi_pbcDecription:'1. If no client is connected to the router, then press and hold WPS button on router and wait until Wi-Fi LED blinks. If at least one client is connect to the router, then open browser on connected device and go to http://192.168.0.1/, enter password and click More > WPS. Press WPS soft-button.<br/>2. On device which you want to connect to the router (e.g. PC or smartphone) open Wi-Fi Setup Utility which supports WPS (should be provided by the vendor of this device), and choose PBC mode or press PBC (WPS) button on device body, if available.<br/>3. Connection between the router and client will be automatically established in about 2 minutes.',
ids_sms_deleteSingleWarning:'Are you sure to delete the message?',
ids_menu_more:'More',
ids_net_4gOnly:'4G Only',
ids_profileProtocal_none:'None',
ids_isSupportKickOff:'Other user already logined, do you still want to login? This will kick other user off.',
ids_changePassword_Tips:'Your current username and password is the default setting,we advise that you change your password to something memorable.Please <a class="userpass_link">&nbsp;click here&nbsp;</a> to change the username and password.',
ids_wifi_wifiSleep:'WiFi Sleep',
ids_security_upnpDescription:'UPnP allows device to device networking. It is a distributed, open architecture protocol based on established standards such as the Internet Protocol Suite (TCP/IP), HTTP, XML and SOAP.',
ids_sms_deleteAll:'Delete all',
ids_pb_location:'Location',
ids_diagnostic:'Diagnostic',
ids_security_macAddrInvalid:'MAC Address is invalid.',
ids_security_PowerSavingWiFiTips:'WiFi will automatically turn off if the connection is in idle for a long time.',
ids_tr069_connRqUsername:'Connection Request User Name',
ids_security_PowerSavingWiFi:'Wi-Fi',
ids_profile_pwdRule:'The maximum length of Password is 31,except for: " : ; & .',
ids_tr069_inform:'Inform',
ids_locked_permanently:'This device has been locked permanently and cannot be unlocked!',
ids_sys_setRebootEvent:'The device is rebooting, please wait 60 seconds,then reconnect to the Wi-Fi device.',
ids_sms_saveMode:'Save Mode',
ids_pb_add:'Add',
ids_sim_spck:'SPCK',
ids_security_upnp:'UPnP',
ids_sms_encodingoptimization:'SMS Encoding Optimization',
ids_profile_inputDialNum:'Please input the dial number!',
ids_dlg_pb_deleteWarning:'Are you sure you want to delete?',
ids_security_enableIp:'Enable IP address filter',
ids_sms_mobileNum:'Mobile Phone Number',
ids_security_urlFilterTitle:'URL Filter',
ids_btn_setDefault:'Set&nbsp;Default',
ids_wan_connectedRuleIndia:'Please disconnect data connection before initiating Profile management.',
ids_title_loginSettings:'Login Settings',
ids_profile_apn:'APN',
ids_pb_local:'Local',
ids_wan_roamingAutoConnect:'Automatically connect even when in roaming.',
ids_wifi_key:'Key',
ids_login_userName:'admin',
ids_wifi_offRule:'WiFi is disabled currently as no client connected for a long time.  Please enable WiFi manually by pressing any button on device if you want to use WiFi.',
ids_allow:'Allow',
ids_usage_MB:'MB',
ids_sim_simLockedTips:'For more information, please click "SIM Lock Required" to unlock at first.',
ids_login_inputOldPwd:'Please input the old password.',
ids_icon_downloaded:'Downloaded',
ids_sys_rebootWarn:'Are you sure to restart this device?',
ids_security_enableFirewall:'Enable firewall',
ids_security_pfRangePortTip:'Lan port number is not the same with wan port number!',
ids_wifi_wepRule:'WEP Key should be ASCII characters ranging from 32-127, except for: " : ; & .',
ids_sd_viewFile:'View File',
ids_icon_debit:'Debit',
ids_wifi_wpa2:'WPA2 PSK',
ids_sim_pinManagement:'PIN Code Management',
ids_security_upnpStatus:'UPnP status',
ids_HelplineNumber:'Helpline Number:',
ids_login_confirmPwdRule:'The new password is not the same as the confirmed one.',
ids_router_leaseTime:'DHCP IP Lease Time',
ids_sd_usedTotal:'(Used/Total)',
ids_usage_monthlyDataPlan:'Monthly Data Plan',
ids_title_wps:'WPS',
ids_sms_newMessage:'New Message',
ids_auto:'AUTO',
ids_usage_setTimeLimit:'Set Time Limit',
ids_wifi_wep:'WEP',
ids_net_status:'Status',
ids_usage_minutes:'minutes',
ids_wifi_wpsActive:'WPS is active.',
ids_menu_usageSetting:'Usage Settings',
ids_login_otherLogin:'The administrator had already logged in, Please try later.',
ids_btn_wan_disconnect:'Disconnect',
ids_tr069_inputAcsUserName:'Please input the acs user name before saving it.',
ids_security_ipFilterList:'IP Filter List',
ids_wifi_on:'On',
ids_day:'day',
ids_net_gsm:'2G',
ids_usage_notAccurate:'Statistics may not be accurate.',
ids_sim_pukRequired:'PUK Required',
ids_security_ipOption:'Options',
ids_net_lte:'4G',
ids_router_subnetEmpty:'Subnet mask is empty. Please input again!',
ids_pdpTimer_5seconds:'5 seconds',
ids_wan_roamingPopWarningMessage:'Click <OK> to use data while roaming. Check with your network provider for pricing',
ids_manual:'Manual',
ids_menu_connectDevice:'Connected Device(s)',
ids_profile_dialNumber:'Dial Number',
ids_menu_sms:'SMS',
ids_sys_hwVersion:'Hardware Version',
ids_usage_mothlyDataTips:'Please input the data between 1-1024.',
ids_pdpTimer_90seconds:'90 seconds',
ids_title_macFilter:'MAC Filter',
ids_netMode_Automatic4g3g2g:'Automatic(4G & 3G & 2G)',
ids_sys_noFileChosen:'No file chosen',
ids_dlg_sms_mobileNumRule:'Please enter a valid number: 0-9 and \'+\' only, no spaces or special characters.',
ids_wan_connecting:'Connecting......',
ids_profile_inputName:'Please input the profile name before saving it.',
ids_wan_Block:'The MAC address list already full, can’t process this option.',
ids_icon_people:'People',
ids_sim_autoValidate:'Auto Validate',
ids_menu_language:'Language',
ids_wifi_wpsPinRule:'WPS PIN code should be 4 or 8 digits.',
ids_title_pinCodeSettings:'PIN Code Settings',
ids_net_searching:'Searching......',
ids_wifi_wpaRule:'WPA PSK should be ASCII characters ranging from 32-127, except for: " : ; & .',
ids_ussd_notSupport:'Not support!Please try again.',
ids_tr069_acsUrl:'ACS URL',
ids_sms_report:'SMS Report',
ids_sim_cck:'CCK',
ids_security:'Security',
ids_enable:'Enable',
ids_wifi_wpaAes:'AES',
ids_btn_next:'Next',
ids_profile_profileName:'Profile Name',
ids_wifi_wepOpen:'Open',
ids_wan_connectIPMode:'Connection IP Mode',
ids_router_subnetInvalid:'Subnet mask is invalid. Please input again!',
ids_pdpTimer_30seconds:'30 seconds',
ids_usage_min:'Min',
ids_wan_connected:'Connected'
}