var resourceInfo={
ids_fota_upgradingTips:'Frissítés alatt ne kapcsolja ki a készüléket. A frissítést követően a készülék újra fog indulni.',
ids_usage_billingDay:'Számlázási nap',
ids_sms_phoneNumberInvalid:'Érvénytelen telefonszám',
ids_btn_logout:'Kijelentkezés',
ids_wifi_ssidBroadcast:'SSID sugárzás',
ids_wifi_wpaDescription:'A WPA előmegosztott kulcsának (PSK) 8 - 63 ASCII karakterből kell állnia.',
ids_dlg_pb_nameRule:'A Név mező nem tartalmazhatja a következő karaktereket:"\\\\","\\\'".',
ids_usage_GB:'GB',
ids_UserNameRule32:'A felhasználónév maximális hossza 32 karakter lehet, a következő szimbólumokat azonban nem tartalmazhatja: " : ; & .',
ids_pdpTimer_120seconds:'120 másodperc',
ids_profile_profileNameRule:'A profilnév maximális hossza 31 karakter lehet, a következő szimbólumokat azonban nem tartalmazhatja: , " : ; \\ & % + < > ?.',
ids_security_ipFilterDescription:'A port értéktartománya: 0-65535.',
ids_back:'Előző',
ids_usage_dataUsageReach:'Amikor az adatforgalom eléri a havi adatcsomagban foglalt mennyiséget',
ids_router_startIpInvalid:'A kezdő IP-cím érvénytelen. Adja meg ismét.',
ids_iptype:'IP típus',
ids_net_selectWarn:'Válasszon egy hálózatot.',
ids_login_inputCurrPwd:'Az aktuális jelszó hibás.',
ids_sim_autoPin:'PIN-kód automatikus hitelesítése',
ids_wifi_offTip:'A Wi-Fi ki van kapcsolva. Próbálkozzon újra a Wi-Fi megnyitását követően.',
ids_net_3g4gOnly:'Csak 3G / 4G',
ids_wifi_wifiOffTime_30min:'30 perc',
ids_fota_batteryTips:'A készülék nem frissíthető, mivel az akkumulátor töltöttségi szintje alacsony.',
ids_wifi_wpa:'WPA PSK',
ids_wifi_cipher:'Titkosítás típusa',
ids_sim_initializing:'SIM-kártya inicializálása folyamatban.',
ids_success:'Sikeres',
ids_sim_lockCodeRule:'A SIM-kártyazár kódjának 10 számjegyből kell állnia.',
ids_sim_pinRequired:'A PIN-kód megadása szükséges',
ids_router_endIpInvalid:'A záró IP-cím érvénytelen. Adja meg ismét.',
ids_security_macFilterDescription:'A WLAN hálózathoz csatlakozó készülékek ellenőrzés alatt tartása és kezelése (növeli a WLAN biztonságát).',
ids_net_lteOnlyVal:'Csak LTE',
ids_security_PowerSavingSmartTips:'A bekapcsolást jelző LED kivételével az összes LED jelzőfény automatikusan kikapcsol, ha 30 másodpercig nem csatlakozik egyetlen készülék sem a Wi-Fi hálózatra vagy semmilyen manuális műveletre nem kerül sor.',
ids_wan_tips:'Sikertelen! Túllépte az adathasználati küszöböt. Újracsatlakozáshoz állítsa vissza a havi adatcsomagot.',
ids_wan_roamingWarningMessage:'A Data Roaming lehetővé teszi a böngészést a világhálón, külföldön, e-mailben, MMS-ben és egyéb adatszolgáltatásokban. Ellenőrizze a hálózat szolgáltatóját az árazásért',
ids_title_preferredDnsServer:'Preferált DNS szerver',
ids_modify:'Módosítás',
ids_title_connectMode:'Csatlakozási mód',
ids_net_noService:'Nincs térerő',
ids_net_2g3gOnly:'Csak 2G / 3G',
ids_sms_chatInputConfirm:'Kérjük, nyomja meg az Enter gombot a befejezéshez',
ids_sms_mobileNumRule:'A mobilszám legfeljebb 20 karakterből állhat, és a "+0123456789" karaktereket tartalmazhatja. Adja meg újra.',
ids_dlg_pb_NumberNullWarning:'A Telefonszám mező nem lehet üres.',
ids_usage_hours:'óra',
ids_usage_timePassed:'Eltelt idő',
ids_wifi_country:'Ország',
ids_wifi_wlan_mode:'WLAN mód',
ids_net_umts:'3G',
ids_fail:'Sikertelen.',
ids_wifi_wpsPin:'WPS PIN-kódja',
ids_wan_inputDeviceName:'Adja meg a készülék nevét',
ids_sms_sendFail:'SMS küldése sikertelen',
ids_sim_pukCode:'PUK-kód',
ids_sms_newMessageOn:'olvasatlan /',
ids_tr069_inputConReqPassword:'Mentés előtt adja meg a csatlakozáshoz szükséges jelszót.',
ids_sys_swVersion:'Szoftververzió',
ids_sim_simlockError:'SIM feloldási kód hiba!',
ids_security_ipFilterPort:'A port értéktartománya: 0-65535.',
ids_wifi_inputSsid:'Adja meg az SSID azonosítót.',
ids_clearCode_Thirtythree:'Nincsenek szolgáltatásra vonatkozó adatok',
ids_sim_confirmPinCode:'PIN-kód megerősítés',
ids_security_dmzStatus:'DMZ állapot',
ids_security_macAddrNameWarn:'A MAC-cím már létezik.',
ids_security_portRule:'A port értéktartománya: 1-65535.',
ids_router_startIP:'Kezdő IP',
ids_fotaUpdate_openRoaming_meg:'A Roaming módban történő letöltés többletköltségekkel járhat. Tájékozódjon a mobilszolgáltatójánál. Kívánja folytatni?',
ids_net_forbid:'Tilos',
ids_btn_loginTimeout:'ismételt regisztráció',
ids_security_wanIpAddr:'WAN IP-címe',
ids_profile_userName:'Felhasználónév',
ids_profile_password:'Jelszó',
ids_btn_restore:'Visszaállítás',
ids_tips_livechat:'Élő csevegés',
ids_login_inputPwd:'Adja meg a jelszót.',
ids_login_inputUserName:'Adja meg a felhasználónevet.',
ids_pdpTimer_20seconds:'20 másodperc',
ids_btn_previous:'Előző',
ids_sys_restoreBackupWarn:'A feltöltés befejezését követően ez a művelet a beállítások frissítését és a készülék újraindítását vonja maga után. Biztosan folytatni kívánja?',
ids_security_ipLanWan:'Megjegyzés: A LAN/WAN Port érték tartomány 0-65535 és 0',
ids_usage_KB:'KB',
ids_login_remenberPassword:'Jelszó emlékeztető',
ids_security_firewallDes:'Az oldal a tűzfal szűrési funkcióinak engedélyezésére vonatkozó információkat tartalmaz. Az IP-cím szűrési funkciók kizárólag aktív tűzfal esetén érhetők el.',
ids_title_wifiSettings:'Wi-Fi beállítások',
ids_sim_invalidSimCard:'Érvénytelen SIM-kártya',
ids_sim_unknown:'Ismeretlen',
ids_wan_disconnecting:'Kapcsolat bontása folyamatban...',
ids_btn_delete:'Törlés',
ids_tr069_client:'TR-069 kliens – Konfigurálás',
ids_wifi_channel:'Wi-Fi csatorna',
ids_title_dnsSetting:'DNS',
ids_pb_name:'Név',
ids_btn_apply:'Alkalmaz',
ids_fota_latestVersion:'Már a legfrissebb verzióval rendelkezik.',
ids_security_urlAddrInvalid:'Az URL-cím érvénytelen.',
ids_wan_cannotBlock:'A MAC-szűrő aktiválva van, ezért a kérelem nem dolgozható fel.',
ids_deny:'Elutasítás',
ids_sms_saveDraftSuccess:'SMS elmentve vázlatként',
ids_network_notAvailableFunctionWarn:'Kérjük válassza le az adatkapcsolatot mielőtt elindítja a fiók kezelését',
ids_usage_duration:'Időtartam',
ids_sim_rck:'RCK',
ids_sms_deleteWarning:'Biztosan törölni kívánja az üzenete(ke)t?',
ids_icon_uploaded:'Feltöltve',
ids_orange_sim_pinOperationWarn:'Nem frissítheti a PIN-kód beállításokat miközben az internetre csatlakozik.',
ids_dlg_pb_mobileNumRule:'A mobilszám legfeljebb 40 karakterből állhat, és a "+0123456789" karaktereket tartalmazhatja. Adja meg újra.',
ids_title_profilesManagement:'Profilkezelés',
ids_wifi_wifiOffTime_20min:'20 perc',
ids_sim_lockForbidden:'A SIM-KÁRTYA ZÁROLÁSA tilos!',
ids_sim_pinRule:'A PIN-kódnak 4-8 számjegyből kell állnia.',
ids_security_dmzTips:'A DMZ lehetővé teszi a kiválasztott készülék számára az átjáró tűzfalának megkerülését, és az internetről korlátlan hozzáférést biztosít az adott készüléknek.',
ids_router_startSameSubnet:'A kezdő IP-címnek és az "IP-címnek" ugyanahhoz az alhálózathoz kell tartoznia.',
ids_btn_help:'Súgó',
ids_menu_smsSettings:'SMS beállítások',
ids_profile_nameWarn:'A profilnév már létezik.',
ids_wifi_wifiOffTime_10min:'10 perc',
ids_sim_newPinRule:'Az új PIN-kódnak 4-8 számjegyből kell állnia.',
ids_sim_comfirmPinRule:'A PIN-kód megerősítésének 4-8 számjegyből kell állnia.',
ids_sim_enterValidCode:'Adjon meg egy érvényes PIN-kódot.',
ids_btn_send:'Küldés',
ids_net_available:'Elérhető',
ids_profile_numRule:'Megjegyzés: A létrehozható profilok maximális száma 15.',
ids_gsm7_text:'GSM 7',
ids_dlg_sms_smsForwardNumEmpty:'A mobilszám mező üres. Adja meg a számot.',
ids_wifi_wepDescription:'A WEP-kulcs 5 vagy 13 ASCII karakterből, illetve 10 vagy 26 hexadecimális számjegyből áll.',
ids_sd_sdCard:'SD-kártya',
ids_sys_deviceName:'Készülék neve',
ids_days:'nap',
ids_sys_ipAddress:'IP-cím',
ids_login_nameOrPwdWrong:'Helytelen felhasználónév vagy jelszó.',
ids_profile_userNameRule:'A felhasználónév maximális hossza 31 karakter lehet, a következő szimbólumokat azonban nem tartalmazhatja: " : ; & .',
ids_wifi_cannotSet:'A művelet feldolgozása nem lehetséges, mivel a Wi-Fi funkció pillanatnyilag le van tiltva.',
ids_router_ipAddrEmpty:'Az IP-cím mező üres. Adja meg ismét.',
ids_wifi_pinDecription:'WPS PIN-kód (a WPS beállítása a speciális 8 számjegyű kód megadásával):<br/>1. Ha legalább egy kliens csatlakozik az útválasztóhoz, akkor nyissa meg a csatlakoztatott készülék böngészőjét, látogassa meg a http://192.168.0.1/ címet, adja meg a jelszót, és kattintson a Továbbiak > WPS lehetőségre. WPS PIN-kód kiválasztása.<br/>2. Az útválasztóhoz csatlakoztatni kívánt készüléken (pl. számítógép vagy okostelefon) nyissa meg a WPS támogatással rendelkező Wi-Fi beállítási segédeszközt (a készülék eladójának kell biztosítania), és válassza a WPS PIN üzemmódot. Egy 8 számjegyű WPS PIN-kód lesz generálva.<br/>3. Térjen vissza az útválasztó webes felületére, adja meg a 8 számjegyű WPS PIN-kódot a WPS PIN mezőben, és kattintson az Alkalmaz gombra.<br/>4. Az útválasztó és a kliens között automatikusan kapcsolat létesül kb. 2 perc elteltével.',
ids_tr069_tips:'Válassza ki a kívánt értékeket, majd kattintson az „Alkalmazás/Mentés” lehetőségre a TR-069 kliens opcióinak konfigurálása érdekében.',
ids_more_onlineUpdate:'On-line frissítés',
ids_security_btnAdd:'Hozzáadás',
ids_sms_autoForward:'SMS átirányítás mobiltelefonra',
ids_sim_simLockCode:'SIM feloldási kód',
ids_router_restartWarn:'A művelet végrehajtásához a készülék újraindítása szükséges. Biztosan folytatni kívánja?',
ids_sms_saveSimCard:'SIM-kártya',
ids_automatic:'Automatikus',
ids_security_portTips:'Megjegyzés: Adja meg a portot és a port csoportját. Például: 30 vagy 65500-65510.',
ids_wifi_wpsNotSuppotSSIDHidden:'SSID elrejtve. A WPS beállítása nem lehetséges.',
ids_netMode_Automatic3g2g:'Automatikus(3G & 2G)',
ids_wifi_apIsotation:'Hozzáférési pont elszigetelése',
ids_security_portForwarding:'Porttovábbítás',
ids_btn_add:'Hozzáadás',
ids_usage_billingTimeTips:'Adja meg a napot 1 és 31 között.',
ids_minutes:'perc',
ids_ussd_inputDescription:'Adja meg az USSD-kódot',
ids_fota_upgrading:'Frissítés folyamatban',
ids_router_dhcpServer:'DHCP szerver',
ids_sim_pinRequiredTips:'Ha első feloldáskor további információra van szüksége, kattintson az „A PIN-kód megadása szükséges” lehetőségre.',
ids_login_checkPwdRule:'Érvénytelen jelszó! A belépési jelszó 4 - 16 karakterből állhat, és a  következő szimbólumokat tartalmazhatja: 0-9, a-z, A-Z,"-+!@$#^&*". Adja meg újra.',
ids_wifi_wifiOffTime:'Wi-Fi kikapcsolási idő',
ids_sd_sdShareMode:'SD megosztási mód',
ids_btn_continue:'Folytatás',
ids_profile_protocal:'Protokoll',
ids_security_lanPort:'LAN port',
ids_dlg_sms_reInputCenterNum:'Az SMS központ száma érvénytelen. Adja meg ismét.',
ids_btn_backup:'Biztonsági mentés',
ids_wan_connected_num:'Csatlakozva',
ids_sms_centerNum:'SMS központ',
ids_fota_downloading:'Letöltés folyamatban...',
ids_wifi_wpaWpa2Psk:'WPA/WPA2 PSK',
ids_usage_of:'/',
ids_sys_rebootDecription:'Nyomja meg a gombot a készülék újraindításához.',
ids_title_about:'Névjegy',
ids_sim_nck:'NCK',
ids_net_operator:'Szolgáltató',
ids_router_endIpEmpty:'A záró IP-cím mező üres. Adja meg ismét.',
ids_btn_cancel:'Mégse',
ids_dlg_pb_nameNullWarning:'A Név mező nem lehet üres.',
ids_dlg_sms_inputCenterNum:'Az SMS központ száma mező üres. Adja meg a számot.',
ids_ussd_rule:'Csak számjegyek, a „*” és a „#”  jel adhatók meg.',
ids_wifi_wifi:'WiFi',
ids_sms_selectSomeOptions:'Legfeljebb 3 névjegy',
ids_btn_new:'Új',
ids_fota_findNewVersion:'Új verzió keresése',
ids_security_pfNumRule:'Megjegyzés: A létrehozható porttovábbítások maximális száma 16.',
ids_wifi_showPwd:'Jelszó megjelenítése',
ids_security_urlFilterList:'URL szűrő lista',
ids_loginTimeout:'Bejelentkezési időtúllépés. Ismét be kell jelentkeznie.',
ids_title_alternateDnsServer:'Alternetív szerver',
ids_login_inputNewPwd:'Adja meg az új jelszót.',
ids_fota_updateTitle:'Rendszerfrissítések',
ids_login_inputConfirmPwd:'Adja meg a jelszó megerősítést.',
ids_hours:'óra',
ids_wifi_maxUser:'A felhasználók maximális száma',
ids_pb_addNew:'Hozzáadás',
ids_usage_timeLimit:'Időkorlát',
ids_sim_pinCode:'PIN-kód',
ids_wifi_wpaTkip:'TKIP',
ids_sim_autoPinState:'Jelenlegi állapot',
ids_security_dmzTitle:'DMZ',
ids_security_dmzIpInvalid:'A DMZ IP-címe érvénytelen.',
ids_btn_unblock:'Feloldás',
ids_fota_checkUpdate:'Frissítés',
ids_title_advanced:'Speciális beállítások',
ids_security_ipFilterWarn:'Az IP-szűrő már létezik.',
ids_fota_updateDescription:'Az új verzió telepítéséhez kattintson a „Frissítés” gombra.',
ids_btn_reset:'Visszaállítás',
ids_tr069_acsUrlRule:'Példa az Acs url-címének formátumára: http://ip-cím:port/xxx',
ids_show_again:'Ne mutassa többé',
ids_usage_hrs:'Óra',
ids_icon_battery:'Akkumulátor',
ids_sms_saveDevice:'Készülék',
ids_roamAppear:'Az adatkapcsolat roaming hálózatban történő használatához csúsztassa el az ujját. Az árakról tájékozódjon a szolgáltatójánál.',
ids_sys_chooseFile:'Válasszon fájlt',
ids_btn_refresh:'Frissítés',
ids_pb_phoneBook:'Telefonkönyv',
ids_net_select:'Hálózatválasztás',
ids_sim_pinError:'PIN-kód hiba!',
ids_sms_saveDraftFailed:'A vázlat mentése sikertelen',
ids_sms_delivered:'Kézbesítve',
ids_usage_autoDisconnected:'Kapcsolat automatikusan bontva',
ids_login_confirmPwd:'Jelszó megerősítése',
ids_security_addMacAddress:'MAC-cím hozzáadása',
ids_sim_noSimCard:'Nincs SIM-kártya',
ids_wifi_notSuppotWepWpa:'A WPS nem áll rendelkezésre WEP, WPA, WPA2 TKIP hálózatokban!',
ids_security_pfWarn:'A porttovábbítás már be van állítva.',
ids_fota_checking:'Ellenőrzés folyamatban...',
ids_dlg_pb_lenWarning:'A bevitt szám túl hosszú.',
ids_sim_newPinCode:'Új PIN-kód',
ids_sim_pinNotAvailable:'A PIN-kód nem áll rendelkezésre.',
ids_usage_clear:'Előzmények törlése',
ids_wifi_maxSsid:'Az SSID azonosító legfeljebb 32 karakterből állhat, és a következő szimbólumokat tartalmazhatja: 0-9, a-z, A-Z, "-", "_", ".". ," ".',
ids_usage_startTimeTips:'Adja meg az adatmennyiséget 1 és 43 200 között.',
ids_wifi_pbcConfiguration:'gombnyomásos konfigurálás',
ids_usage_dataConsumption:'Felhasznált adatforgalom',
ids_disable:'Letiltás',
ids_ucs2Orgsm7_text:'UCS2 Or GSM7',
ids_login_loginPwd:'Bejelentkezési jelszó',
ids_btn_save:'Mentés',
ids_wifi_802mode:'802.11 mód',
ids_pb_phoneNumber:'Telefonszám',
ids_ussd_timeOut:'Időtúllépés! Próbálja meg újra.',
ids_btn_reboot:'Újraindítás',
ids_minute:'perc',
ids_router_ipAddrInvalid:'Az IP-cím érvénytelen. Adja meg ismét.',
ids_router_startIpEmpty:'A kezdő IP-cím mező üres. Adja meg ismét.',
ids_sim_pinEnable:'PIN-kód automatikus jóváhagyása engedélyezve.',
ids_sim_pinCodeOperation:'PIN-kóddal kapcsolatos művelet',
ids_security_dmzInvalidLanSubnet:'A DMZ IP-cím nem tartozik a LAN alhálózathoz',
ids_net_service:'Szolgáltatás',
ids_router_ipRule:'Hiba történt! Vegye figyelembe, hogy az otthoni cím utáni 10 érték a rendszer számára fenntartott IP-cím, amely nem tartozhat a DHCP IP-készlethez.',
ids_usage_roaming:'Roaming',
ids_title_ussd:'USSD',
ids_btn_ok:'OK',
ids_sys_resetDecription:'Alapértelmezett gyári beállítások visszaállítása.',
ids_tr069_inputInformInterval:'Mentés előtt adja meg a tájékoztatási időszakot.',
ids_security_dmzIpAddr:'DMZ IP-címe',
ids_profile_inputApn:'Adja meg a hozzáférési pont nevét.',
ids_sys_restoreFactoryWarn:'Ez a művelet visszaállítja az alapértelmezett gyári beállításokat, majd újraindítja a készüléket. Biztosan folytatni kívánja?',
ids_net_registing:'Regisztráció folyamatban...',
ids_sys_backupDecription:'Töltse le a konfigurációt (biztonsági másolat)',
ids_sms_selectAnOption:'Válasszon egy opciót',
ids_tr069_inputAcsUrl:'Mentés előtt adja meg az ACS URL-címet.',
ids_tr069_acsUsername:'ACS felhasználónév',
ids_pdpTimer_0seconds:'0 másodperc',
ids_usage_home:'Főmenü',
ids_profile_deleteWarn:'Biztosan törölni kívánja?',
ids_sms_smsFull:'Az SMS fiók megtelt. Ahhoz, hogy további SMS üzeneteket küldhessen és tárolhasson, töröljön ki néhány SMS üzenetet.',
ids_tr069_connRqPw:'A csatlakozáshoz meg kell adni a jelszót',
ids_sim_pukError:'PUK-kód hiba!',
ids_sys_system:'Rendszer',
ids_security_PowerSavingSmart:'Intelligens',
ids_login_timeuseout:'Bejelentkezési időtúllépés. Indítsa újra a készüléket, és próbálja újra.',
ids_usage_minutesTimes:'Perc',
ids_sim_pukRule:'A PUK-kódnak 8 számjegyből kell állnia.',
ids_net_3gOnly:'Csak 3G',
ids_sim_nsck:'NSCK',
ids_subnetMask:'Alhálózati maszk',
ids_pdpTimer_60seconds:'60 másodperc',
ids_sim_pinDisable:'PIN-kód automatikus jóváhagyása letiltva.',
ids_sys_macAddress:'MAC-cím',
ids_menu_connection:'Csatlakozás',
ids_dlg_pb_tooManyNumbers:'A szerkesztéshez csak egy számot válasszon ki.',
ids_password:'Jelszó',
ids_security_virtualServer:'Virtuális szerver (statikus porttovábbítás)',
ids_security_ipFilterDes:'Végezze el a csomagok szűrését a következő protokollal, porttal és IP-címmel meghatározott szabályok szerint.',
ids_ussd_checkBlance:'Egyenleg megtekintése',
ids_title_tr069:'TR069',
ids_sms_draft:'Vázlat',
ids_wifi_encryption:'Titkosítás',
ids_title_ping:'Ping',
ids_foot_copyright:'Copyright 2016-2018 TCL Communication Ltd. Minden jog fenntartva.',
ids_tr069_acsPw:'ACS jelszó',
ids_help_userManual:'Használati utasítás',
ids_security_pfDescription:'A porttovábbítás lehetővé teszi a külső számítógépek számára a LAN által biztosított WWW, FTP és egyéb szolgáltatások elérését.',
ids_wifi_notSuppotMacFilter:'A WPS (2.0) művelet nem engedélyezhető, ha a MAC-cím szűrő aktív.',
ids_title_blockDevice:'Készülék letiltása',
ids_router_endGeaterStart:'A záró IP-cím értékének nagyobbnak kell lennie a "kezdő IP-cím" értékénél.',
ids_net_2gOnly:'Csak 2G',
ids_clearCode_Twentynine:'Hitelesítési hiba',
ids_usage_day:'nap',
ids_wifi_wepShare:'Megosztás',
ids_sms_messageSending:'Egy SMS küldése folyamatban van',
ids_wan_roamingPopCloseConntectTips:'Az adatbarangolás le lesz kapcsolva.',
ids_sd_currentFolder:'Aktuális mappa',
ids_wan_disconnected:'Leválasztva',
ids_security_numRule:'<b>Megjegyzés:</b>a létrehozható IP-szűrők maximális száma 16.',
ids_dns_manual_mode:'DNS manuális mód',
ids_login:'Bejelentkezés',
ids_security_PowerSavingTitle:'Energiatakarékos mód',
ids_security_lanIpAddr:'LAN IP-címe',
ids_menu_settings:'Beállítások',
ids_wifi_disconWarning:'Ez a művelet a Wi-Fi kapcsolat bontását eredményezi. Biztosan folytatni kívánja?',
ids_wifi_wpsActiveWarn:'WPS művelet folyamatban. Próbálja meg ismét két perc múlva!',
ids_login_loginUserName:'Bejelentkezési felhasználónév',
ids_wifi_wepWifiCertification:'A WEP kulcs 5, 13, 10 vagy 26.',
ids_connect:'Csatlakozás',
ids_btn_block:'Letiltás',
ids_pb_number:'Szám',
ids_login_wrongPwd:'Érvénytelen jelszó.',
ids_sms_smsForwarding:'SMS átirányítás',
ids_sys_selectFilePrompt:'Feltöltés előtt válasszon ki egy fájlt.',
ids_wifi_wifiSecurity:'Wi-Fi biztonság',
ids_btn_edit:'Szerkesztés',
ids_security_firewallSwitch:'Tűzfal kapcsoló',
ids_router_endIP:'Záró IP',
ids_sys_imei:'IMEI',
ids_sim_remainTime:'Fennmaradó próbálkozások száma:',
ids_update_Confirm:'A fájl letöltésre került. Biztosan el kívánja végezni a frissítést?',
ids_sim_pinConfirmed:'A PIN-kód megerősítésnek meg kell egyeznie az új PIN-kóddal.',
ids_filter_urlAddress:'URL cím',
ids_validate:'Jóváhagyás',
ids_security_subnetWarn:'A LAN IP-címének és az "IP-címnek" ugyanahhoz az alhálózathoz kell tartoznia.',
ids_sms_inputNum:'Adja meg a mobilszámot.',
ids_tr069_informInterval:'Tájékoztatási időszak (mp)',
ids_fota_haveNewVersion:'Új szoftver áll rendelkezésre. Frissítéshez kattintson.',
ids_sim_pukRequiredTips:'Ha első feloldáskor további információra van szüksége, kattintson az „A PUK-kód megadása szükséges” lehetőségre.',
ids_sms_emptyMessageWarn:'Az üzenet üres. Biztosan el kívánja küldeni ezt az üres üzenetet?',
ids_sim_pck:'PCK',
ids_usage_clearHistory:'Biztosan vissza kívánja állítani az összes statisztikát?',
ids_hour:'óra',
ids_tr069_connRqAuth:'A csatlakozáshoz hitelesítésre van szükség',
ids_wifi_off:'Kikapcsolva',
ids_pb_storageStatus:'Tárhely állapota',
ids_wan_connectedRule:'Ez a beállítás összekapcsolt módban nem használható. Kattintson a „Lecsatlakozás” gombra, majd próbálja újra.',
ids_menu_usage:'Adathasználat',
ids_security_dmzDescription:'Amennyiben a számítógép nem képes a hálózati alkalmazások átjárón keresztüli futtatására, engedélyezze a DMZ funkciót, majd adja meg a számítógép IP-címét az alábbi mezőben.',
ids_title_networkMode:'Hálózati mód',
ids_wifi_wifiOffTime_5min:'5 perc',
ids_wifi_pbc:'PBC',
ids_error:'Hiba!',
ids_sim_changePinError:'Hiba a PIN-kód megváltoztatása során!',
ids_security_wanPort:'WAN port',
ids_security_ipFilter:'IP-szűrő',
ids_tr069_inputConReqUserName:'Mentés előtt adja meg a csatlakozáshoz szükséges felhasználónevet.',
ids_tr069_informIntervalRule:'A tájékoztatási időszaknak 0 és 2678400 között kell lennie, beleértve a „0123456789” értéket is.',
ids_login_newPwd:'Új jelszó',
ids_pdpTimer_10seconds:'10 másodperc',
ids_security_virtualServerList:'Virtuális szerverlista',
ids_security_urlAddrNameWarn:'Az URL-cím már létezik.',
ids_btn_select:'Kiválasztás',
ids_router_endSameSubnet:'A záró IP-címnek és az "IP-címnek" ugyanahhoz az alhálózathoz kell tartoznia.',
ids_ussd_CodeEmpty:'A mező nem maradhat üresen!',
ids_sim_autoPinError:'Hiba a PIN-kód automatikus ellenőrzése során!',
ids_usage_cancelLimitTips:'Az adatkorlát kikapcsolásához állítsa az adatkorlát értékét 0-ra, és mentse el a választását.',
ids_sim_simLocked:'A SIM feloldási kód megadása szükséges',
ids_icon_timeElapsed:'Eltelt idő',
ids_sms_sendingPrompt:'Küldés folyamatban...Várjon!',
ids_tr069_inputAcsPassword:'Mentés előtt adja meg az ACS jelszót.',
ids_requestError:'Nincs válasz. Előfordulhat, hogy megszakadt a kapcsolat a készülékkel. Indítsa újra a készüléket, majd próbálkozzon újra.',
ids_profile_inputRule:'A hozzáférési pont nevének, valamint a hívószámnak 32 - 127 ASCII karakterből kell állnia, a következő szimbólumokat azonban nem tartalmazhatja: " : ; & .',
ids_net_active:'Aktív',
ids_sms_numberWarning:'A bevitt szám túl hosszú. Rövidítse le.',
ids_data:'Adatok',
ids_pdpTimer:'PDP időzítő',
ids_menu_sharing:'Megosztás',
ids_sd_noSdCard:'Nincs SD-kártya',
ids_wifi_pbcDecription:'1. Ha egyetlen kliens sem csatlakozik az útválasztóhoz, akkor tartsa lenyomva az útválasztó WPS gombját, amíg a Wi-Fi led villogni nem kezd. Ha legalább egy kliens csatlakozik az útválasztóhoz, akkor nyissa meg a csatlakoztatott készülék böngészőjét, látogassa meg a http://192.168.0.1/ címet, adja meg a jelszót, és kattintson a Továbbiak > WPS lehetőségre. Nyomja meg a WPS funkciógombot.<br/>2. Az útválasztóhoz csatlakoztatni kívánt készüléken (pl. számítógép vagy okostelefon) nyissa meg a WPS támogatással rendelkező Wi-Fi beállítási segédeszközt (a készülék eladójának kell biztosítania), és válassza a PBC üzemmódot vagy nyomja meg a PBC (WPS) gombot a készülék házán, ha rendelkezik ilyen gombbal.<br/>3. Az útválasztó és a kliens között automatikusan kapcsolat létesül kb. 2 perc elteltével.',
ids_sms_deleteSingleWarning:'Biztosan törölni kívánja az üzenete(ke)t?',
ids_menu_more:'Továbbiak',
ids_net_4gOnly:'Csak 4G',
ids_profileProtocal_none:'None',
ids_isSupportKickOff:'Másik felhasználó már be van jelentkezve, folytatja a bejelentkezést? Ez kizárja  a másik felhasználót.',
ids_changePassword_Tips:'Az aktuális felhasználónév és jelszó az alapértelmezett értékek. Azt javasoljuk, hogy változtassa meg a jelszót egy olyanra, amit könnyen megjegyez. A felhasználónév és a jelszó megváltoztatásához <a class="userpass_link">&nbsp;kattintson ide&nbsp;</a>.',
ids_wifi_wifiSleep:'WiFi Sleep',
ids_security_upnpDescription:'Az UPnP lehetővé teszi a készülékek hálózatra kapcsolását. Ez egy elosztott, nyitott struktúrájú protokoll, amely olyan bevett standardokon alapul, mint az internetes protokollkészlet (TCP/IP), HTTP, XML és SOAP.',
ids_sms_deleteAll:'Összes törlése',
ids_pb_location:'Helyzet',
ids_diagnostic:'Diagnosztika',
ids_security_macAddrInvalid:'A MAC-cím érvénytelen.',
ids_security_PowerSavingWiFiTips:'A Wi-Fi automatikusan kikapcsol, ha a kapcsolat hosszabb ideig készenléti állapotban van.',
ids_tr069_connRqUsername:'A csatlakozáshoz meg kell adni a felhasználónevet',
ids_security_PowerSavingWiFi:'Wi-Fi',
ids_profile_pwdRule:'A jelszó maximális hossza 31 karakter lehet, a következő szimbólumokat azonban nem tartalmazhatja: " : ; & .',
ids_tr069_inform:'Tájékoztatás',
ids_locked_permanently:'A készülék végleges zárolásra került, a feloldása pedig nem lehetséges!',
ids_sys_setRebootEvent:'A készülék újraindul. Várjon 1 percet, majd csatlakozzon újra a Wi-Fi eszközhöz.',
ids_sms_saveMode:'Mentés üzemmód',
ids_pb_add:'Hozzáadás',
ids_sim_spck:'SPCK',
ids_security_upnp:'UPnP',
ids_sms_encodingoptimization:'SMS kódolás optimalizálás',
ids_profile_inputDialNum:'Adja meg a hívószámot.',
ids_dlg_pb_deleteWarning:'Biztosan törölni kívánja?',
ids_security_enableIp:'IP-cím szűrő engedélyezése',
ids_sms_mobileNum:'Mobiltelefonszám',
ids_security_urlFilterTitle:'URL-szűrő',
ids_btn_setDefault:'Alapértelmezett',
ids_wan_connectedRuleIndia:'Kérjük válassza le az adatkapcsolatot mielőtt elindítja a fiók kezelését',
ids_title_loginSettings:'Bejelentkezési beállítások',
ids_profile_apn:'APN',
ids_pb_local:'Helyi',
ids_wan_roamingAutoConnect:'Automatikus csatlakozás még roaming üzemmódban is.',
ids_wifi_key:'Kulcs',
ids_login_userName:'adminisztrátor',
ids_wifi_offRule:'A Wi-Fi jelenleg ki van kapcsolva, mert hosszú ideje egyetlen kliens sem csatlakozott.  A Wi-Fi használatához aktiválja manuálisan a készülék bármelyik gombjának megnyomásával.',
ids_allow:'Engedélyezés',
ids_usage_MB:'MB',
ids_sim_simLockedTips:'Ha első feloldáskor további információra van szüksége, kattintson az „A SIM feloldási kódmegadása szükséges” lehetőségre.',
ids_login_inputOldPwd:'Adja meg a régi jelszót.',
ids_icon_downloaded:'Letöltve',
ids_sys_rebootWarn:'Biztosan újra kívánja indítani a készüléket?',
ids_security_enableFirewall:'Tűzfal engedélyezése',
ids_security_pfRangePortTip:'A LAN port száma és a WAN port száma nem egyeznek meg!',
ids_wifi_wepRule:'A WEP-kulcsnak 32 - 127 ASCII karakterből kell állnia, a következő szimbólumokat azonban nem tartalmazhatja: " : ; & .',
ids_sd_viewFile:'Fájl megtekintése',
ids_icon_debit:'Mennyiség',
ids_wifi_wpa2:'WPA2 PSK',
ids_sim_pinManagement:'PIN-kód kezelése',
ids_security_upnpStatus:'UPnP állapot',
ids_HelplineNumber:'Ügyfélszolgálati szám:',
ids_login_confirmPwdRule:'Az új jelszó nem egyezik meg a jelszó megerősítéssel.',
ids_router_leaseTime:'DHCP bérleti idő',
ids_sd_usedTotal:'(Felhasznált/Összes)',
ids_usage_monthlyDataPlan:'Havi adatcsomag',
ids_title_wps:'WPS',
ids_sms_newMessage:'Új üzenet',
ids_auto:'AUTOMATIKUS',
ids_usage_setTimeLimit:'Időkorlát beállítása',
ids_wifi_wep:'WEP',
ids_net_status:'Állapot',
ids_usage_minutes:'perc',
ids_wifi_wpsActive:'A WPS funkció aktív.',
ids_menu_usageSetting:'Felhasználási beállítások',
ids_login_otherLogin:'A rendszergazda már bejelentkezett. Próbálja újra később.',
ids_btn_wan_disconnect:'Kapcsolat bontása',
ids_tr069_inputAcsUserName:'Mentés előtt adja meg az ACS felhasználónevet.',
ids_security_ipFilterList:'IP szűrő lista',
ids_wifi_on:'Bekapcsolva',
ids_day:'nap',
ids_net_gsm:'2G',
ids_usage_notAccurate:'Előfordulhat, hogy a statisztikák nem pontosak.',
ids_sim_pukRequired:'A PUK-kód megadása szükséges',
ids_security_ipOption:'Opciók',
ids_net_lte:'4G',
ids_router_subnetEmpty:'Az Alhálózati maszk mező üres. Adja meg ismét.',
ids_pdpTimer_5seconds:'5 másodperc',
ids_wan_roamingPopWarningMessage:'Kattintson az <OK> gombra az adatok barangolás közben történő használatához. Ellenőrizze a hálózat szolgáltatóját az árazásért',
ids_manual:'Manuális',
ids_menu_connectDevice:'Csatlakoztatott készülék(ek)',
ids_profile_dialNumber:'Hívószám',
ids_menu_sms:'SMS',
ids_sys_hwVersion:'Hardververzió',
ids_usage_mothlyDataTips:'Adja meg az adatmennyiséget 1 és 1024 között.',
ids_pdpTimer_90seconds:'90 másodperc',
ids_title_macFilter:'MAC szűrő',
ids_netMode_Automatic4g3g2g:'Automatikus(4G & 3G & 2G)',
ids_sys_noFileChosen:'Nincs fájl kiválasztva',
ids_dlg_sms_mobileNumRule:'Adjon meg egy érvényes számot: kizárólag a 0 és 9 közötti számjegyeket és a „+” karaktert tartalmazhatja, szóközök és speciális karakterek nélkül.',
ids_wan_connecting:'Csatlakozás folyamatban...',
ids_profile_inputName:'Mentés előtt adja meg a profilnevet.',
ids_wan_Block:'A MAC-címek listája megtelt, ezért a kérelem nem dolgozható fel.',
ids_icon_people:'Személyek',
ids_sim_autoValidate:'Automatikus hitelesítés',
ids_menu_language:'Nyelv',
ids_wifi_wpsPinRule:'A WPS PIN-kódjának 4-8 számjegyből kell állnia.',
ids_title_pinCodeSettings:'PIN-kód beállítások',
ids_net_searching:'Keresés folyamatban…',
ids_wifi_wpaRule:'A WPA PSK-kulcsának 32 - 127 ASCII karakterből kell állnia, a következő szimbólumokat azonban nem tartalmazhatja: " : ; & .',
ids_ussd_notSupport:'Nem támogatott! Próbálja meg újra.',
ids_tr069_acsUrl:'ACS URL-cím',
ids_sms_report:'SMS jelentés',
ids_sim_cck:'CCK',
ids_security:'Biztonság',
ids_enable:'Engedélyezés',
ids_wifi_wpaAes:'AES',
ids_btn_next:'Következő',
ids_profile_profileName:'Profil neve',
ids_wifi_wepOpen:'Megnyitás',
ids_wan_connectIPMode:'Csatlakozás IP üzemmódja',
ids_router_subnetInvalid:'Az alhálózati maszk érvénytelen. Adja meg ismét.',
ids_pdpTimer_30seconds:'30 másodperc',
ids_usage_min:'Perc',
ids_wan_connected:'Csatlakozva'
}