var resourceInfo={
ids_fota_upgradingTips:'NÃO desligue durante a atualização. O dispositivo será reiniciado após a atualização.',
ids_usage_billingDay:'Dia de faturação',
ids_sms_phoneNumberInvalid:'Número de telefone inválido',
ids_btn_logout:'Sair',
ids_wifi_ssidBroadcast:'Transmissão SSID',
ids_wifi_wpaDescription:'A chave WPA pré-partilhada (PSK) deve ter entre 8 e 63 caracteres ASCII.',
ids_dlg_pb_nameRule:'O Nome não pode incluir os seguintes caracteres:"\\","\\\'".',
ids_usage_GB:'GB',
ids_UserNameRule32:'O nome do utilizador pode ter um máximo de 32 caracteres, à excepção de: " : ; &',
ids_pdpTimer_120seconds:'120 segundos',
ids_profile_profileNameRule:'O nome do perfil pode ter um máximo de 31 caracteres, à excepção de: , " : ; \\ & % + < > ?.',
ids_security_ipFilterDescription:'O intervalo da porta é 0 - 65535.',
ids_back:'Voltar',
ids_usage_dataUsageReach:'Quando a utilização de dados atinge o plano de dados mensal',
ids_router_startIpInvalid:'O endereço IP inicial não é válido. Introduza-o novamente!',
ids_iptype:'Tipo de IP',
ids_net_selectWarn:'Seleccione uma rede!',
ids_login_inputCurrPwd:'Palavra-passe atual errada.',
ids_sim_autoPin:'Validação automática do código PIN',
ids_wifi_offTip:'O Wi-Fi está desativado. Tente novamente depois de ativar o Wi-Fi.',
ids_net_3g4gOnly:'Só 3G / 4G',
ids_wifi_wifiOffTime_30min:'30 minutos',
ids_fota_batteryTips:'Bateria fraca. O dispositivo não pode ser atualizado',
ids_wifi_wpa:'WPA PSK',
ids_wifi_cipher:'Tipo de cifra',
ids_sim_initializing:'Cartão SIM a inicializar.',
ids_success:'Êxito',
ids_sim_lockCodeRule:'O código SIM LOCK deve ter 10 dígitos.',
ids_sim_pinRequired:'PIN necessário',
ids_router_endIpInvalid:'O endereço IP final não é válido. Introduza-o novamente!',
ids_security_macFilterDescription:'Controle e gira o dispositivo que permite aceder à WLAN (aumente a segurança da WLAN).',
ids_net_lteOnlyVal:'Só LTE',
ids_security_PowerSavingSmartTips:'Todos os LED apagam automaticamente exceto o LED de alimentação quando não existe acesso ao Wi-Fi ou operação manual durante 30 seg.',
ids_wan_tips:'Erro! Histórico de utilização de dados ultrapassado. Pode repor o Plano de dados mensal e voltar a ligar.',
ids_wan_roamingWarningMessage:'O roaming de dados permite que você navegue na web, use e-mail, MMS e outros serviços de dados enquanto estiver no exterior. Verifique com seu provedor de rede para obter preços',
ids_title_preferredDnsServer:'Servidor DNS preferencial',
ids_modify:'Modificar',
ids_title_connectMode:'Modo de ligação',
ids_net_noService:'Sem rede',
ids_net_2g3gOnly:'Só 2G / 3G',
ids_sms_chatInputConfirm:'Prima Enter para concluir',
ids_sms_mobileNumRule:'O número de telemóvel pode ter um máximo de 20 dígitos, incluindo "+0123456789"; introduza-o novamente.',
ids_dlg_pb_NumberNullWarning:'O Número de telefone não pode estar vazio.',
ids_usage_hours:'horas',
ids_usage_timePassed:'Tempo decorrido',
ids_wifi_country:'País',
ids_wifi_wlan_mode:'Modo Wlan',
ids_net_umts:'3G',
ids_fail:'Sem êxito!',
ids_wifi_wpsPin:'PIN de WPS',
ids_wan_inputDeviceName:'introduza o nome do dispositivo',
ids_sms_sendFail:'Falha ao enviar SMS',
ids_sim_pukCode:'Código PUK',
ids_sms_newMessageOn:'não lido de',
ids_tr069_inputConReqPassword:'Introduza a palavra-passe do pedido de ligação antes de a guardar.',
ids_sys_swVersion:'Versão de software',
ids_sim_simlockError:'Erro de bloqueio do SIM!',
ids_security_ipFilterPort:'O intervalo da porta é 0 - 65535.',
ids_wifi_inputSsid:'Introduza o SSID.',
ids_clearCode_Thirtythree:'Sem dados de serviço',
ids_sim_confirmPinCode:'Confirmação código PIN',
ids_security_dmzStatus:'Estado DMZ',
ids_security_macAddrNameWarn:'O endereço MAC já existe.',
ids_security_portRule:'O intervalo da porta é 1 - 65535.',
ids_router_startIP:'IP de início',
ids_fotaUpdate_openRoaming_meg:'Podem aplicar-se custos adicionais para transferência em roaming. Verifique com o seu operador. Pretende continuar?',
ids_net_forbid:'Proibida',
ids_btn_loginTimeout:'voltar a registar',
ids_security_wanIpAddr:'Endereço IP WAN',
ids_profile_userName:'Nome do utilizador',
ids_profile_password:'Palavra-passe',
ids_btn_restore:'Restaurar',
ids_tips_livechat:'Chat ao vivo',
ids_login_inputPwd:'Introduza a palavra-passe.',
ids_login_inputUserName:'Introduza o nome de utilizador.',
ids_pdpTimer_20seconds:'20 segundos',
ids_btn_previous:'Anterior',
ids_sys_restoreBackupWarn:'Esta acção vai actualizar as definições e reiniciar o dispositivo quando o envio for concluído. Tem a certeza de que pretende continuar?',
ids_security_ipLanWan:'Nota: O intervalo de valores da Porta LAN/WAN é 0-65535 e 0 significa qualquer um.',
ids_usage_KB:'KB',
ids_login_remenberPassword:'Lembrar palavra-passe',
ids_security_firewallDes:'Esta página fornece informações sobre como ativar o filtro de firewall. O filtro de endereço IP e funções PING da porta WAN só estão disponíveis quando o firewall está ativado.',
ids_title_wifiSettings:'Definições Wi-Fi',
ids_sim_invalidSimCard:'Cartão SIM inválido',
ids_sim_unknown:'Desconhecido',
ids_wan_disconnecting:'A desligar...',
ids_btn_delete:'Eliminar',
ids_tr069_client:'Cliente TR-069 – Configuração',
ids_wifi_channel:'Canal Wi-Fi',
ids_title_dnsSetting:'DNS',
ids_pb_name:'Nome',
ids_btn_apply:'Aplicar',
ids_fota_latestVersion:'Esta já é a última versão.',
ids_security_urlAddrInvalid:'O endereço URL é inválido.',
ids_wan_cannotBlock:'O filtro Mac está como Permitir agora. Não é possível processar esta opção.',
ids_deny:'Recusar',
ids_sms_saveDraftSuccess:'SMS guardada como rascunho',
ids_network_notAvailableFunctionWarn:'Desligue a ligação de dados antes de iniciar a gestão do perfil',
ids_usage_duration:'Tempo de duração',
ids_sim_rck:'RCK',
ids_sms_deleteWarning:'Tem a certeza de que pretende eliminar as mensagens?',
ids_icon_uploaded:'Carregado',
ids_orange_sim_pinOperationWarn:'Não é possível atualizar as definições do código PIN enquanto está ligado à Internet.',
ids_dlg_pb_mobileNumRule:'O comprimento máximo do Número de telefone é 40 dígitos, incluindo "+0123456789". Introduza novamente.',
ids_title_profilesManagement:'Gestão de perfis',
ids_wifi_wifiOffTime_20min:'20 minutos',
ids_sim_lockForbidden:'O código SIM LOCK é proibido!',
ids_sim_pinRule:'O código PIN deve ter entre 4 e 8 dígitos.',
ids_security_dmzTips:'O DMZ permite que o dispositivo selecionado contorne as funcionalidades de firewall do gateway e permite acesso ilimitado da Internet para esse dispositivo.',
ids_router_startSameSubnet:'"Endereço IP inicial" e "Endereço IP" devem pertencer à mesma sub-rede.',
ids_btn_help:'Ajuda',
ids_menu_smsSettings:'Definições de SMS',
ids_profile_nameWarn:'Este nome de perfil já existe.',
ids_wifi_wifiOffTime_10min:'10 minutos',
ids_sim_newPinRule:'O novo código PIN deve ter entre 4 e 8 dígitos.',
ids_sim_comfirmPinRule:'O código PIN confirmado deve ter entre 4 e 8 dígitos.',
ids_sim_enterValidCode:'Introduza um código PIN válido.',
ids_btn_send:'Enviar',
ids_net_available:'Disponível',
ids_profile_numRule:'Nota: pode criar um máximo de 15 perfis.',
ids_gsm7_text:'GSM 7',
ids_dlg_sms_smsForwardNumEmpty:'O Número de telemóvel está vazio. Introduza o número.',
ids_wifi_wepDescription:'A chave WEP é composta por 5 ou 13 caracteres ASCII ou 10 ou 26 dígitos hexadecimais.',
ids_sd_sdCard:'Cartão SD',
ids_sys_deviceName:'Nome do dispositivo',
ids_days:'dias',
ids_sys_ipAddress:'Endereço IP',
ids_login_nameOrPwdWrong:'Nome de utilizador ou palavra-passe incorretos!',
ids_profile_userNameRule:'O nome do utilizador pode ter um máximo de 31 caracteres, à excepção de: " : ; &',
ids_wifi_cannotSet:'Wi-Fi é desativado agora, não pode processar essa função.',
ids_router_ipAddrEmpty:'Endereço IP vazio. Introduza-o novamente!',
ids_wifi_pinDecription:'PIN WPS (configuração WPS através da introdução de um código especial de 8 dígitos):</br>1. Se, pelo menos, um cliente estiver ligado ao router, abra o browser no dispositivo ligado e vá para http://192.168.0.1/, introduza a palavra-passe e clique em Mais > WPS. Selecione o PIN WPS.</br>2. No dispositivo que pretende ligar ao router (por ex. PC ou smartphone), abra o Utilitário de configuração do Wi-Fi que suporta WPS (deve ser fornecido pelo fornecedor do dispositivo) e escolha o modo PIN WPS. Será gerado um PIN WPS de 8 dígitos.</br>3. Volte à interface Web do router, introduza o PIN WPS de 8 dígitos no campo PIN WPS e clique em Aplicar.</br>4. A ligação entre o router e o cliente será automaticamente estabelecida em cerca de 2 minutos.',
ids_tr069_tips:'Selecione os valores pretendidos e clique em “Aplicar/Guardar” para configurar as opções do cliente TR-069.',
ids_more_onlineUpdate:'Atualização online',
ids_security_btnAdd:'Adicionar',
ids_sms_autoForward:'Reenvio de SMS para telemóvel',
ids_sim_simLockCode:'Código de bloqueio do SIM',
ids_router_restartWarn:'Esta acção requer que o dispositivo seja reiniciado. Tem a certeza de que pretende continuar?',
ids_sms_saveSimCard:'Cartão SIM',
ids_automatic:'Automática',
ids_security_portTips:'Nota: Especifique a porta ou grupo de portas, exemplo:80 ou 35500-35510.',
ids_wifi_wpsNotSuppotSSIDHidden:'SSID oculto. Não é possível definir WPS.',
ids_netMode_Automatic3g2g:'Automática(3G & 2G)',
ids_wifi_apIsotation:'Isolamento AP',
ids_security_portForwarding:'Encaminhamento de portas',
ids_btn_add:'Adicionar',
ids_usage_billingTimeTips:'Introduza o dia entre 1 e 31.',
ids_minutes:'minutos',
ids_ussd_inputDescription:'Introduza o código USSD',
ids_fota_upgrading:'A atualizar…',
ids_router_dhcpServer:'Servidor DHCP',
ids_sim_pinRequiredTips:'Para mais informações, clique em "PIN necessário" para desbloquear primeiro.',
ids_login_checkPwdRule:'Palavra-passe inválida! A palavra-passe de início de sessão pode ter um máximo de 16 caracteres, incluindo 0-9, a-z, A-Z,"-+!@$#^&*"; introduza-a novamente.',
ids_wifi_wifiOffTime:'Tempo de desativação do Wi-Fi',
ids_sd_sdShareMode:'Modo de partilha de SD',
ids_btn_continue:'Continuar',
ids_profile_protocal:'Protocolo',
ids_security_lanPort:'Porta LAN',
ids_dlg_sms_reInputCenterNum:'O número do centro de SMS não é válido. Introduza-o novamente!',
ids_btn_backup:'Cópia',
ids_wan_connected_num:'Ligado',
ids_sms_centerNum:'Centro de SMS',
ids_fota_downloading:'A transferir…',
ids_wifi_wpaWpa2Psk:'WPA/WPA2 PSK',
ids_usage_of:'de',
ids_sys_rebootDecription:'Clique neste botão para reiniciar o dispositivo.',
ids_title_about:'Sobre',
ids_sim_nck:'NCK',
ids_net_operator:'Operador',
ids_router_endIpEmpty:'Endereço IP final vazio. Introduza-o novamente!',
ids_btn_cancel:'Cancelar',
ids_dlg_pb_nameNullWarning:'O Nome não pode estar vazio.',
ids_dlg_sms_inputCenterNum:'Número do centro de SMS vazio. Introduza o número!',
ids_ussd_rule:'Apenas "*" "#" e números podem ser inseridos.',
ids_wifi_wifi:'Wi-Fi',
ids_sms_selectSomeOptions:'3 contactos no máximo',
ids_btn_new:'Novo',
ids_fota_findNewVersion:'Foi encontrada uma nova versão',
ids_security_pfNumRule:'Nota: O numero máximo de regras é 16.',
ids_wifi_showPwd:'Mostrar palavra-passe',
ids_security_urlFilterList:'Lista de filtros URL',
ids_loginTimeout:'Tempo limite de início de sessão excedido. É necessário voltar a iniciar sessão.',
ids_title_alternateDnsServer:'Servidor DNS alternativo',
ids_login_inputNewPwd:'Introduza a nova palavra-passe.',
ids_fota_updateTitle:'Atualizações do sistema',
ids_login_inputConfirmPwd:'Introduza a palavra-passe confirmada.',
ids_hours:'horas',
ids_wifi_maxUser:'N.º máximo de utilizadores',
ids_pb_addNew:'Adicionar',
ids_usage_timeLimit:'Limite de tempo',
ids_sim_pinCode:'Código PIN',
ids_wifi_wpaTkip:'TKIP',
ids_sim_autoPinState:'Estado atual',
ids_security_dmzTitle:'DMZ',
ids_security_dmzIpInvalid:'O endereço IP DMZ não é um endereço IP válido.',
ids_btn_unblock:'Desbloquear',
ids_fota_checkUpdate:'Atualizar',
ids_title_advanced:'Definições avançadas',
ids_security_ipFilterWarn:'O Filtro IP já existe.',
ids_fota_updateDescription:'Clique em "Atualizar" para atualizar para a versão mais recente.',
ids_btn_reset:'Repor',
ids_tr069_acsUrlRule:'Formato do url acs:por ex.:http://endereço ip:porta/xxx',
ids_show_again:'Não mostrar novamente',
ids_usage_hrs:'h',
ids_icon_battery:'Bateria',
ids_sms_saveDevice:'Dispositivo',
ids_roamAppear:'Deslize para utilizar os dados em roaming. Verifique os custos com o seu operador.',
ids_sys_chooseFile:'Escolher ficheiro',
ids_btn_refresh:'Actualizar',
ids_pb_phoneBook:'Contactos',
ids_net_select:'Selecção de rede',
ids_sim_pinError:'Erro de PIN!',
ids_sms_saveDraftFailed:'Falha ao guardar rascunho',
ids_sms_delivered:'Entregue',
ids_usage_autoDisconnected:'Desligamento automático',
ids_login_confirmPwd:'Confirmar palavra-passe',
ids_security_addMacAddress:'Adicionar endereço MAC',
ids_sim_noSimCard:'Sem cartão SIM',
ids_wifi_notSuppotWepWpa:'O WPS não está disponível para WEP, WPA e WPA2 TKIP!',
ids_security_pfWarn:'O encaminhamento da porta já existe.',
ids_fota_checking:'Verificando…',
ids_dlg_pb_lenWarning:'O texto inserido é demasiado longo',
ids_sim_newPinCode:'Novo código PIN',
ids_sim_pinNotAvailable:'O código PIN não está disponível.',
ids_usage_clear:'Limpar histórico',
ids_wifi_maxSsid:'O SSID pode ter um máximo de 32 caracteres, incluindo 0-9, a-z, A-Z, "-", "_", "." ," ".',
ids_usage_startTimeTips:'Introduza os dados entre 1 e 43200.',
ids_wifi_pbcConfiguration:'Configuração do botão de pressão',
ids_usage_dataConsumption:'Consumo de dados',
ids_disable:'Desactivar',
ids_ucs2Orgsm7_text:'UCS2 Or GSM7',
ids_login_loginPwd:'Palavra-passe de início de sessão',
ids_btn_save:'Guardar',
ids_wifi_802mode:'Modo 802.11',
ids_pb_phoneNumber:'Número de telefone',
ids_ussd_timeOut:'Tempo limite excedido! Tente novamente.',
ids_btn_reboot:'Reiniciar',
ids_minute:'minuto',
ids_router_ipAddrInvalid:'O endereço IP não é válido. Introduza-o novamente!',
ids_router_startIpEmpty:'Endereço IP inicial vazio. Introduza-o novamente!',
ids_sim_pinEnable:'Validação automática do PIN ativada.',
ids_sim_pinCodeOperation:'Operação de código PIN',
ids_security_dmzInvalidLanSubnet:'O endereço IP DMZ não está na sub-rede LAN.',
ids_net_service:'Serviço',
ids_router_ipRule:'Erro! Os 10 endereços sucedentes são IPs de sistema pré-reservados e não podem ser incluídos na gama de IPs a atribui.',
ids_usage_roaming:'Roaming',
ids_title_ussd:'USSD',
ids_btn_ok:'OK',
ids_sys_resetDecription:'Restaurar predefinições de fábrica',
ids_tr069_inputInformInterval:'Introduza o intervalo de comunicação antes de o guardar.',
ids_security_dmzIpAddr:'endereço DMZ IP',
ids_profile_inputApn:'Introduza o APN!',
ids_sys_restoreFactoryWarn:'Esta acção vai restaurar as predefinições de fábrica e reiniciar o dispositivo. Tem a certeza de que pretende continuar?',
ids_net_registing:'A registar...',
ids_sys_backupDecription:'Transfira (Cópia) a configuração.',
ids_sms_selectAnOption:'Selecione uma opção',
ids_tr069_inputAcsUrl:'Introduza o url acs antes de o guardar.',
ids_tr069_acsUsername:'Nome do utilizador ACS',
ids_pdpTimer_0seconds:'0 segundo',
ids_usage_home:'Início',
ids_profile_deleteWarn:'Tem a certeza de que pretende eliminar?',
ids_sms_smsFull:'Caixa de SMS enviados cheia; elimine alguns SMS para poder enviar/guardar novos SMS.',
ids_tr069_connRqPw:'Palavra-passe do pedido de ligação',
ids_sim_pukError:'Erro de PUK!',
ids_sys_system:'Sistema',
ids_security_PowerSavingSmart:'Inteligente',
ids_login_timeuseout:'O tempo limite do início de sessão expirou. Reinicie e tente novamente.',
ids_usage_minutesTimes:'min(s)',
ids_sim_pukRule:'O código PUK deve ter 8 dígitos.',
ids_net_3gOnly:'Só 3G',
ids_sim_nsck:'NSCK',
ids_subnetMask:'Máscara de sub-rede',
ids_pdpTimer_60seconds:'60 segundos',
ids_sim_pinDisable:'Validação automática do PIN desativada.',
ids_sys_macAddress:'Endereço MAC',
ids_menu_connection:'Ligação',
ids_dlg_pb_tooManyNumbers:'Para começar a editar, selecione apenas um número.',
ids_password:'Palavra-passe',
ids_security_virtualServer:'Servidor virtual (encaminhamento de portas estático)',
ids_security_ipFilterDes:'Filtre os pacotes usando as seguintes regras especificadas com protocolo, porta e endereço IP.',
ids_ussd_checkBlance:'Verificar o saldo',
ids_title_tr069:'TR069',
ids_sms_draft:'Rascunho',
ids_wifi_encryption:'Encriptação',
ids_title_ping:'Ping',
ids_foot_copyright:'Copyright 2016-2018 TCL Communication Ltd. Todos os direitos reservados',
ids_tr069_acsPw:'Palavra-passe ACS',
ids_help_userManual:'Manual do usuário',
ids_security_pfDescription:'O Reencaminhamento de portas permite que computadores externos acedam a WWW, FTP ou a outros serviços fornecidos por LAN.',
ids_wifi_notSuppotMacFilter:'O procedimento WPS (versão 2.0) não pode ser ativado se o filtro de endereço Mac estiver ativado.',
ids_title_blockDevice:'Bloquear dispositivo',
ids_router_endGeaterStart:'"Endereço IP final" deve ser maior que "Endereço IP inicial".',
ids_net_2gOnly:'Só 2G',
ids_clearCode_Twentynine:'Falha de autenticação',
ids_usage_day:'dia',
ids_wifi_wepShare:'Partilhado',
ids_sms_messageSending:'Está a ser enviada uma SMS',
ids_wan_roamingPopCloseConntectTips:'O roaming de dados será desativado.',
ids_sd_currentFolder:'Pasta atual',
ids_wan_disconnected:'Desligado',
ids_security_numRule:'Nota: O numero máximo de regras é 16.',
ids_dns_manual_mode:'Modo manual DNS',
ids_login:'Entrar',
ids_security_PowerSavingTitle:'Poupança de energia',
ids_security_lanIpAddr:'Endereço IP de LAN',
ids_menu_settings:'Definições',
ids_wifi_disconWarning:'Esta acção vai desligar o Wi-Fi. Tem a certeza de que pretende continuar?',
ids_wifi_wpsActiveWarn:'Procedimento WPS em curso. Tente novamente dois minutos mais tarde!',
ids_login_loginUserName:'Nome de utilizador de início de sessão',
ids_wifi_wepWifiCertification:'A chave WEP é composta por 5 ou 13 ou 10 ou 26.',
ids_connect:'Ligar',
ids_btn_block:'Bloquear',
ids_pb_number:'N.º',
ids_login_wrongPwd:'Palavra-passe errada!',
ids_sms_smsForwarding:'Reenvio de SMS',
ids_sys_selectFilePrompt:'Seleccione um ficheiro antes de enviar.',
ids_wifi_wifiSecurity:'Segurança Wi-Fi',
ids_btn_edit:'Editar',
ids_security_firewallSwitch:'Firewall switch',
ids_router_endIP:'IP de fim',
ids_sys_imei:'IMEI',
ids_sim_remainTime:'N.º de tentativas restantes',
ids_update_Confirm:'O ficheiro já foi transferido, tem a certeza de que pretende atualizá-lo?',
ids_sim_pinConfirmed:'O código PIN confirmado deve ser idêntico ao novo código PIN.',
ids_filter_urlAddress:'Endereço URL',
ids_validate:'Validar',
ids_security_subnetWarn:'O endereço IP de LAN e o endereço IP devem pertencer à mesma sub-rede.',
ids_sms_inputNum:'Introduza um número de telemóvel.',
ids_tr069_informInterval:'Intervalo(s) de comunicação',
ids_fota_haveNewVersion:'Está disponível novo SW. Clique para atualizar.',
ids_sim_pukRequiredTips:'Para mais informações, clique em "PUK necessário" para desbloquear primeiro.',
ids_sms_emptyMessageWarn:'Mensagem vazia. Enviar esta mensagem vazia?',
ids_sim_pck:'PCK',
ids_usage_clearHistory:'Repor todas as estatísticas agora?',
ids_hour:'hora',
ids_tr069_connRqAuth:'Autenticação do pedido de ligação',
ids_wifi_off:'Desligado',
ids_pb_storageStatus:'Estado do armazenamento',
ids_wan_connectedRule:'Esta definição não pode ser utilizada no modo ligado. Clique em “Desligar” e tente novamente.',
ids_menu_usage:'Utilização',
ids_security_dmzDescription:'Se um PC não conseguir executar as aplicações de rede através do gateway, ative a função DMZ e introduza o endereço IP do PC abaixo.',
ids_title_networkMode:'Modo de rede',
ids_wifi_wifiOffTime_5min:'5 minutos',
ids_wifi_pbc:'PBC',
ids_error:'Erro!',
ids_sim_changePinError:'Erro de alteração de PIN!',
ids_security_wanPort:'Porta WAN',
ids_security_ipFilter:'Filtro IP',
ids_tr069_inputConReqUserName:'Introduza o nome de utilizador do pedido de ligação antes de o guardar.',
ids_tr069_informIntervalRule:'O intervalo de comunicação deve ser 0-2678400, incluindo "0123456789".',
ids_login_newPwd:'Nova palavra-passe',
ids_pdpTimer_10seconds:'10 segundos',
ids_security_virtualServerList:'Lista de servidor virtual',
ids_security_urlAddrNameWarn:'O endereço URL já existe.',
ids_btn_select:'Seleccionar',
ids_router_endSameSubnet:'"Endereço IP final" e "Endereço IP" devem pertencer à mesma sub-rede.',
ids_ussd_CodeEmpty:'A caixa de introdução não pode estar em branco!',
ids_sim_autoPinError:'Erro de verificação automática do PIN!',
ids_usage_cancelLimitTips:'Defina o limite de dados como 0 e guarde para cancelar qualquer limite de dados.',
ids_sim_simLocked:'Bloqueio do SIM necessário',
ids_icon_timeElapsed:'Tempo decorrido',
ids_sms_sendingPrompt:'A enviar..., aguarde!',
ids_tr069_inputAcsPassword:'Introduza a palavra-passe acs antes de a guardar.',
ids_requestError:'Não foi possível efectuar o pedido; o dispositivo pode ter sido desligado. Reinicie o dispositivo e tente novamente.',
ids_profile_inputRule:'APN e número de discagem devem ser caracteres ASCII que variaram de 32 a 127, exceto para:  " : ; & .',
ids_net_active:'Activa',
ids_sms_numberWarning:'Limite de comprimento de caracteres excedido. O máximo é 1530 bytes',
ids_data:'Dados',
ids_pdpTimer:'Temporizador PDP',
ids_menu_sharing:'Partilhar',
ids_sd_noSdCard:'Nenhum cartão SD',
ids_wifi_pbcDecription:'1. Se não houver nenhum cliente ligado ao router, prima sem soltar o botão WPS no router e aguarde até o LED do Wi-Fi piscar. Se, pelo menos, um cliente estiver ligado ao router, abra o browser no dispositivo ligado e vá para http://192.168.0.1/, introduza a palavra-passe e clique em Mais > WPS. Prima o botão de função WPS.</br>2. No dispositivo que pretende ligar ao router (por ex. PC ou smartphone), abra o Utilitário de configuração do Wi-Fi que suporta WPS (deve ser fornecido pelo fornecedor do dispositivo) e escolha o modo PBC ou prima o botão PBC (WPS) no corpo do dispositivo, se disponível.</br>3. A ligação entre o router e o cliente será automaticamente estabelecida em cerca de 2 minutos.',
ids_sms_deleteSingleWarning:'Tem a certeza de que pretende eliminar as mensagens?',
ids_menu_more:'Mais',
ids_net_4gOnly:'Só 4G',
ids_profileProtocal_none:'None',
ids_isSupportKickOff:'Já existe outro utilizador com sessão iniciada, pretende iniciar sessão mesmo assim? Isto irá expulsar o outro utilizador.',
ids_changePassword_Tips:'O seu nome de utilizador e palavra-passe são a predefinição. Aconselhamos que altere a sua palavra-passe para algo de que se recorde facilmente. <a class="userpass_link">&nbsp;Clique aqui&nbsp;</a> para alterar o nome de utilizador e a palavra-passe.',
ids_wifi_wifiSleep:'WiFi Sleep',
ids_security_upnpDescription:'UPnP permite uma ligação em rede dispositivo a dispositivo, é um protocolo de arquitetura distribuída e aberta baseado em normas estabelecidas, tais como o conjunto de protocolos de Internet (TCP/IP), HTTP, XML e SOAP.',
ids_sms_deleteAll:'Eliminar todos',
ids_pb_location:'Localização',
ids_diagnostic:'Diagnóstico',
ids_security_macAddrInvalid:'O endereço MAC não é válido.',
ids_security_PowerSavingWiFiTips:'O Wi-Fi desliga automaticamente se a ligação estiver inativa durante muito tempo.',
ids_tr069_connRqUsername:'Nome de utilizador do pedido de ligação',
ids_security_PowerSavingWiFi:'Wi-Fi',
ids_profile_pwdRule:'O comprimento máximo da senha é de 31, exceto para: ",:; & .',
ids_tr069_inform:'Aviso',
ids_locked_permanently:'Este dispositivo foi bloqueado definitivamente e não pode ser desbloqueado!',
ids_sys_setRebootEvent:'O dispositivo está a reiniciar; aguarde 60 segundos e restabeleça a ligação ao equipamento Wi-Fi.',
ids_sms_saveMode:'Modo de gravação',
ids_pb_add:'Adicionar',
ids_sim_spck:'SPCK',
ids_security_upnp:'UPnP',
ids_sms_encodingoptimization:'Otimização de codificação de SMS',
ids_profile_inputDialNum:'Introduza o número de marcação!',
ids_dlg_pb_deleteWarning:'Tem a certeza de que pretende eliminar?',
ids_security_enableIp:'Ativar filtro de endereço IP',
ids_sms_mobileNum:'Número de telemóvel',
ids_security_urlFilterTitle:'Filtro URL',
ids_btn_setDefault:'Predefinir',
ids_wan_connectedRuleIndia:'Desligue a ligação de dados antes de iniciar a gestão do perfil.',
ids_title_loginSettings:'Definições de início de sessão',
ids_profile_apn:'APN',
ids_pb_local:'Local',
ids_wan_roamingAutoConnect:'Estabeleça ligação automaticamente até mesmo quando estiver em roaming.',
ids_wifi_key:'Chave',
ids_login_userName:'admin',
ids_wifi_offRule:'O Wi-Fi está desativado no momento, porque o cliente esteve desligado durante algum tempo. Ative o Wi-Fi manualmente premindo qualquer botão no dispositivo.',
ids_allow:'Permitir',
ids_usage_MB:'MB',
ids_sim_simLockedTips:'Para mais informações, clique em "Bloqueio do SIM necessário" para desbloquear primeiro.',
ids_login_inputOldPwd:'Introduza a palavra-passe antiga.',
ids_icon_downloaded:'Transferido',
ids_sys_rebootWarn:'Tem a certeza de que pretende reiniciar este dispositivo?',
ids_security_enableFirewall:'Ativar firewall',
ids_security_pfRangePortTip:'O número da porta LAN não é o mesmo que o número da porta WAN!',
ids_wifi_wepRule:'A chave WEP deve ter entre 32 e 127 caracteres ASCII, exceto para: " : ; & .',
ids_sd_viewFile:'Ver ficheiro',
ids_icon_debit:'Débito',
ids_wifi_wpa2:'WPA2 PSK',
ids_sim_pinManagement:'Gestão de códigos PIN',
ids_security_upnpStatus:'Estado UPnP',
ids_HelplineNumber:'Número da linha de ajuda:',
ids_login_confirmPwdRule:'A nova palavra-passe e a palavra-passe Confirmação devem ser idênticas.',
ids_router_leaseTime:'Duração da concessão de IP do DHCP',
ids_sd_usedTotal:'(Utilizado/Total)',
ids_usage_monthlyDataPlan:'Plano de dados mensal',
ids_title_wps:'WPS',
ids_sms_newMessage:'Nova Mensagem',
ids_auto:'AUTO',
ids_usage_setTimeLimit:'Definir limite de tempo',
ids_wifi_wep:'WEP',
ids_net_status:'Estado',
ids_usage_minutes:'minutos',
ids_wifi_wpsActive:'O WPS activo.',
ids_menu_usageSetting:'Definições de utilização',
ids_login_otherLogin:'O administrador já iniciou sessão. Volte a tentar mais tarde.',
ids_btn_wan_disconnect:'Desligar',
ids_tr069_inputAcsUserName:'Introduza o nome de utilizador acs antes de o guardar.',
ids_security_ipFilterList:'Lista de filtros IP',
ids_wifi_on:'Ligado',
ids_day:'dia',
ids_net_gsm:'2G',
ids_usage_notAccurate:'As estatísticas podem não ser exatas.',
ids_sim_pukRequired:'PUK necessário',
ids_security_ipOption:'Opção',
ids_net_lte:'4G',
ids_router_subnetEmpty:'Máscara de sub-rede vazia. Introduza-a novamente!',
ids_pdpTimer_5seconds:'5 segundos',
ids_wan_roamingPopWarningMessage:'Clique em <OK> para usar dados em roaming. Verifique com seu provedor de rede para obter preços',
ids_manual:'Manual',
ids_menu_connectDevice:'Dispositivo(s) ligado(s)',
ids_profile_dialNumber:'Número de marcação',
ids_menu_sms:'SMS',
ids_sys_hwVersion:'Versão de hardware',
ids_usage_mothlyDataTips:'Introduza os dados entre 1 e 1024.',
ids_pdpTimer_90seconds:'90 segundos',
ids_title_macFilter:'Filtro MAC',
ids_netMode_Automatic4g3g2g:'Automática(4G & 3G & 2G)',
ids_sys_noFileChosen:'Nenhum ficheiro escolhido',
ids_dlg_sms_mobileNumRule:'Introduza um número válido: 0-9 e \'+\' apenas. Sem espaços ou caracteres especiais.',
ids_wan_connecting:'A ligar...',
ids_profile_inputName:'Introduza o nome do perfil antes de guardá-lo.',
ids_wan_Block:'A lista de endereços Mac está cheia. Não é possível processar esta opção.',
ids_icon_people:'Contactos',
ids_sim_autoValidate:'Validar automaticamente',
ids_menu_language:'Idioma',
ids_wifi_wpsPinRule:'O código PIN do WPS deve ter 4 ou 8 dígitos.',
ids_title_pinCodeSettings:'Definições de código PIN',
ids_net_searching:'A procurar...',
ids_wifi_wpaRule:'A WPA PSK deve ter entre 32 e 127 caracteres ASCII, à excepção de: " : ; & .',
ids_ussd_notSupport:'Não suportado! Tente novamente.',
ids_tr069_acsUrl:'URL ACS',
ids_sms_report:'Relatório SMS',
ids_sim_cck:'CCK',
ids_security:'Segurança',
ids_enable:'Activar',
ids_wifi_wpaAes:'AES',
ids_btn_next:'Seguinte',
ids_profile_profileName:'Nome do perfil',
ids_wifi_wepOpen:'Aberto',
ids_wan_connectIPMode:'Modo de ligação IP',
ids_router_subnetInvalid:'A máscara de sub-rede não é válida. Introduza-a novamente!',
ids_pdpTimer_30seconds:'30 segundos',
ids_usage_min:'min',
ids_wan_connected:'Ligado'
}