var resourceInfo={
ids_fota_upgradingTips:'Schakel het apparaat niet uit tijdens het updaten. Het apparaat zal opnieuw opstarten na de update.',
ids_usage_billingDay:'Dag afrekening',
ids_sms_phoneNumberInvalid:'Telefoonnummer ongeldig',
ids_btn_logout:'Afmelden',
ids_wifi_ssidBroadcast:'SSID Broadcast',
ids_wifi_wpaDescription:'De WPA Pre-Shared Key (PSK) moet bestaan uit 8-63 ASCII tekens of 64 hexadecimale digits.',
ids_dlg_pb_nameRule:'De naam mag de volgende tekens niet bevatten: "\\","\\\'".',
ids_usage_GB:'GB',
ids_UserNameRule32:'De maximum lengte van de gebruikersnaam is 32 tekens, uitgezonderd:  " : ; & .',
ids_pdpTimer_120seconds:'120 seconden',
ids_profile_profileNameRule:'De maximum lengte van de profielnaam is 31 tekens, uitgezonderd:, " : ; \\ & % + < > ?',
ids_security_ipFilterDescription:'Het waardebereik van de poort is 0-65535.',
ids_back:'Terug',
ids_usage_dataUsageReach:'Wanneer data-gebruik de Maand Data-bundel heeft bereikt',
ids_router_startIpInvalid:'Start IP-adres is ongeldig. Voer opnieuw in!',
ids_iptype:'IP-type',
ids_net_selectWarn:'Selecteer een netwerk!',
ids_login_inputCurrPwd:'Huidige wachtwoord is onjuist.',
ids_sim_autoPin:'PIN-code automatisch valideren',
ids_wifi_offTip:'Wi-Fi is uitgeschakeld. Probeer opnieuw nadat Wi-Fi is ingeschakeld.',
ids_net_3g4gOnly:'Alleen 3G / 4G',
ids_wifi_wifiOffTime_30min:'30 minuten',
ids_fota_batteryTips:'Batterij is bijna leeg. Het apparaat kan niet worden geüpdate.',
ids_wifi_wpa:'WPA PSK',
ids_wifi_cipher:'Versleutelingstype',
ids_sim_initializing:'SIM initialiseren.',
ids_success:'Voltooid',
ids_sim_lockCodeRule:'SIM-lock-code moet 10 cijfers zijn.',
ids_sim_pinRequired:'PIN vereist',
ids_router_endIpInvalid:'Eind IP-adres is ongeldig. Voer opnieuw in!',
ids_security_macFilterDescription:'Controleer en beheer de apparatentoegang tot de WLAN. (Verbeter de beveiliging van WLAN).',
ids_net_lteOnlyVal:'Alleen LTE',
ids_security_PowerSavingSmartTips:'Alle LED\'s gaan automatisch uit, behalve de aan/uit-LED, als er 30 seconden geen Wi-Fi-toegang is of geen handmatige bewerking wordt uitgevoerd.',
ids_wan_tips:'Mislukt! Gebruikslimiet is overschreden. U kunt de Maand Data-bundel opnieuw instellen en weer verbinding maken.',
ids_wan_roamingWarningMessage:'Met Data Roaming kunt u op internet surfen, e-mail, MMS en andere gegevensservices gebruiken terwijl u in het buitenland bent. Neem contact op met uw netwerkprovider voor prijzen',
ids_title_preferredDnsServer:'Voorkeur DNS Server',
ids_modify:'Wijzigen',
ids_title_connectMode:'Verbinding-modus',
ids_net_noService:'Geen service',
ids_net_2g3gOnly:'Alleen 2G / 3G',
ids_sms_chatInputConfirm:'Druk op Enter om te voltooien',
ids_sms_mobileNumRule:'De maximum lengte van het mobiele nummer is 20 cijfers, bevattende "+0123456789". Voer opnieuw in.',
ids_dlg_pb_NumberNullWarning:'Het telefoonnummer mag niet leeg zijn.',
ids_usage_hours:'uren',
ids_usage_timePassed:'Tijd verstreken',
ids_wifi_country:'Land',
ids_wifi_wlan_mode:'Wi-Fi modus',
ids_net_umts:'3G',
ids_fail:'Mislukt!',
ids_wifi_wpsPin:'WPS PIN',
ids_wan_inputDeviceName:'Voer apparaatnaam in',
ids_sms_sendFail:'SMS verzenden mislukt',
ids_sim_pukCode:'PUK-code',
ids_sms_newMessageOn:'ongelezen van',
ids_tr069_inputConReqPassword:'Voer het verbindingsverzoek wachtwoord in voordat u deze opslaat.',
ids_sys_swVersion:'Software versie',
ids_sim_simlockError:'SIM-lock-code fout',
ids_security_ipFilterPort:'Het waardebereik van de poort is 0-65535.',
ids_wifi_inputSsid:'Voer de SSID in.',
ids_clearCode_Thirtythree:'Geen servicegegevens',
ids_sim_confirmPinCode:'Bevestig PIN-code',
ids_security_dmzStatus:'DMZ-status',
ids_security_macAddrNameWarn:'Het MAC-adres bestaat al.',
ids_security_portRule:'Het waardebereik van de poort is 1-65535.',
ids_router_startIP:'Start IP-adres',
ids_fotaUpdate_openRoaming_meg:'Er kunnen extra kosten in rekening worden gebracht voor downloaden tijdens roaming. Raadpleeg daarvoor uw serviceprovider. Wilt u doorgaan?',
ids_net_forbid:'Verboden',
ids_btn_loginTimeout:'opnieuw registreren',
ids_security_wanIpAddr:'WAN IP-adres',
ids_profile_userName:'Gebruikersnaam',
ids_profile_password:'Wachtwoord',
ids_btn_restore:'Herstel',
ids_tips_livechat:'Live chat',
ids_login_inputPwd:'Voer het wachtwoord in',
ids_login_inputUserName:'Voer de gebruikersnaam in.',
ids_pdpTimer_20seconds:'20 seconden',
ids_btn_previous:'Vorige',
ids_sys_restoreBackupWarn:'Deze actie zal de instellingen bijwerken. Het apparaat wordt opnieuw opgestart zodra de upload gereed is. Wilt u doorgaan?',
ids_security_ipLanWan:'N.B.: Het waardebereik van de LAN/WAN poort is 0-65535 en 0 betekent elke willekeurige.',
ids_usage_KB:'KB',
ids_login_remenberPassword:'Wachtwoord onthouden',
ids_security_firewallDes:'Deze pagina geeft informatie over hoe de firewall filter-functies kunnen worden geactiveerd. Het IP-adres filter en de WAN-poort ping functies zijn alleen beschikbaar als de firewall is geactiveerd.',
ids_title_wifiSettings:'Wi-Fi Instellingen',
ids_sim_invalidSimCard:'Ongeldige SIM-kaart',
ids_sim_unknown:'Onbekend',
ids_wan_disconnecting:'Verbreken......',
ids_btn_delete:'Wissen',
ids_tr069_client:'TR-069-client – Configuratie',
ids_wifi_channel:'Wi-Fi Kanaal',
ids_title_dnsSetting:'DNS',
ids_pb_name:'Naam',
ids_btn_apply:'Toepassen',
ids_fota_latestVersion:'Deze software is al de laatste versie.',
ids_security_urlAddrInvalid:'URL-adres is ongeldig.',
ids_wan_cannotBlock:'MAC-filter staat nu op Toestaan. Deze optie kan niet uitgevoerd worden.',
ids_deny:'Afwijzen',
ids_sms_saveDraftSuccess:'SMS is opgeslagen als concept',
ids_network_notAvailableFunctionWarn:'Verbreek eerst de data verbinding alvorens Profiel Beheer te starten.',
ids_usage_duration:'Tijdsduur',
ids_sim_rck:'RCK',
ids_sms_deleteWarning:'Wilt u bericht(en) wissen?',
ids_icon_uploaded:'Upload',
ids_orange_sim_pinOperationWarn:'U kunt de PIN-code-instellingen niet bijwerken wanneer u bent verbonden met internet.',
ids_dlg_pb_mobileNumRule:'De maximumlengte van mobiele nummers is 40 cijfers, waaronder "+0123456789". Voer deze opnieuw in.',
ids_title_profilesManagement:'Profiel Beheer',
ids_wifi_wifiOffTime_20min:'20 minuten',
ids_sim_lockForbidden:'SIM-lock is niet toegestaan!',
ids_sim_pinRule:'PIN-code moet 4-8 cijfers zijn.',
ids_security_dmzTips:'Met DMZ kan het geselecteerde apparaat de firewall-functies van de gateway omzeilen en wordt onbeperkte toegang via internet verleend aan dat apparaat.',
ids_router_startSameSubnet:'Start IP-adres en "IP-adres" moeten behoren tot hetzelfde subnet.',
ids_btn_help:'Help',
ids_menu_smsSettings:'SMS Instellingen',
ids_profile_nameWarn:'De profielnaam bestaat al.',
ids_wifi_wifiOffTime_10min:'10 minuten',
ids_sim_newPinRule:'Nieuwe PIN-code moet 4-8 cijfers zijn.',
ids_sim_comfirmPinRule:'PIN-code ter bevestiging moet 4-8 cijfers zijn.',
ids_sim_enterValidCode:'Geef een geldige PIN-code op.',
ids_btn_send:'Zenden',
ids_net_available:'Beschikbaar',
ids_profile_numRule:'Opmerking: Het maximum aantal profielen dan u kunt aanmaken is 15.',
ids_gsm7_text:'GSM 7',
ids_dlg_sms_smsForwardNumEmpty:'Mobiel nummer is leeg. Voer het nummer in.',
ids_wifi_wepDescription:'WEP Key bestaat uit 5 of 13 ASCII tekens, of 10 of 26 hexadecimale digits.',
ids_sd_sdCard:'SD-kaart',
ids_sys_deviceName:'Apparaatnaam',
ids_days:'dagen',
ids_sys_ipAddress:'IP-adres',
ids_login_nameOrPwdWrong:'Gebruikersnaam of wachtwoord is onjuist.',
ids_profile_userNameRule:'De maximum lengte van de gebruikersnaam is 31 tekens, uitgezonderd:  " : ; & .',
ids_wifi_cannotSet:'Wi-Fi is momenteel uitgeschakeld. Deze optie kan nu niet worden verwerkt.',
ids_router_ipAddrEmpty:'IP-adres is leeg. Voer opnieuw in!',
ids_wifi_pinDecription:'WPS PIN (WPS instellen door een speciale 8-cijferige code op te geven):<br/>1. Als er ten minste één client is verbonden met de router, opent u de browser van het verbonden apparaat en gaat u naar http://192.168.0.1/. Geef vervolgens uw wachtwoord op en klik op Meer > WPS. Selecteer WPS PIN.<br/>2. Op het apparaat waarmee u verbinding wilt maken met de router (bijvoorbeeld een pc of smartphone) opent u het Wi-Fi-hulpprogramma dat WPS ondersteunt (bijgeleverd door leverancier van het apparaat). Kies vervolgens WPS PIN-methode. Er wordt een 8-cijferige WPS PIN-code gegenereerd.<br/>3. Ga terug naar de webinterface van de router en geef in het WPS PIN-codeveld de 8-cijferige WPS PIN-code op. Klik vervolgens op Toepassen.<br/>4. De verbinding tussen de router en de client wordt binnen ongeveer 2 minuten automatisch tot stand gebracht.',
ids_tr069_tips:'Selecteer de gewenste waarden en klik op "Toepassen/Opslaan" om de TR-069-client opties te configureren.',
ids_more_onlineUpdate:'On-line Update',
ids_security_btnAdd:'Toevoegen',
ids_sms_autoForward:'SMS doorsturen naar mobiele telefoon',
ids_sim_simLockCode:'SIM-lock-code',
ids_router_restartWarn:'Deze actie vereist dat het apparaat opnieuw wordt opgestart. Wilt u doorgaan?',
ids_sms_saveSimCard:'SIM-kaart',
ids_automatic:'Automatisch',
ids_security_portTips:'Opmerking: Geef de poort en poortgroep op, bijvoorbeeld: 30 of 65500-65510.',
ids_wifi_wpsNotSuppotSSIDHidden:'SSID afgescherm, WPS kan niet worden gebruikt.',
ids_netMode_Automatic3g2g:'Automatisch(3G & 2G)',
ids_wifi_apIsotation:'AP Isolatie',
ids_security_portForwarding:'Poortdoorschakeling',
ids_btn_add:'Toevoegen',
ids_usage_billingTimeTips:'Voer de dag in tussen 1-31.',
ids_minutes:'minuten',
ids_ussd_inputDescription:'Voer de USSD-code in',
ids_fota_upgrading:'Updaten......',
ids_router_dhcpServer:'DHCP-server',
ids_sim_pinRequiredTips:'Voor meer informatie, klik op "PIN vereist" om te ontgrendelen.',
ids_login_checkPwdRule:'Ongeldig wachtwoord! De lengte van het aanmeld wachtwoord is 4-16 tekens, inclusief 0-9, a-z, A-Z,"-+!@$#^&*", voer opnieuw in.',
ids_wifi_wifiOffTime:'Tijd Wi-Fi uit',
ids_sd_sdShareMode:'SD Delen-modus',
ids_btn_continue:'Doorgaan',
ids_profile_protocal:'Protocol',
ids_security_lanPort:'LAN-poort',
ids_dlg_sms_reInputCenterNum:'Het SMS service center nummer is ongeldig. Voer het nummer opnieuw in!',
ids_btn_backup:'Back-up',
ids_wan_connected_num:'Verbonden',
ids_sms_centerNum:'SMS-center',
ids_fota_downloading:'Downloaden...',
ids_wifi_wpaWpa2Psk:'WPA/WPA2 PSK',
ids_usage_of:'van',
ids_sys_rebootDecription:'Klik op deze knop om het apparaat opnieuw op te starten.',
ids_title_about:'Over',
ids_sim_nck:'NCK',
ids_net_operator:'Operator',
ids_router_endIpEmpty:'Eind IP-adres is leeg. Voer opnieuw in!',
ids_btn_cancel:'Annuleren',
ids_dlg_pb_nameNullWarning:'De naam mag niet leeg zijn.',
ids_dlg_sms_inputCenterNum:'Het SMS service center nummer is leeg. Voer het nummer in!',
ids_ussd_rule:'Alleen "*" "#" en cijfers kunnen worden ingevoerd.',
ids_wifi_wifi:'Wi-Fi',
ids_sms_selectSomeOptions:'Maximaal 3 contacten',
ids_btn_new:'Nieuw',
ids_fota_findNewVersion:'Nieuw versie gevonden',
ids_security_pfNumRule:'Opmerking: U kunt maximaal 16 poortdoorschakelingen maken.',
ids_wifi_showPwd:'Wachtwoord tonen',
ids_security_urlFilterList:'URL Filter Lijst',
ids_loginTimeout:'Time-out voor inloggen. Log opnieuw in.',
ids_title_alternateDnsServer:'Alternatieve DNS Server',
ids_login_inputNewPwd:'Voer het nieuwe wachtwoord in.',
ids_fota_updateTitle:'Systeemupdates',
ids_login_inputConfirmPwd:'Voer het wachtwoord ter bevestiging in.',
ids_hours:'uren',
ids_wifi_maxUser:'Max aantal gebruikers',
ids_pb_addNew:'Toevoegen',
ids_usage_timeLimit:'Tijdslimiet',
ids_sim_pinCode:'PIN-code',
ids_wifi_wpaTkip:'TKIP',
ids_sim_autoPinState:'Huidige status',
ids_security_dmzTitle:'DMZ',
ids_security_dmzIpInvalid:'DMZ IP-adres is geen geldig IP-adres.',
ids_btn_unblock:'Deblokkeren',
ids_fota_checkUpdate:'Updaten',
ids_title_advanced:'Geavanceerde Instellingen',
ids_security_ipFilterWarn:'Het IP-filter bestaat al.',
ids_fota_updateDescription:'Klik op "Updaten" om te updaten naar de nieuwe versie.',
ids_btn_reset:'Reset',
ids_tr069_acsUrlRule:'Acs url formaat: bijv.: http://ip-adres:poort/xxx',
ids_show_again:'Dit niet meer weergeven',
ids_usage_hrs:'Uur',
ids_icon_battery:'Batterij',
ids_sms_saveDevice:'Apparaat',
ids_roamAppear:'Veeg om data roaming in the schakelen. Contacteer uw provider voor de kosten.',
ids_sys_chooseFile:'Bestand selecteren',
ids_btn_refresh:'Verversen',
ids_pb_phoneBook:'Telefoonboek',
ids_net_select:'Netwerk-selectie',
ids_sim_pinError:'PIN-code fout',
ids_sms_saveDraftFailed:'Opslaan als concept mislukt',
ids_sms_delivered:'Afgeleverd',
ids_usage_autoDisconnected:'Automatisch verbreken',
ids_login_confirmPwd:'Bevestig wachtwoord',
ids_security_addMacAddress:'MAC-adres toevoegen',
ids_sim_noSimCard:'Geen SIM-kaart',
ids_wifi_notSuppotWepWpa:'WPS is niet beschikbaar bij gebruik van WEP, WPA, WPA2 TKIP!',
ids_security_pfWarn:'De poortdoorschakeling bestaat al.',
ids_fota_checking:'Controleren...',
ids_dlg_pb_lenWarning:'De invoer is te lang',
ids_sim_newPinCode:'Nieuwe PIN-code',
ids_sim_pinNotAvailable:'PIN-code is niet beschikbaar',
ids_usage_clear:'Historie wissen',
ids_wifi_maxSsid:'De maximum lengte van SSID is 32 tekens, inclusief 0-9, a-z, A-Z, "-", "_", "." ," ".',
ids_usage_startTimeTips:'Voer een waarde in tussen 1-43200.',
ids_wifi_pbcConfiguration:'Push Button Configuratie',
ids_usage_dataConsumption:'Data-gebruik',
ids_disable:'Deactiveren',
ids_ucs2Orgsm7_text:'UCS2 Or GSM7',
ids_login_loginPwd:'Aanmeld wachtwoord',
ids_btn_save:'Opslaan',
ids_wifi_802mode:'802.11 Modus',
ids_pb_phoneNumber:'Telefoonnummer',
ids_ussd_timeOut:'Time-out. Probeer het opnieuw.',
ids_btn_reboot:'Herstarten',
ids_minute:'minuut',
ids_router_ipAddrInvalid:'IP-adres is ongeldig. Voer opnieuw in!',
ids_router_startIpEmpty:'Start IP-adres is leeg. Voer opnieuw in!',
ids_sim_pinEnable:'PIN autom. valideren is ingeschakeld.',
ids_sim_pinCodeOperation:'PIN-code functie',
ids_security_dmzInvalidLanSubnet:'DMZ IP-adres bevindt zich niet in het LAN-subnet.',
ids_net_service:'Service',
ids_router_ipRule:'Fout! Let op, 10 IP-adressen na het Thuis-adres zijn gereserveerd voor het systeem. Deze kunnen niet binnen de DHCP IP-pool worden gebruikt.',
ids_usage_roaming:'Roaming',
ids_title_ussd:'USSD',
ids_btn_ok:'OK',
ids_sys_resetDecription:'Fabrieksinstellingen herstellen.',
ids_tr069_inputInformInterval:'Voer de informatie-interval in voordat u deze opslaat.',
ids_security_dmzIpAddr:'DMZ IP-adres',
ids_profile_inputApn:'Voer de APN in!',
ids_sys_restoreFactoryWarn:'Deze actie zal de fabrieksinstellingen herstellen en het apparaat wordt opnieuw opgestart. Wilt u doorgaan?',
ids_net_registing:'Registreren......',
ids_sys_backupDecription:'Download (Back-up) de configuratie.',
ids_sms_selectAnOption:'Selecteer een optie',
ids_tr069_inputAcsUrl:'Voer de acs url in voordat u deze opslaat.',
ids_tr069_acsUsername:'ACS Gebruikersnaam',
ids_pdpTimer_0seconds:'0 seconde',
ids_usage_home:'Thuis',
ids_profile_deleteWarn:'Wilt u dit profiel verwijderen?',
ids_sms_smsFull:'Het SMS postvak is vol. Wis een aantal SMS-en om een nieuwe SMS te kunnen verzenden/opslaan.',
ids_tr069_connRqPw:'Verbindingsverzoek Wachtwoord',
ids_sim_pukError:'PUK-code fout',
ids_sys_system:'Systeem',
ids_security_PowerSavingSmart:'Slim',
ids_login_timeuseout:'Maximum aantal pogingen om aan te melden bereikt. Herstart apparaat en probeer opnieuw.',
ids_usage_minutesTimes:'min.',
ids_sim_pukRule:'PUK-code moet 8 cijfers zijn.',
ids_net_3gOnly:'Alleen 3G',
ids_sim_nsck:'NSCK',
ids_subnetMask:'Subnet-masker',
ids_pdpTimer_60seconds:'60 seconden',
ids_sim_pinDisable:'PIN autom. valideren is uitgeschakeld.',
ids_sys_macAddress:'MAC-adres',
ids_menu_connection:'Verbinding',
ids_dlg_pb_tooManyNumbers:'Selecteer slechts één nummer om te beginnen met bewerken.',
ids_password:'Wachtwoord',
ids_security_virtualServer:'Virtuele server (statische poortdoorschakeling)',
ids_security_ipFilterDes:'Filter-pakketten gebruiken de volgende regels gespecificeerd met protocol, poort en IP-adres.',
ids_ussd_checkBlance:'Saldo controleren',
ids_title_tr069:'TR069',
ids_sms_draft:'Concepten',
ids_wifi_encryption:'Versleuteling',
ids_title_ping:'Ping',
ids_foot_copyright:'Copyright 2016-2018 TCL Communication Ltd. Alle rechten voorbehouden.',
ids_tr069_acsPw:'ACS Wachtwoord',
ids_help_userManual:'Handleiding',
ids_security_pfDescription:'Door poortdoorschakeling kunnen externe computers toegang krijgen tot WWW, FTP of andere services die worden geleverd door het LAN.',
ids_wifi_notSuppotMacFilter:'WPS-procedure (versie 2.0) kan niet worden geactiveerd als MAC-adres filter is ingeschakeld.',
ids_title_blockDevice:'Apparaat blokkeren',
ids_router_endGeaterStart:'Eind IP-adres moet hoger zijn dan "Start IP-adres".',
ids_net_2gOnly:'Alleen 2G',
ids_clearCode_Twentynine:'Verificatie mislukt',
ids_usage_day:'dag',
ids_wifi_wepShare:'WEP-Shared',
ids_sms_messageSending:'Er wordt een SMS verzonden',
ids_wan_roamingPopCloseConntectTips:'Gegevensroaming wordt gedeactiveerd.',
ids_sd_currentFolder:'Huidige Map',
ids_wan_disconnected:'Verbroken',
ids_security_numRule:'<b>Opmerking:</b> U kunt maximaal 16 IP-filters maken.',
ids_dns_manual_mode:'DNS handmatige modus',
ids_login:'Aanmelden',
ids_security_PowerSavingTitle:'Energiebesparing',
ids_security_lanIpAddr:'LAN IP-adres',
ids_menu_settings:'Instellingen',
ids_wifi_disconWarning:'Deze actie zal Wi-Fi verbreken. Wilt u doorgaan?',
ids_wifi_wpsActiveWarn:'WPS-procedure is actief. Probeer het over 2 minuten opnieuw.',
ids_login_loginUserName:'Gebruikersnaam voor inloggen',
ids_wifi_wepWifiCertification:'WEP-sleutel is 5 of 13 of 10 of 26.',
ids_connect:'Verbinden',
ids_btn_block:'Blokkeren',
ids_pb_number:'NR.',
ids_login_wrongPwd:'Onjuist wachtwoord!',
ids_sms_smsForwarding:'SMS doorsturen',
ids_sys_selectFilePrompt:'Selecteer een bestand voor het uploaden.',
ids_wifi_wifiSecurity:'Wi-Fi Beveiliging',
ids_btn_edit:'Wijzigen',
ids_security_firewallSwitch:'Firewall Schakelaar',
ids_router_endIP:'Eind IP-adres',
ids_sys_imei:'IMEI',
ids_sim_remainTime:'Poging(en) over',
ids_update_Confirm:'Het bestand is gedownload. Weet u zeker dat u wilt bijwerken?',
ids_sim_pinConfirmed:'De PIN-code ter bevestiging moet gelijk zijn aan de nieuwe PIN-code.',
ids_filter_urlAddress:'URL Adres',
ids_validate:'Bevestigen',
ids_security_subnetWarn:'LAN IP-adres en \'IP-adres\' moeten bij hetzelfde subnet horen.',
ids_sms_inputNum:'Voer het mobiele nummer in.',
ids_tr069_informInterval:'Informatie-interval (s)',
ids_fota_haveNewVersion:'Een nieuwe software is beschikbaar. Klik om te updaten.',
ids_sim_pukRequiredTips:'Voor meer informatie, klik op "PUK vereist" om te ontgrendelen.',
ids_sms_emptyMessageWarn:'Bericht is leeg. Wilt u dit lege bericht verzenden?',
ids_sim_pck:'PCK',
ids_usage_clearHistory:'Wilt u alle statistieken op nul zetten?',
ids_hour:'uur',
ids_tr069_connRqAuth:'Verbindingsverzoek Authenticatie',
ids_wifi_off:'Uit',
ids_pb_storageStatus:'Opslagstatus',
ids_wan_connectedRule:'Deze instelling kan niet aangepast worden tijdens een actieve verbinding, verbreek de verbinding en probeer het opnieuw.',
ids_menu_usage:'Verbruik',
ids_security_dmzDescription:'Als de PC geen netwerk-applicaties kan gebruiken via de gateway, dient u de DMZ-functie te activeren en het IP-adres van de PC hieronder in te vullen.',
ids_title_networkMode:'Netwerk-modus',
ids_wifi_wifiOffTime_5min:'5 minuten',
ids_wifi_pbc:'PBC',
ids_error:'Fout!',
ids_sim_changePinError:'Fout bij wijzigen PIN-code!',
ids_security_wanPort:'WAN-poort',
ids_security_ipFilter:'IP-filter',
ids_tr069_inputConReqUserName:'Voer de verbindingsverzoek gebruikersnaam in voordat u deze opslaat.',
ids_tr069_informIntervalRule:'Informatie-interval moet liggen tussen 0-2678400, bevattende "0123456789".',
ids_login_newPwd:'Nieuw wachtwoord',
ids_pdpTimer_10seconds:'10 seconden',
ids_security_virtualServerList:'Lijst met virtuele servers',
ids_security_urlAddrNameWarn:'Het URL-adres bestaat al.',
ids_btn_select:'Selecteren',
ids_router_endSameSubnet:'Eind IP-adres en "IP-adres" moeten behoren tot hetzelfde subnet.',
ids_ussd_CodeEmpty:'Invoervak mag niet leeg zijn.',
ids_sim_autoPinError:'Fout bij automatisch valideren PIN-code',
ids_usage_cancelLimitTips:'Stel de datalimiet in op 0 en sla dit op om een datalimiet te annuleren.',
ids_sim_simLocked:'SIM-lock vereist',
ids_icon_timeElapsed:'Tijd verstreken',
ids_sms_sendingPrompt:'Zenden......, even wachten!',
ids_tr069_inputAcsPassword:'Voer het acs wachtwoord in voordat u deze opslaat.',
ids_requestError:'Geen reactie. De verbinding met het apparaat kan zijn verbroken. Start het apparaat opnieuw op en probeer opnieuw.',
ids_profile_inputRule:'APN & Nummer moet bestaan uit ASCII tekens in het bereik van 32-127, uitgezonderd: " : ; & .',
ids_net_active:'Actief',
ids_sms_numberWarning:'De invoer is te lang. Wis een gedeelte.',
ids_data:'Data',
ids_pdpTimer:'PDP-timer',
ids_menu_sharing:'Delen',
ids_sd_noSdCard:'Geen SD-kaart',
ids_wifi_pbcDecription:'1.  Als er geen client is verbonden met de router, houdt u de WPS-knop op de router ingedrukt en wacht u tot het Wi-Fi LED-lampje gaat knipperen. Als er ten minste één client is verbonden met de router, opent u de browser van het verbonden apparaat en gaat u naar http://192.168.0.1/. Geef vervolgens uw wachtwoord op en klik op Meer > WPS. Druk op de WPS-functietoets.<br/>2. Op het apparaat waarmee u verbinding wilt maken met de router (bijvoorbeeld een pc of smartphone), opent u het Wi-Fi-hulpprogramma dat WPS ondersteunt (bijgeleverd door leverancier van het apparaat). Kies vervolgens de PBC-methode of druk, indien beschikbaar, op de PBC-knop (WPS) van het apparaat.<br/>3. De verbinding tussen de router en de client wordt binnen ongeveer 2 minuten automatisch tot stand gebracht.',
ids_sms_deleteSingleWarning:'Wilt u bericht(en) wissen?',
ids_menu_more:'Meer',
ids_net_4gOnly:'Alleen 4G',
ids_profileProtocal_none:'None',
ids_isSupportKickOff:'Een andere gebruiker is al aangemeld, wilt u nog zich steeds aanmelden? De andere gebruiker wordt dan afgemeld.',
ids_changePassword_Tips:'Uw huidige gebruikersnaam en wachtwoord zijn de standaardinstelling. We raden u aan uw wachtwoord te wijzigen in iets dat u kunt onthouden. <a class="userpass_link">&nbsp;Klik hier&nbsp;</a> om de gebruikersnaam en het wachtwoord te wijzigen.',
ids_wifi_wifiSleep:'WiFi Sleep',
ids_security_upnpDescription:'Met UPnP worden netwerken van apparaat naar apparaat mogelijk. Dit is een gedistribueerd, open architectuurprotocol op basis van gevestigde normen zoals de Internet Protocol Suite (TCP/IP), HTTP, XML en SOAP.',
ids_sms_deleteAll:'Alles wissen',
ids_pb_location:'Locatie',
ids_diagnostic:'Diagnostische controle',
ids_security_macAddrInvalid:'MAC-adres is ongeldig.',
ids_security_PowerSavingWiFiTips:'Wi-Fi wordt automatisch uitgeschakeld als de verbinding lange tijd inactief is.',
ids_tr069_connRqUsername:'Verbindingsverzoek Gebruikersnaam',
ids_security_PowerSavingWiFi:'Wi-Fi',
ids_profile_pwdRule:'De maximum lengte van het wachtwoord is 31 tekens, uitgezonderd: " : ; &',
ids_tr069_inform:'Informeren',
ids_locked_permanently:'Dit apparaat is permanent vergrendeld en kan niet worden ontgrendeld.',
ids_sys_setRebootEvent:'Het apparaat wordt opnieuw opgestart.Wacht 60 seconden.Maak dan opnieuw verbinding met het Wi-Fi apparaat.',
ids_sms_saveMode:'Opslag-modus',
ids_pb_add:'Toevoegen',
ids_sim_spck:'SPCK',
ids_security_upnp:'UPnP',
ids_sms_encodingoptimization:'SMS-coderingsoptimalisatie',
ids_profile_inputDialNum:'Voer het nummer in!',
ids_dlg_pb_deleteWarning:'Weet u zeker dat u wilt verwijderen?',
ids_security_enableIp:'IP-adres filter activeren',
ids_sms_mobileNum:'Mobiel telefoonnummer',
ids_security_urlFilterTitle:'URL-filter',
ids_btn_setDefault:'Als&nbsp;Standaard',
ids_wan_connectedRuleIndia:'Verbreek de dataverbinding voordat u begint met Profielbeheer.',
ids_title_loginSettings:'Aanmeld Instellingen',
ids_profile_apn:'APN',
ids_pb_local:'Lokaal',
ids_wan_roamingAutoConnect:'Automatisch verbinding maken ook tijdens roaming',
ids_wifi_key:'Sleutel',
ids_login_userName:'beheerder',
ids_wifi_offRule:'Wi-Fi is momenteel uitgeschakeld, omdat lange tijd geen client verbonden was. Schakel Wi-Fi handmatig in door een toets op het apparaat in te drukken, als u Wi-Fi wilt gebruiken.',
ids_allow:'Toestaan',
ids_usage_MB:'MB',
ids_sim_simLockedTips:'Voor meer informatie, klik op "SIM-lock vereist" om te ontgrendelen.',
ids_login_inputOldPwd:'Voer het oude wachtwoord in.',
ids_icon_downloaded:'Download',
ids_sys_rebootWarn:'Wilt u het apparaat opnieuw opstarten?',
ids_security_enableFirewall:'Firewall activeren',
ids_security_pfRangePortTip:'LAN-poortnummer is niet gelijk aan WAN-poortnummer.',
ids_wifi_wepRule:'WEP Key moet bestaan uit ASCII tekens in het bereik van 32-127, uitgezonderd: " : ; & .',
ids_sd_viewFile:'Bestand bekijken',
ids_icon_debit:'Gebruikt',
ids_wifi_wpa2:'WPA2 PSK',
ids_sim_pinManagement:'PIN-code Beheer',
ids_security_upnpStatus:'UPnP-status',
ids_HelplineNumber:'Nummer van hulplijn:',
ids_login_confirmPwdRule:'Het nieuwe wachtwoord en het wachtwoord ter bevestiging moeten gelijk zijn.',
ids_router_leaseTime:'DHCP IP Lease-tijd',
ids_sd_usedTotal:'(Gebruikt/Totaal)',
ids_usage_monthlyDataPlan:'Maand Data-bundel',
ids_title_wps:'WPS',
ids_sms_newMessage:'Nieuw bericht',
ids_auto:'AUTO',
ids_usage_setTimeLimit:'Tijdslimiet instellen',
ids_wifi_wep:'WEP',
ids_net_status:'Status',
ids_usage_minutes:'minuten',
ids_wifi_wpsActive:'WPS is geactiveerd.',
ids_menu_usageSetting:'Verbruik Instellingen',
ids_login_otherLogin:'De administrator is reeds aangemeld. Probeer het later.',
ids_btn_wan_disconnect:'Verbreken',
ids_tr069_inputAcsUserName:'Voer de acs gebruikersnaam in voordat u deze opslaat.',
ids_security_ipFilterList:'IP Filter Lijst',
ids_wifi_on:'Aan',
ids_day:'dag',
ids_net_gsm:'2G',
ids_usage_notAccurate:'Statistieken zijn mogelijk niet correct.',
ids_sim_pukRequired:'PUK vereist',
ids_security_ipOption:'Opties',
ids_net_lte:'4G',
ids_router_subnetEmpty:'Subnet-masker is leeg. Voer opnieuw in!',
ids_pdpTimer_5seconds:'5 seconden',
ids_wan_roamingPopWarningMessage:'Klik op <OK> om gegevens te gebruiken tijdens roamen. Neem contact op met uw netwerkprovider voor prijzen',
ids_manual:'Handmatig',
ids_menu_connectDevice:'Verbonden Apparaten',
ids_profile_dialNumber:'Nummer',
ids_menu_sms:'SMS',
ids_sys_hwVersion:'Hardware versie',
ids_usage_mothlyDataTips:'Voer een waarde in tussen 1-1024.',
ids_pdpTimer_90seconds:'90 seconden',
ids_title_macFilter:'MAC-filter',
ids_netMode_Automatic4g3g2g:'Automatisch(4G & 3G & 2G)',
ids_sys_noFileChosen:'Geen bestand geselecteerd',
ids_dlg_sms_mobileNumRule:'Geef een geldig nummer op: Alleen 0-9 en \'+\', geen spaties of speciale tekens.',
ids_wan_connecting:'Verbinden......',
ids_profile_inputName:'Voer de profielnaam in, voordat u het profiel opslaat.',
ids_wan_Block:'De lijst met MAC-adressen is vol. Deze optie kan niet uitgevoerd worden.',
ids_icon_people:'Contacten',
ids_sim_autoValidate:'Automatisch valideren',
ids_menu_language:'Taal',
ids_wifi_wpsPinRule:'WPS PIN-code moet 4-8 cijfers zijn.',
ids_title_pinCodeSettings:'PIN-code Instellingen',
ids_net_searching:'Zoeken......',
ids_wifi_wpaRule:'WPA PSK moet bestaan uit ASCII tekens in het bereik van 32-127, uitgezonderd: " : ; & .',
ids_ussd_notSupport:'Niet ondersteund. Probeer het opnieuw.',
ids_tr069_acsUrl:'ACS URL',
ids_sms_report:'SMS Afleverrapport',
ids_sim_cck:'CCK',
ids_security:'Beveiliging',
ids_enable:'Activeren',
ids_wifi_wpaAes:'AES',
ids_btn_next:'Verder',
ids_profile_profileName:'Profielnaam',
ids_wifi_wepOpen:'WEP-OPEN',
ids_wan_connectIPMode:'Verbindings-IP-modus',
ids_router_subnetInvalid:'Subnet-masker is ongeldig. Voer opnieuw in!',
ids_pdpTimer_30seconds:'30 seconden',
ids_usage_min:'Min',
ids_wan_connected:'Verbonden'
}