var resourceInfo={
ids_fota_upgradingTips:'No apague el dispositivo durante la actualización. El dispositivo se reiniciará después de la actualización.',
ids_usage_billingDay:'Día de facturación',
ids_sms_phoneNumberInvalid:'El número de teléfono no es válido',
ids_btn_logout:'Cerrar',
ids_wifi_ssidBroadcast:'Difusión SSID',
ids_wifi_wpaDescription:'La clave precompartida (PSK) del WPA debe contener entre 8 y 63 caracteres ASCII o 64 dígitos hexadecimales.',
ids_dlg_pb_nameRule:'El nombre no puede incluir los siguientes caracteres: "\\","\\\'".',
ids_usage_GB:'GB',
ids_UserNameRule32:'El número máximo de caracteres para el nombre de usuario es 32, sin incluir: " : ; & .',
ids_pdpTimer_120seconds:'120 segundos',
ids_profile_profileNameRule:'El número máximo de caracteres para el nombre del perfil es 31, sin incluir: , " : ; \\ & % + < > ?.',
ids_security_ipFilterDescription:'El rango del valor del puerto es 0-65535.',
ids_back:'Atrás',
ids_usage_dataUsageReach:'Cuando el uso de datos alcanza al plan de datos mensual',
ids_router_startIpInvalid:'¡La dirección IP inicial no es válida. Vuelva a introducirla!',
ids_iptype:'Tipo de IP',
ids_net_selectWarn:'Seleccione una red.',
ids_login_inputCurrPwd:'La contraseña actual es incorrecta.',
ids_sim_autoPin:'Validación automática del código PIN',
ids_wifi_offTip:'WiFi esta deshabilitado. Por favor, inténtelo de nuevo tras haber habilitado WiFi.',
ids_net_3g4gOnly:'Solo 3G / 4G',
ids_wifi_wifiOffTime_30min:'30 minutos',
ids_fota_batteryTips:'Batería baja, el dispositivo no puede actualizarse',
ids_wifi_wpa:'PSK del WPA',
ids_wifi_cipher:'Tipo de cifrado',
ids_sim_initializing:'La SIM se está inicializando.',
ids_success:'Correcto',
ids_sim_lockCodeRule:'El código SIMLOCK debe tener 10 dígitos.',
ids_sim_pinRequired:'Se requiere PIN',
ids_router_endIpInvalid:'¡La dirección IP final no es válida. Vuelva a introducirla!',
ids_security_macFilterDescription:'Control y administración del dispositivo que accede a la WLAN (mejora de la seguridad de la WLAN).',
ids_net_lteOnlyVal:'Solo LTE',
ids_security_PowerSavingSmartTips:'Todos los ledes se apagan automáticamente excepto el led de encendido cuando no hay acceso Wi-Fi o el funcionamiento es manual durante 30 segundos.',
ids_wan_tips:'¡Falló ! Desbordamiento en el histórico de uso, usted puede reiniciar el Plan Mensual de Datos y luego reconectarse.',
ids_wan_roamingWarningMessage:'El roaming de datos le permite navegar por la web, usar el correo electrónico, MMS y otros servicios de datos mientras está en el extranjero. Verifique con su proveedor de red los precios',
ids_title_preferredDnsServer:'Servidor DNS preferido',
ids_modify:'Modificar',
ids_title_connectMode:'Modo de conexión',
ids_net_noService:'Sin servicio',
ids_net_2g3gOnly:'Solo 2G / 3G',
ids_sms_chatInputConfirm:'Por favor, pulse Intro para completar',
ids_sms_mobileNumRule:'El número máximo de caracteres para el número de móvil es 20 dígitos, incluido "+0123456789", vuelva a introducirlo.',
ids_dlg_pb_NumberNullWarning:'El número de teléfono no puede estar vacío.',
ids_usage_hours:'horas',
ids_usage_timePassed:'Tiempo superado',
ids_wifi_country:'País',
ids_wifi_wlan_mode:'Modo Wlan',
ids_net_umts:'3G',
ids_fail:'¡Error!',
ids_wifi_wpsPin:'PIN WPS',
ids_wan_inputDeviceName:'Introduzca un nombre de dispositivo',
ids_sms_sendFail:'Error al enviar el SMS',
ids_sim_pukCode:'Código PUK',
ids_sms_newMessageOn:'sin leer de',
ids_tr069_inputConReqPassword:'Por favor, introduzca la contraseña de la petición de conexión antes de guardar.',
ids_sys_swVersion:'Versión de software',
ids_sim_simlockError:'¡Error de bloqueo de la SIM!',
ids_security_ipFilterPort:'El rango del valor del puerto es 0-65535.',
ids_wifi_inputSsid:'Introduzca el SSID.',
ids_clearCode_Thirtythree:'SIN SUBSCRIPCION AL SERVICIO',
ids_sim_confirmPinCode:'Código PIN confirmado',
ids_security_dmzStatus:'Estatus DMZ',
ids_security_macAddrNameWarn:'La dirección MAC ya existe.',
ids_security_portRule:'El rango del valor del puerto es 1-65535.',
ids_router_startIP:'Dirección IP inicial',
ids_fotaUpdate_openRoaming_meg:'Pueden aplicarse cargos adicionales por realizar descargas mientras está en roaming, consulte con su operador. ¿Desea continuar?',
ids_net_forbid:'Prohibido',
ids_btn_loginTimeout:'registrarse de nuevo',
ids_security_wanIpAddr:'Dirección IP WAN',
ids_profile_userName:'Nombre de usuario',
ids_profile_password:'Contraseña',
ids_btn_restore:'Restablecer',
ids_tips_livechat:'Chat en directo',
ids_login_inputPwd:'Introduzca el contraseña.',
ids_login_inputUserName:'Introduzca el nombre de usuario',
ids_pdpTimer_20seconds:'20 segundos',
ids_btn_previous:'Anterior',
ids_sys_restoreBackupWarn:'Esta acción actualizará la configuración y reiniciará el dispositivo una vez que haya finalizado la descarga. ¿Aún desea continuar?',
ids_security_ipLanWan:'Nota: el rango de valores de puertos LAN/WAN es de 0-65535, 0 significa cualquier rango.',
ids_usage_KB:'KB',
ids_login_remenberPassword:'Recordar contraseña',
ids_security_firewallDes:'Esta página muestra información acerca de cómo habilitar las funciones de filtro del cortafuegos. Las funciones de filtro de dirección IP solo están disponibles cuando el cortafuegos está habilitado.',
ids_title_wifiSettings:'Ajustes de Wi-Fi',
ids_sim_invalidSimCard:'Tarjeta SIM no válida',
ids_sim_unknown:'Desconocido',
ids_wan_disconnecting:'Desconectando......',
ids_btn_delete:'Eliminar',
ids_tr069_client:'Configuración del cliente TR-069',
ids_wifi_channel:'Canal Wi-Fi',
ids_title_dnsSetting:'DNS',
ids_pb_name:'Nombre',
ids_btn_apply:'Aplicar',
ids_fota_latestVersion:'Esta ya es la última versión.',
ids_security_urlAddrInvalid:'La dirección URL no es válida.',
ids_wan_cannotBlock:'El filtrado por MAC está habilitado ahora, no se puede procesar esta opción.',
ids_deny:'Denegar',
ids_sms_saveDraftSuccess:'El SMS se ha guardado como borrador',
ids_network_notAvailableFunctionWarn:'Por favor, deshabilite la conexión antes de iniciar la gestión de perfiles.',
ids_usage_duration:'Duración',
ids_sim_rck:'RCK',
ids_sms_deleteWarning:'¿Desea eliminarla?',
ids_icon_uploaded:'Cargadas',
ids_orange_sim_pinOperationWarn:'Mientras esté conectado a internet no puede cambiar los ajustes de PIN.',
ids_dlg_pb_mobileNumRule:'El número máximo de caracteres para el número de móvil es 40 dígitos, incluido "+0123456789"; vuelva a introducirlo.',
ids_title_profilesManagement:'Administración del perfil',
ids_wifi_wifiOffTime_20min:'20 minutos',
ids_sim_lockForbidden:'¡SIMLOCK prohibido!',
ids_sim_pinRule:'El código PIN debe contener entre 4 y 8 dígitos.',
ids_security_dmzTips:'DMZ permite al dispositivo seleccionado omitir las funciones de firewall de la puerta de enlace y otorga acceso sin restricciones de Internet a ese dispositivo.',
ids_router_startSameSubnet:'La "dirección IP inicial" y la "dirección IP" deben pertenecer a la misma subred.',
ids_btn_help:'Ayuda',
ids_menu_smsSettings:'Configuración de SMS',
ids_profile_nameWarn:'El nombre del perfil ya existe.',
ids_wifi_wifiOffTime_10min:'10 minutos',
ids_sim_newPinRule:'El nuevo código PIN debe contener entre 4 y 8 dígitos.',
ids_sim_comfirmPinRule:'El código PIN confirmado debe contener entre 4 y 8 dígitos.',
ids_sim_enterValidCode:'Por favor introduzca un código PIN válido.',
ids_btn_send:'Enviar',
ids_net_available:'Disponible',
ids_profile_numRule:'Nota: El número máximo del perfil que puede crear es 15.',
ids_gsm7_text:'GSM 7',
ids_dlg_sms_smsForwardNumEmpty:'El número de móvil está vacío. Introduzca el número.',
ids_wifi_wepDescription:'La clave WEP tiene 5 o 13 caracteres ASCII, o bien 10 o 26 caracteres hexadecimales.',
ids_sd_sdCard:'Tarjeta SD',
ids_sys_deviceName:'Nombre del dispositivo',
ids_days:'días',
ids_sys_ipAddress:'Dirección IP',
ids_login_nameOrPwdWrong:'El nombre de usuario o la contraseña son incorrectos',
ids_profile_userNameRule:'El número máximo de caracteres para el nombre de usuario es 31, sin incluir: " : ; & .',
ids_wifi_cannotSet:'Wi-Fi está deshabilitado, no se puede procesar esta opción.',
ids_router_ipAddrEmpty:'¡La dirección IP está vacía. Vuelva a introducirla !',
ids_wifi_pinDecription:'PIN WPS (configure el WPS introduciendo el código especial de 8 dígitos):</br>1. Si al menos un cliente está conectado al router, abra el navegador en el dispositivo conectado y vaya a http://192.168.0.1/, introduzca la contraseña y haga clic en Más > WPS. Seleccione PIN WPS.</br>2. En el dispositivo que desea conectar al router (p. ej. PC o smartphone), abra la configuración del Wi-Fi compatible con WPS (el proveedor de este dispositivo deberá proporcionarla) y seleccione el modo PIN WPS. Se generará el PIN WPS de 8 dígitos.</br>3. Vuelva a la interfaz web del router, introduzca el PIN WPS de 8 dígitos en el campo PIN WPS y haga clic en Aplicar.</br>4. La conexión entre el router y el cliente se establecerá automáticamente en unos 2 minutos.',
ids_tr069_tips:'Seleccione los valores deseados y haga clic en “Aplicar/Guardar” para configurar las opciones del cliente TR-069.',
ids_more_onlineUpdate:'Actualización online',
ids_security_btnAdd:'Añadir',
ids_sms_autoForward:'Reenvío de SMS al teléfono móvil',
ids_sim_simLockCode:'Código de bloqueo de la SIM',
ids_router_restartWarn:'Esta acción requiere que se reinicie el dispositivo. ¿Aún desea continuar?',
ids_sms_saveSimCard:'Tarjeta SIM',
ids_automatic:'Automático',
ids_security_portTips:'Nota: especifique el puerto y el grupo del puerto; por ejemplo: 30 o 65500-65510.',
ids_wifi_wpsNotSuppotSSIDHidden:'SSID oculto, imposible configurar WPS.',
ids_netMode_Automatic3g2g:'(3G & 2G)Automático',
ids_wifi_apIsotation:'Aislamiento AP',
ids_security_portForwarding:'Reenvío de puerto',
ids_btn_add:'Añadir',
ids_usage_billingTimeTips:'Introduzca el día entre 1 y 31.',
ids_minutes:'minutos',
ids_ussd_inputDescription:'Por favor código USSD entrada',
ids_fota_upgrading:'Actualizando...',
ids_router_dhcpServer:'Servidor DHCP',
ids_sim_pinRequiredTips:'Para obtener más información, haga clic en "Se requiere PIN" para desbloquear desde el principio.',
ids_login_checkPwdRule:'Contraseña no válida. La longitud de la contraseña de inicio de sesión es de 4 a 16 caracteres, incluidos 0-9, a-z, A-Z,"-+!@$#^&*", vuelva a introducirla.',
ids_wifi_wifiOffTime:'Desactivación del Wi-Fi',
ids_sd_sdShareMode:'Modo Compartir SD',
ids_btn_continue:'Continuar',
ids_profile_protocal:'Protocolo',
ids_security_lanPort:'Puerto LAN',
ids_dlg_sms_reInputCenterNum:'¡El número del centro de SMS no es válido. Vuelva a introducirlo!',
ids_btn_backup:'Copia de seguridad',
ids_wan_connected_num:'Conectado(s)',
ids_sms_centerNum:'Centro de SMS',
ids_fota_downloading:'Descargando…',
ids_wifi_wpaWpa2Psk:'WPA/WPA2 PSK',
ids_usage_of:'de',
ids_sys_rebootDecription:'Haga clic en este botón para reiniciar el dispositivo.',
ids_title_about:'Acerca de',
ids_sim_nck:'NCK',
ids_net_operator:'Operador',
ids_router_endIpEmpty:'¡La dirección IP final está vacía. Vuelva a introducirla!',
ids_btn_cancel:'Cancelar',
ids_dlg_pb_nameNullWarning:'El nombre no puede estar vacío.',
ids_dlg_sms_inputCenterNum:'¡El número del centro de SMS está vacío. Introduzca el número!',
ids_ussd_rule:'Solo se pueden introducir “*”, “#”y números.',
ids_wifi_wifi:'Wi-Fi',
ids_sms_selectSomeOptions:'3 contactos como máximo',
ids_btn_new:'Nuevo',
ids_fota_findNewVersion:'Buscar nueva versión',
ids_security_pfNumRule:'Nota: el número máximo del reenvío de puertos que puede crear es 16.',
ids_wifi_showPwd:'Mostrar contraseña',
ids_security_urlFilterList:'Lista de filtrado de URL',
ids_loginTimeout:'Tiempo de inicio de sesión agotado; debe volver a iniciar sesión.',
ids_title_alternateDnsServer:'Servidor DNS alternativo',
ids_login_inputNewPwd:'Introduzca la nueva contraseña.',
ids_fota_updateTitle:'Actualizaciones del sistema',
ids_login_inputConfirmPwd:'Voer het wachtwoord ter bevestiging in.',
ids_hours:'horas',
ids_wifi_maxUser:'Número máximo de usuarios',
ids_pb_addNew:'Añadir',
ids_usage_timeLimit:'Límite de tiempo',
ids_sim_pinCode:'Código PIN',
ids_wifi_wpaTkip:'TKIP',
ids_sim_autoPinState:'Estatus actual',
ids_security_dmzTitle:'DMZ',
ids_security_dmzIpInvalid:'La direccion IP DMZ no es una IP valida.',
ids_btn_unblock:'Desbloquear',
ids_fota_checkUpdate:'Actualizar',
ids_title_advanced:'Configuración avanzada',
ids_security_ipFilterWarn:'El filtro IP ya existe.',
ids_fota_updateDescription:'Haga clic en "Actualizar" para actualizar a la nueva versión.',
ids_btn_reset:'Restablecer',
ids_tr069_acsUrlRule:'Formato de URL ACS: ej.http://direccionip:puerto/xxx',
ids_show_again:'No volver a mostrar.',
ids_usage_hrs:'Hrs',
ids_icon_battery:'Batería',
ids_sms_saveDevice:'Dispositivo',
ids_roamAppear:'Deslice para utilizar los datos en roaming. Consulte su proveedor de red para conocer el precio.',
ids_sys_chooseFile:'Seleccione el archivo',
ids_btn_refresh:'Actualizar',
ids_pb_phoneBook:'Agenda',
ids_net_select:'Selección de red',
ids_sim_pinError:'¡PIN incorrecto!',
ids_sms_saveDraftFailed:'Error al guardar borrador',
ids_sms_delivered:'Entregado',
ids_usage_autoDisconnected:'Desconectado automáticamente',
ids_login_confirmPwd:'Confirme la contraseña',
ids_security_addMacAddress:'Añadir dirección MAC',
ids_sim_noSimCard:'No hay tarjeta SIM',
ids_wifi_notSuppotWepWpa:'WPS no disponible con WEP, WPA, WPA2 TKIP',
ids_security_pfWarn:'El reenvío de puertos ya existe.',
ids_fota_checking:'Comprobando…',
ids_dlg_pb_lenWarning:'El texto introducido es demasiado largo.',
ids_sim_newPinCode:'Código PIN nuevo',
ids_sim_pinNotAvailable:'El código PIN no está disponible.',
ids_usage_clear:'Borrar historial',
ids_wifi_maxSsid:'El número máximo de caracteres para el SSID es 32, incluidos 0-9, a-z, A-Z, "-", "_", "." ," ".',
ids_usage_startTimeTips:'Introduzca la fecha entre 1 y 43200.',
ids_wifi_pbcConfiguration:'configuración del pulsador',
ids_usage_dataConsumption:'Consumo de datos',
ids_disable:'Deshabilitar',
ids_ucs2Orgsm7_text:'UCS2 Or GSM7',
ids_login_loginPwd:'Contraseña de inicio de sesión',
ids_btn_save:'Guardar',
ids_wifi_802mode:'Modo 802.11',
ids_pb_phoneNumber:'Número Claro',
ids_ussd_timeOut:'Tiempo de espera agotado. Por favor, inténtelo de nuevo.',
ids_btn_reboot:'Reiniciar',
ids_minute:'minuto',
ids_router_ipAddrInvalid:'¡La dirección IP no es válida. Vuelva a introducirla !',
ids_router_startIpEmpty:'¡La dirección IP inicial está vacía. Vuelva a introducirla!',
ids_sim_pinEnable:'La validación automática del PIN está activada.',
ids_sim_pinCodeOperation:'Funciones del código PIN',
ids_security_dmzInvalidLanSubnet:'La direccion IP DMZ no esta en la subnet LAN.',
ids_net_service:'Servicio',
ids_router_ipRule:'Error. Tenga en cuenta que 10 después de la dirección principal es una IP reservada previamente por el sistema, y no puede incluirse en el grupo de IP de DHCP.',
ids_usage_roaming:'Roaming',
ids_title_ussd:'USSD',
ids_btn_ok:'Aceptar',
ids_sys_resetDecription:'Restablecer la configuración predeterminada de fábrica.',
ids_tr069_inputInformInterval:'Por favor, introduzca el intervalo de información antes de guardar.',
ids_security_dmzIpAddr:'Dirección IP DMZ',
ids_profile_inputApn:'¡Introduzca el APN!',
ids_sys_restoreFactoryWarn:'Esta acción restablece la configuración predeterminada de fábrica y reinicia el dispositivo. ¿Aún desea continuar?',
ids_net_registing:'Registrando......',
ids_sys_backupDecription:'Descargar (hacer una copia de seguridad) la configuración.',
ids_sms_selectAnOption:'Seleccione una opción',
ids_tr069_inputAcsUrl:'Por favor, introduzca la dirección URL del ACS antes de guardar.',
ids_tr069_acsUsername:'Nombre de usuario ACS',
ids_pdpTimer_0seconds:'0 segundos',
ids_usage_home:'Personal',
ids_profile_deleteWarn:'¿Está seguro de que quiere eliminar?',
ids_sms_smsFull:'El buzón de SMS está lleno, elimine algunos SMS para poder enviar/guardar SMS nuevos.',
ids_tr069_connRqPw:'Contraseña de solicitud de conexión',
ids_sim_pukError:'¡PUK incorrecto!',
ids_sys_system:'Sistema',
ids_security_PowerSavingSmart:'Predictivo',
ids_login_timeuseout:'Ha superado el número de intentos de registro. Por favor, reinicie y vuelva a intentarlo.',
ids_usage_minutesTimes:'Min(s)',
ids_sim_pukRule:'El código PUK debe contener 8 dígitos.',
ids_net_3gOnly:'Solo 3G',
ids_sim_nsck:'NSCK',
ids_subnetMask:'Máscara de subred',
ids_pdpTimer_60seconds:'60 segundos',
ids_sim_pinDisable:'La validación automática del PIN está desactivada.',
ids_sys_macAddress:'Dirección MAC',
ids_menu_connection:'Conexión',
ids_dlg_pb_tooManyNumbers:'Para empezar a editar, seleccione solo un número.',
ids_password:'Contraseña',
ids_security_virtualServer:'Servidor virtual (reenvío de puerto estático)',
ids_security_ipFilterDes:'Los paquetes de filtro utilizando las siguientes reglas con protocolo especificado, puerto y dirección IP.',
ids_ussd_checkBlance:'Comprobar el saldo',
ids_title_tr069:'TR069',
ids_sms_draft:'Borradores',
ids_wifi_encryption:'Codificación',
ids_title_ping:'Ping',
ids_foot_copyright:'Copyright 2016-2018 TCL Communication Ltd. Todos los derechos reservados.',
ids_tr069_acsPw:'Contraseña de ACS',
ids_help_userManual:'Manual de usuario',
ids_security_pfDescription:'El reenvío de puertos permite a ordenadores externos acceder a WWW, al FTP o a otros servicios proporcionados por la LAN.',
ids_wifi_notSuppotMacFilter:'WPS (Versión 2.0) no puede ser activado si el filtrado por dirección Mac está habilitado.',
ids_title_blockDevice:'Bloquear dispositivo',
ids_router_endGeaterStart:'La "dirección IP final" debe ser mayor que la "dirección IP inicial".',
ids_net_2gOnly:'Solo 2G',
ids_clearCode_Twentynine:'FALLA DE AUTENTICACION',
ids_usage_day:'día',
ids_wifi_wepShare:'WEP-Shared',
ids_sms_messageSending:'Envío de un SMS en curso',
ids_wan_roamingPopCloseConntectTips:'Los datos en roaming se deshabilitarán.',
ids_sd_currentFolder:'Carpeta actual',
ids_wan_disconnected:'Desconectada',
ids_security_numRule:'<b>Nota:</b>El número máximo del filtro IP que puede crear es 16.',
ids_dns_manual_mode:'Modo Manual DNS',
ids_login:'Iniciar',
ids_security_PowerSavingTitle:'Ahorro de energía',
ids_security_lanIpAddr:'Dirección IP LAN',
ids_menu_settings:'Configuración',
ids_wifi_disconWarning:'Esta acción desconectará el Wi-Fi. ¿Aún desea continuar?',
ids_wifi_wpsActiveWarn:'Se está ejecutando el procedimiento WPS.Espere 2 minutos y vuelva a intentarlo.',
ids_login_loginUserName:'Nombre de usuario de inicio de sesión',
ids_wifi_wepWifiCertification:'La clave WEP tiene 5, 13, 10 o 26 caracteres.',
ids_connect:'Conectar',
ids_btn_block:'Bloquear',
ids_pb_number:'NO.',
ids_login_wrongPwd:'Contraseña incorrecta',
ids_sms_smsForwarding:'Reenvío de SMS',
ids_sys_selectFilePrompt:'Seleccione un archivo antes de iniciar la carga.',
ids_wifi_wifiSecurity:'Seguridad de Wi-Fi',
ids_btn_edit:'Editar',
ids_security_firewallSwitch:'Firewall conmutador',
ids_router_endIP:'Dirección IP final',
ids_sys_imei:'IMEI',
ids_sim_remainTime:'Intento(s) restante(s)',
ids_update_Confirm:'El archivo ha sido descargado. ¿Seguro que quiere actualizar?',
ids_sim_pinConfirmed:'El código PIN confirmado debe ser el mismo que el nuevo código PIN.',
ids_filter_urlAddress:'Dirección URL',
ids_validate:'Validar',
ids_security_subnetWarn:'La dirección IP LAN y la "dirección IP" deben pertenecer a la misma subred.',
ids_sms_inputNum:'Introduzca un número de móvil.',
ids_tr069_informInterval:'Informar del intervalo',
ids_fota_haveNewVersion:'Hay un nuevo software disponible; haga clic para actualizar.',
ids_sim_pukRequiredTips:'Para obtener más información, haga clic en "Se requiere PUK" para desbloquear desde el principio.',
ids_sms_emptyMessageWarn:'El mensaje está vacío. ¿Seguro que desea enviar este mensaje vacío?',
ids_sim_pck:'PCK',
ids_usage_clearHistory:'¿Seguro que quiere reiniciar todas las estadísticas?',
ids_hour:'hora',
ids_tr069_connRqAuth:'Autenticación de solicitud de conexión',
ids_wifi_off:'Desactivado',
ids_pb_storageStatus:'Estado de almacenamiento',
ids_wan_connectedRule:'Este ajuste no puede usarse en el modo conectado. Haga clic en "Desconectar" y vuelva a intentarlo.',
ids_menu_usage:'Uso',
ids_security_dmzDescription:'Si un PC no puede ejecutar aplicaciones de red a través de la puerta de enlace, active la función DMZ e introduzca la dirección IP del PC a continuación.',
ids_title_networkMode:'Modo de red',
ids_wifi_wifiOffTime_5min:'5 minutos',
ids_wifi_pbc:'CP',
ids_error:'¡Error!',
ids_sim_changePinError:'¡Error al cambiar el PIN!',
ids_security_wanPort:'Puerto WAN',
ids_security_ipFilter:'Filtro de IP',
ids_tr069_inputConReqUserName:'Por favor, introduzca el nombre de usuario de la petición de conexión antes de guardar.',
ids_tr069_informIntervalRule:'El intervalo de información debe estar entre 0 y 2678400.',
ids_login_newPwd:'Contraseña nueva',
ids_pdpTimer_10seconds:'10 segundos',
ids_security_virtualServerList:'Lista de servidor virtual',
ids_security_urlAddrNameWarn:'La dirección URL ya existe.',
ids_btn_select:'Seleccionar',
ids_router_endSameSubnet:'La "dirección IP final" y la "dirección IP" deben pertenecer a la misma subred.',
ids_ussd_CodeEmpty:'El campo de entrada no puede estar vacío!',
ids_sim_autoPinError:'¡Error de verificación automática del PIN!',
ids_usage_cancelLimitTips:'Configure el límite de uso d datos a 0 y guarde para cancelar cualquier límite de uso.',
ids_sim_simLocked:'Se requiere bloqueo de la SIM',
ids_icon_timeElapsed:'Tiempo transcurrido',
ids_sms_sendingPrompt:'Enviando, espere.',
ids_tr069_inputAcsPassword:'Por favor, introduzca la contraseña del ACS antes de guardar.',
ids_requestError:'No hay respuesta; puede que se haya desconectado el dispositivo. Reinicie el dispositivo y vuelva a intentarlo.',
ids_profile_inputRule:'La APN & Número de marcación debe estar formada por caracteres ASCII entre 32 y 127, sin incluir: " : ; & .',
ids_net_active:'Activo',
ids_sms_numberWarning:'El texto introducido es demasiado largo. Borre alguna parte.',
ids_data:'Datos',
ids_pdpTimer:'Temporizador PDP',
ids_menu_sharing:'Compartir',
ids_sd_noSdCard:'Sin tarjeta SD',
ids_wifi_pbcDecription:'1. Si no hay ningún cliente conectado al router, pulse prolongadamente el botón WPS del router y espere hasta que el indicador LED del Wi-Fi parpadee. Si al menos un cliente está conectado al router, abra el navegador en el dispositivo conectado y vaya a http://192.168.0.1/, introduzca la contraseña y haga clic en Más > WPS. Pulse el botón programable WPS.</br>2. En el dispositivo que desea conectar al router (p. ej., PC o smartphone), abra la configuración del Wi-Fi compatible con WPS (el proveedor de este dispositivo deberá proporcionarla) y seleccione el modo CP o pulse el botón CP (WPS) en el cuerpo del dispositivo, si está disponible.</br>3. La conexión entre el router y el cliente se establecerá automáticamente en unos 2 minutos.',
ids_sms_deleteSingleWarning:'¿Desea eliminarla?',
ids_menu_more:'Más',
ids_net_4gOnly:'Solo 4G',
ids_profileProtocal_none:'None',
ids_isSupportKickOff:'Ya hay un usuario conectado, ¿desea todavía conectarse? Expulsará a ese usuario.',
ids_changePassword_Tips:'Su nombre de usuario y contraseña actuales son los predeterminados. Le recomendamos que cambie la contraseña por otra que pueda recordar fácilmente. Haga <a class="userpass_link">&nbsp;clic aquí&nbsp;</a> para cambiar el nombre de usuario y la contraseña.',
ids_wifi_wifiSleep:'WiFi Sleep',
ids_security_upnpDescription:'UPnP permite redes de dispositivo a dispositivo. Es un protocolo de arquitectura distribuido y abierto, basado en estándares establecidos como el conjunto de protocolos de Internet (TCP/IP), HTTP, XML y SOAP.',
ids_sms_deleteAll:'Eliminar todo',
ids_pb_location:'Ubicación',
ids_diagnostic:'Diagnóstico',
ids_security_macAddrInvalid:'La dirección MAC no es válida.',
ids_security_PowerSavingWiFiTips:'El Wi-Fi se desconectará automáticamente si la conexión está inactiva durante mucho tiempo.',
ids_tr069_connRqUsername:'Nombre de usuario de solicitud de conexión',
ids_security_PowerSavingWiFi:'Wi-Fi',
ids_profile_pwdRule:'El número máximo de caracteres para la contraseña es 31, sin incluir " : ; & .',
ids_tr069_inform:'Informar',
ids_locked_permanently:'El dispositivo se ha bloqueado permanentemente y no se puede desbloquear.',
ids_sys_setRebootEvent:'Se está reiniciando el dispositivo, espere 60 segundos y, a continuación, haga vuelva a conectarse al dispositivo Wi-Fi.',
ids_sms_saveMode:'Modo ahorro',
ids_pb_add:'Añadir',
ids_sim_spck:'SPCK',
ids_security_upnp:'UPnP',
ids_sms_encodingoptimization:'Optimización de codificación de SMS',
ids_profile_inputDialNum:'¡Introduzca el número de marcación!',
ids_dlg_pb_deleteWarning:'¿Seguro que desea proceder con la eliminación?',
ids_security_enableIp:'Habilitar filtro de dirección IP',
ids_sms_mobileNum:'Número del teléfono móvil',
ids_security_urlFilterTitle:'Filtro de URL',
ids_btn_setDefault:'Fijar&nbsp;predeterm.',
ids_wan_connectedRuleIndia:'Por favor, deshabilite la conexión antes de iniciar la gestión de perfiles.',
ids_title_loginSettings:'Ajustes de inicio de sesión',
ids_profile_apn:'APN',
ids_pb_local:'Local',
ids_wan_roamingAutoConnect:'Conectar automáticamente incluso en roaming.',
ids_wifi_key:'Tecla',
ids_login_userName:'admin',
ids_wifi_offRule:'Actualmente, WiFi está desactivado ya que ningún equipo se ha conectado desde hace mucho tiempo. Por favor, habilite WiFi manualmente presionando cualquier botón del dispositivo.',
ids_allow:'Permitir',
ids_usage_MB:'MB',
ids_sim_simLockedTips:'Para obtener más información, haga clic en "Se requiere bloqueo de la SIM" para desbloquear desde el principio.',
ids_login_inputOldPwd:'Introduzca la contraseña antigua.',
ids_icon_downloaded:'Descargadas',
ids_sys_rebootWarn:'¿Desea reiniciar el dispositivo?',
ids_security_enableFirewall:'Habilitar cortafuegos',
ids_security_pfRangePortTip:'El número de puerto LAN no es el mismo que el número de puerto WAN.',
ids_wifi_wepRule:'La clave WEP debe estar formada por caracteres ASCII entre 32 y 127, sin incluir: " : ; & .',
ids_sd_viewFile:'Ver archivo',
ids_icon_debit:'Débito',
ids_wifi_wpa2:'PSK del WPA2',
ids_sim_pinManagement:'Administración del código PIN',
ids_security_upnpStatus:'Estado UPnP',
ids_HelplineNumber:'Número de línea de atención:',
ids_login_confirmPwdRule:'La nueva contraseña y la confirmada deben ser la misma.',
ids_router_leaseTime:'Tiempo de concesión de IP de DHCP',
ids_sd_usedTotal:'(Usados/Total)',
ids_usage_monthlyDataPlan:'Plan mensual de datos',
ids_title_wps:'WPS',
ids_sms_newMessage:'Nuevo mensaje',
ids_auto:'AUTO',
ids_usage_setTimeLimit:'Ajustar límite de tiempo',
ids_wifi_wep:'WEP',
ids_net_status:'Estado',
ids_usage_minutes:'minutos',
ids_wifi_wpsActive:'WPS activada.',
ids_menu_usageSetting:'Ajustes de uso',
ids_login_otherLogin:'El administrador ya ha iniciado sesión, inténtelo más tarde.',
ids_btn_wan_disconnect:'Desconectar',
ids_tr069_inputAcsUserName:'Por favor, introduzca el nombre de usuario del ACS antes de guardar.',
ids_security_ipFilterList:'Lista de filtrado de IP',
ids_wifi_on:'Activado',
ids_day:'día',
ids_net_gsm:'2G',
ids_usage_notAccurate:'Es posible que las estadísticas no sean precisas.',
ids_sim_pukRequired:'Se requiere PUK',
ids_security_ipOption:'Opciones',
ids_net_lte:'4G',
ids_router_subnetEmpty:'¡La máscara de subred está vacía. Vuelva a introducirla!',
ids_pdpTimer_5seconds:'5 segundos',
ids_wan_roamingPopWarningMessage:'Haga clic en <Aceptar> para usar datos en itinerancia. Verifique con su proveedor de red los precios',
ids_manual:'Manual',
ids_menu_connectDevice:'Dispositivo(s) conectado(s)',
ids_profile_dialNumber:'Número de marcación',
ids_menu_sms:'SMS',
ids_sys_hwVersion:'Versión de hardware',
ids_usage_mothlyDataTips:'Introduzca la fecha entre 1 y 1024.',
ids_pdpTimer_90seconds:'90 segundos',
ids_title_macFilter:'Filtro de MAC',
ids_netMode_Automatic4g3g2g:'(4G & 3G & 2G)Automático',
ids_sys_noFileChosen:'Archivo no seleccionado',
ids_dlg_sms_mobileNumRule:'Introduzca un número válido: solo entre el 0 y el 9 y \'+\', sin espacios ni caracteres especiales.',
ids_wan_connecting:'Conectando......',
ids_profile_inputName:'Introduzca el nombre del perfil antes de guardarlo.',
ids_wan_Block:'La lista de direcciones MAC está llena, no se puede procesar esta opción.',
ids_icon_people:'Contactos',
ids_sim_autoValidate:'Auto validar',
ids_menu_language:'Idioma',
ids_wifi_wpsPinRule:'El código PIN WPS debe contener entre 4 u 8 dígitos.',
ids_title_pinCodeSettings:'Ajustes del código PIN',
ids_net_searching:'Buscando......',
ids_wifi_wpaRule:'La PSK del WPA debe estar formada por caracteres ASCII entre 32 y 127, sin incluir: " : ; & .',
ids_ussd_notSupport:'No soportado. Por favor, inténtelo de nuevo.',
ids_tr069_acsUrl:'URL de ACS',
ids_sms_report:'Informe SMS',
ids_sim_cck:'CCK',
ids_security:'Seguridad',
ids_enable:'Habilitar',
ids_wifi_wpaAes:'AES',
ids_btn_next:'Siguiente',
ids_profile_profileName:'Nombre de perfil',
ids_wifi_wepOpen:'WEP-OPEN',
ids_wan_connectIPMode:'Modo de conexión IP',
ids_router_subnetInvalid:'¡La máscara de subred no es válida. Vuelva a introducirla!',
ids_pdpTimer_30seconds:'30 segundos',
ids_usage_min:'Min',
ids_wan_connected:'Conectado'
}