var resourceInfo={
ids_fota_upgradingTips:'Nu opriți dispozitivul în timpul actualizării. Acesta va fi repornit după actualizare.',
ids_usage_billingDay:'Zi de facturare',
ids_sms_phoneNumberInvalid:'Număr de telefon incorect',
ids_btn_logout:'Deconectare',
ids_wifi_ssidBroadcast:'Transmisie SSID',
ids_wifi_wpaDescription:'Cheia pre-partajată WPA (PSK) trebuie să aibă între 8 și 63 de caractere ASCII.',
ids_dlg_pb_nameRule:'Numele nu poate conține următoarele caractere: „\\”, „\\\'”.',
ids_usage_GB:'GB',
ids_UserNameRule32:'Lungimea maximă a numelui utilizatorului este de 32 de caractere, nefiind acceptate următoarele: " : ; & .',
ids_pdpTimer_120seconds:'120 secunde',
ids_profile_profileNameRule:'Lungimea maximă a numelui profilului este de 31 de caractere, nefiind acceptate următoarele: , " : ; \\ & % + < > ?.',
ids_security_ipFilterDescription:'Intervalul de valori pentru port este 0 - 65535.',
ids_back:'Înapoi',
ids_usage_dataUsageReach:'Când utilizarea datelor atinge valoarea abonamentului lunar de date',
ids_router_startIpInvalid:'Prima adresă IP este incorectă. Introduceți-o din nou!',
ids_iptype:'Tip de IP',
ids_net_selectWarn:'Selectați o rețea!',
ids_login_inputCurrPwd:'Parola actuală este greșită.',
ids_sim_autoPin:'Validare automată a codului PIN',
ids_wifi_offTip:'Funcția Wi-Fi este dezactivată. Încercați din nou după ce activați funcția.',
ids_net_3g4gOnly:'Doar 3G / 4G',
ids_wifi_wifiOffTime_30min:'30 minute',
ids_fota_batteryTips:'Nivelul de încărcare al acumulatorului este redus. Dispozitivul nu poate fi actualizat.',
ids_wifi_wpa:'WPA PSK',
ids_wifi_cipher:'Tip cifru',
ids_sim_initializing:'Cartela SIM se inițializează.',
ids_success:'Operațiune reușită',
ids_sim_lockCodeRule:'Codul de blocare a cartelei SIM trebuie să aibă 10 cifre.',
ids_sim_pinRequired:'Este necesar codul PIN',
ids_router_endIpInvalid:'Ultima adresă IP este incorectă. Introduceți-o din nou!',
ids_security_macFilterDescription:'Controlați și gestionați dispozitivul care accesează rețeaua WLAN. (îmbunătățiți securitatea WLAN).',
ids_net_lteOnlyVal:'Numai LTE',
ids_security_PowerSavingSmartTips:'Toate ledurile se sting automat, cu excepția ledului de funcționare, când nu există acces Wi-Fi sau operațiuni manuale timp de 30 de secunde.',
ids_wan_tips:'Eroare! Depășire a istoricului de utilizare; puteți reseta abonamentul de date, iar apoi vă puteți reconecta.',
ids_wan_roamingWarningMessage:'Serviciul de date Roaming vă permite să navigați pe Internet, să utilizați e-mail, MMS și alte servicii de date în străinătate. Consultați furnizorul de rețea pentru a stabili prețurile',
ids_title_preferredDnsServer:'Server DNS preferat',
ids_modify:'Modificare',
ids_title_connectMode:'Mod de conectare',
ids_net_noService:'Nu există semnal',
ids_net_2g3gOnly:'Doar 2G / 3G',
ids_sms_chatInputConfirm:'Vă rugăm să apăsați Enter pentru a finaliza',
ids_sms_mobileNumRule:'Numărul de mobil poate avea maximum 20 de cifre, inclusiv „+0123456789”. Introduceți-l din nou.',
ids_dlg_pb_NumberNullWarning:'Câmpul Număr de telefon nu poate fi gol.',
ids_usage_hours:'ore',
ids_usage_timePassed:'Timp scurs',
ids_wifi_country:'Țară',
ids_wifi_wlan_mode:'Mod WLAN',
ids_net_umts:'3G',
ids_fail:'Eroare!',
ids_wifi_wpsPin:'PIN WPS',
ids_wan_inputDeviceName:'Introduceți numele dispozitivului',
ids_sms_sendFail:'Trimiterea mesajului SMS nu a reușit',
ids_sim_pukCode:'Cod PUK',
ids_sms_newMessageOn:'necitite din',
ids_tr069_inputConReqPassword:'Introduceți parola pentru conectare înainte de a o salva.',
ids_sys_swVersion:'Versiune software',
ids_sim_simlockError:'Eroare cod de blocare SIM!',
ids_security_ipFilterPort:'Intervalul de valori pentru port este 0 - 65535.',
ids_wifi_inputSsid:'Introduceți codul SSID.',
ids_clearCode_Thirtythree:'Nu există date privind serviciul',
ids_sim_confirmPinCode:'Confirmați codul PIN',
ids_security_dmzStatus:'Stare DMZ',
ids_security_macAddrNameWarn:'Această adresă MAC există deja.',
ids_security_portRule:'Intervalul de valori pentru port este 1 - 65535.',
ids_router_startIP:'Prima adresă IP',
ids_fotaUpdate_openRoaming_meg:'Se pot percepe costuri suplimentare pentru descărcare în roaming. Consultați operatorul dvs. de telefonie mobilă. Doriți să continuați?',
ids_net_forbid:'Interzis',
ids_btn_loginTimeout:'re-înregistrare',
ids_security_wanIpAddr:'Adresă IP WAN',
ids_profile_userName:'Nume de utilizator',
ids_profile_password:'Parolă',
ids_btn_restore:'Restabilire',
ids_tips_livechat:'Chat live',
ids_login_inputPwd:'Introduceți parola.',
ids_login_inputUserName:'Introduceți numele de utilizator.',
ids_pdpTimer_20seconds:'20 secunde',
ids_btn_previous:'Înapoi',
ids_sys_restoreBackupWarn:'Această acțiune va duce la actualizarea setărilor și la repornirea dispozitivului după finalizarea încărcării. Sigur doriți să continuați?',
ids_security_ipLanWan:'Notă: Intervalul valoric al Portului LAN/WAN este ȋntre 0 și 65535; 0 înseamnă oricare.',
ids_usage_KB:'KB',
ids_login_remenberPassword:'Reține parola',
ids_security_firewallDes:'Această pagină oferă informații despre modul de activare a funcțiilor de filtrare Firewall. Funcțiile de filtrare a adreselor IP sunt disponibile doar când funcția Firewall este activată.',
ids_title_wifiSettings:'Setări Wi-Fi',
ids_sim_invalidSimCard:'Cartelă SIM nevalidă',
ids_sim_unknown:'Necunoscut',
ids_wan_disconnecting:'Se deconectează...',
ids_btn_delete:'Ștergeți',
ids_tr069_client:'Client TR-069 – Configurare',
ids_wifi_channel:'Canal Wi-Fi',
ids_title_dnsSetting:'DNS',
ids_pb_name:'Nume',
ids_btn_apply:'Aplică',
ids_fota_latestVersion:'Aceasta este deja cea mai recentă versiune.',
ids_security_urlAddrInvalid:'Adresa URL este incorectă.',
ids_wan_cannotBlock:'Filtrul MAC este activat în acest moment, iar această opțiune nu poate fi procesată.',
ids_deny:'Refuzați',
ids_sms_saveDraftSuccess:'Mesajul SMS este salvat ca schiță',
ids_network_notAvailableFunctionWarn:'Vă rugăm să deconectați conexiunea de date înainte de a iniția Administrarea profilului',
ids_usage_duration:'Durată',
ids_sim_rck:'RCK',
ids_sms_deleteWarning:'Sigur doriți să ștergeți mesajul(mesajele)?',
ids_icon_uploaded:'Încărcat',
ids_orange_sim_pinOperationWarn:'Nu puteți actualiza setările codului PIN în timp ce sunteți conectat la internet.',
ids_dlg_pb_mobileNumRule:'Numărul de mobil poate avea maximum 40 de cifre, inclusiv „+0123456789”. Introduceți-l din nou.',
ids_title_profilesManagement:'Administrare profil',
ids_wifi_wifiOffTime_20min:'20 minute',
ids_sim_lockForbidden:'Blocarea cartelei SIM este interzisă!',
ids_sim_pinRule:'Codul PIN trebuie să aibă între 4 și 8 cifre.',
ids_security_dmzTips:'Funcția DMZ permite dispozitivului selectat să evite funcțiile de firewall ale dispozitivului gateway și permite accesul fără restricții de pe internet pe dispozitivul respectiv.',
ids_router_startSameSubnet:'Prima adresă IP și „Adresa IP” trebuie să aparțină aceleiași subrețele.',
ids_btn_help:'Ajutor',
ids_menu_smsSettings:'Setări SMS',
ids_profile_nameWarn:'Acest nume de profil există deja.',
ids_wifi_wifiOffTime_10min:'10 minute',
ids_sim_newPinRule:'Noul cod PIN trebuie să aibă între 4 și 8 cifre.',
ids_sim_comfirmPinRule:'Codul PIN confirmat trebuie să aibă între 4 și 8 cifre.',
ids_sim_enterValidCode:'Introduceți un cod PIN corect.',
ids_btn_send:'Trimitere',
ids_net_available:'Disponibil',
ids_profile_numRule:'Observație: Numărul maxim de profiluri pe care le puteți crea este 15.',
ids_gsm7_text:'GSM 7',
ids_dlg_sms_smsForwardNumEmpty:'Câmpul pentru numărul de telefon mobil este gol. Introduceți numărul.',
ids_wifi_wepDescription:'Cheia WEP este formată din 5 sau 13 caractere ASCII ori din 10 sau 26 de caractere hexazecimale.',
ids_sd_sdCard:'Cartelă SD',
ids_sys_deviceName:'Nume dispozitiv',
ids_days:'zile',
ids_sys_ipAddress:'Adresă IP',
ids_login_nameOrPwdWrong:'Nume de utilizator sau parolă incorecte!',
ids_profile_userNameRule:'Lungimea maximă a numelui utilizatorului este de 31 de caractere, nefiind acceptate următoarele: " : ; & .',
ids_wifi_cannotSet:'Funcția Wi-Fi este dezactivată pentru moment. Această opțiune nu poate fi procesată.',
ids_router_ipAddrEmpty:'Câmpul pentru adresa IP este gol. Introduceți-l din nou!',
ids_wifi_pinDecription:'PIN WPS (configurare WPS prin introducerea codului special de 8 cifre):<br/>1. Dacă la router este conectat cel puțin un client, deschideți un browser de pe dispozitivul conectat, accesați adresa http://192.168.0.1/, introduceți parola și dați clic pe opțiunea Mai multe > WPS. Selectați PIN WPS.<br/>2. Pe dispozitivul pe care doriți să îl conectați la router (de exemplu, computer sau telefon inteligent) deschideți aplicația de configurare Wi-Fi care acceptă WPS (ar trebui să fie oferită de furnizorul acestui dispozitiv) și alegeți modul PIN WPS. Se va genera un cod PIN WPS din 8 cifre.<br/>3. Reveniți la interfața web a routerului, introduceți codul PIN WPS format din 8 cifre în câmpul PIN WPS și dați clic pe Aplicare.<br/>4. Conexiunea dintre router și client va fi stabilită automat în circa două minute.',
ids_tr069_tips:'Selectați valorile dorite și dați clic pe „Aplicare/Salvare” pentru a configura opțiunile clientului TR-069.',
ids_more_onlineUpdate:'Actualizare online',
ids_security_btnAdd:'Adăugare',
ids_sms_autoForward:'Redirecționare SMS către telefon mobil',
ids_sim_simLockCode:'Cod blocare cartelă SIM',
ids_router_restartWarn:'Pentru această acțiune este necesară repornirea dispozitivului. Sigur doriți să continuați?',
ids_sms_saveSimCard:'Cartela SIM',
ids_automatic:'Automat',
ids_security_portTips:'Observație: Specificați portul și grupul de porturi, de exemplu: 30 sau 65500-65510.',
ids_wifi_wpsNotSuppotSSIDHidden:'Cod SSID necunoscut. Nu se poate seta procedura WPS.',
ids_netMode_Automatic3g2g:'Automat(3G & 2G)',
ids_wifi_apIsotation:'Izolare punct de acces',
ids_security_portForwarding:'Redirecționare de port',
ids_btn_add:'Adăugare',
ids_usage_billingTimeTips:'Introduceți o zi între 1 și 31.',
ids_minutes:'minute',
ids_ussd_inputDescription:'Introduceți codul USSD',
ids_fota_upgrading:'Se actualizează...',
ids_router_dhcpServer:'Server DHCP',
ids_sim_pinRequiredTips:'Pentru mai multe informații, dați clic pe „Este necesar codul PIN” pentru a efectua întâi deblocarea.',
ids_login_checkPwdRule:'Parolă incorectă! Parola de conectare trebuie să aibă între 4 și 16 caractere, inclusiv 0-9, a-z, A-Z,„-+!@$#^&*”. Introduceți-o din nou.',
ids_wifi_wifiOffTime:'Perioada în care funcția Wi-Fi a fost oprită',
ids_sd_sdShareMode:'Mod de partajare cartelă SD',
ids_btn_continue:'Continuare',
ids_profile_protocal:'Protocol',
ids_security_lanPort:'Port LAN',
ids_dlg_sms_reInputCenterNum:'Numărul pentru centrul de mesaje text este incorect. Introduceți-l din nou!',
ids_btn_backup:'Copie de rezervă',
ids_wan_connected_num:'Conectat',
ids_sms_centerNum:'Centru SMS',
ids_fota_downloading:'Se descarcă...',
ids_wifi_wpaWpa2Psk:'WPA/WPA2 PSK',
ids_usage_of:'din',
ids_sys_rebootDecription:'Dați clic pe acest buton pentru a reporni dispozitivul.',
ids_title_about:'Despre',
ids_sim_nck:'NCK',
ids_net_operator:'Operator',
ids_router_endIpEmpty:'Câmpul pentru ultima adresă IP este gol. Introduceți-l din nou!',
ids_btn_cancel:'Anulare',
ids_dlg_pb_nameNullWarning:'Câmpul Nume nu poate fi gol.',
ids_dlg_sms_inputCenterNum:'Câmpul pentru centrul de mesaje text este gol. Introduceți numărul.',
ids_ussd_rule:'Pot fi introduse doar caracterele „*”, „#” și numere.',
ids_wifi_wifi:'Wi-Fi',
ids_sms_selectSomeOptions:'Cel mult 3 contacte',
ids_btn_new:'Nou',
ids_fota_findNewVersion:'Căutare versiune nouă',
ids_security_pfNumRule:'Observație: Numărul maxim de redirecționări de port pe care le puteți crea este 16.',
ids_wifi_showPwd:'Afișați parola',
ids_security_urlFilterList:'Listă filtru URL',
ids_loginTimeout:'Timp de conectare expirat. Trebuie să vă conectați din nou.',
ids_title_alternateDnsServer:'Server DNS alternativ',
ids_login_inputNewPwd:'Introduceți parola nouă.',
ids_fota_updateTitle:'Actualizări de sistem',
ids_login_inputConfirmPwd:'Introduceți parola confirmată.',
ids_hours:'ore',
ids_wifi_maxUser:'Numărul maxim de utilizatori',
ids_pb_addNew:'Adăugare',
ids_usage_timeLimit:'Limită de timp',
ids_sim_pinCode:'Cod PIN',
ids_wifi_wpaTkip:'TKIP',
ids_sim_autoPinState:'Starea actuală',
ids_security_dmzTitle:'DMZ',
ids_security_dmzIpInvalid:'Adresa IP DMZ nu este o adresă IP valabilă.',
ids_btn_unblock:'Deblocare',
ids_fota_checkUpdate:'Actualizare',
ids_title_advanced:'Setări avansate',
ids_security_ipFilterWarn:'Acest filtru IP există deja.',
ids_fota_updateDescription:'Dați clic pe „Actualizare” pentru a trece la noua versiune.',
ids_btn_reset:'Resetați',
ids_tr069_acsUrlRule:'Formatul adresei URL ACS: de exemplu: http://adresa ip:port/xxx',
ids_show_again:'Nu afișați acest mesaj din nou',
ids_usage_hrs:'Ore',
ids_icon_battery:'Acumulator',
ids_sms_saveDevice:'Dispozitiv',
ids_roamAppear:'Glisați pentru a utiliza conexiunea de date în roaming. Pentru informații despre prețuri, luați legătura cu operatorul dvs.',
ids_sys_chooseFile:'Alegeți un fișier',
ids_btn_refresh:'Împrospătare',
ids_pb_phoneBook:'Agendă',
ids_net_select:'Selectare rețea',
ids_sim_pinError:'Eroare cod PIN!',
ids_sms_saveDraftFailed:'Eroare la salvarea schiței',
ids_sms_delivered:'Trimis',
ids_usage_autoDisconnected:'Deconectat automat',
ids_login_confirmPwd:'Confirmați parola:',
ids_security_addMacAddress:'Adăugați o adresă MAC',
ids_sim_noSimCard:'Nu există cartelă SIM',
ids_wifi_notSuppotWepWpa:'Funcția WPS nu este disponibilă cu WEP, WPA, WPA2 TKIP!',
ids_security_pfWarn:'Redirecționarea de port există deja.',
ids_fota_checking:'Se verifică...',
ids_dlg_pb_lenWarning:'Datele introduse sunt prea lungi',
ids_sim_newPinCode:'Cod PIN nou',
ids_sim_pinNotAvailable:'Codul PIN nu este disponibil',
ids_usage_clear:'Ștergere istoric',
ids_wifi_maxSsid:'Codul SSID poate avea maximum 32 de caractere, inclusiv 0-9, a-z, A-Z, „-”, „_”, „.” ,„ ”.',
ids_usage_startTimeTips:'Introduceți datele, utilizând cifre între 1 și 43200.',
ids_wifi_pbcConfiguration:'(Push Button Configuration - Configurare prin buton de comandă)',
ids_usage_dataConsumption:'Trafic de date',
ids_disable:'Dezactivare',
ids_ucs2Orgsm7_text:'UCS2 Or GSM7',
ids_login_loginPwd:'Parolă de conectare',
ids_btn_save:'Salvare',
ids_wifi_802mode:'Mod 802.11',
ids_pb_phoneNumber:'Număr de telefon',
ids_ussd_timeOut:'Timp expirat! Încercați din nou.',
ids_btn_reboot:'Reporniți',
ids_minute:'minut',
ids_router_ipAddrInvalid:'Adresa IP este incorectă. Introduceți-o din nou!',
ids_router_startIpEmpty:'Câmpul pentru prima adresă IP este gol. Introduceți-l din nou!',
ids_sim_pinEnable:'Funcția de validare automată a codului PIN este activată.',
ids_sim_pinCodeOperation:'Operațiune cod PIN',
ids_security_dmzInvalidLanSubnet:'Adresa IP DMZ nu există în subrețeaua LAN.',
ids_net_service:'Serviciu',
ids_router_ipRule:'Eroare! Rețineți că, următoarele 10 adrese de după adresa de acasă sunt adrese IP rezervate în prealabil și nu pot fi incluse în rezervorul de adrese IP DHCP.',
ids_usage_roaming:'Roaming',
ids_title_ussd:'USSD',
ids_btn_ok:'OK',
ids_sys_resetDecription:'Reveniți la setările implicite din fabrică.',
ids_tr069_inputInformInterval:'Introduceți intervalul de informare înainte de a-l salva.',
ids_security_dmzIpAddr:'Adresă IP DMZ',
ids_profile_inputApn:'Introduceți numele punctului de acces.',
ids_sys_restoreFactoryWarn:'Această acțiune va duce la restabilirea setărilor implicite din fabrică și la repornirea dispozitivului. Sigur doriți să continuați?',
ids_net_registing:'Se înregistrează...',
ids_sys_backupDecription:'Descărcați configurarea (realizați o copie de rezervă)',
ids_sms_selectAnOption:'Selectați o opțiune',
ids_tr069_inputAcsUrl:'Introduceți adresa URL ACS înainte de a o salva.',
ids_tr069_acsUsername:'Nume de utilizator ACS',
ids_pdpTimer_0seconds:'0 secunde',
ids_usage_home:'Rețea locală',
ids_profile_deleteWarn:'Sigur doriți ștergerea?',
ids_sms_smsFull:'Cutia de mesaje SMS este plină. Ștergeți câteva mesaje pentru a putea trimite/salva mesaje noi.',
ids_tr069_connRqPw:'Parolă pentru conectare',
ids_sim_pukError:'Eroare cod PUK!',
ids_sys_system:'Sistem',
ids_security_PowerSavingSmart:'Inteligent',
ids_login_timeuseout:'Durata încercării de conectare a fost depășită. Reporniți și încercați din nou.',
ids_usage_minutesTimes:'minut(e)',
ids_sim_pukRule:'Codul PUK trebuie să aibă 8 cifre.',
ids_net_3gOnly:'Numai 3G',
ids_sim_nsck:'NSCK',
ids_subnetMask:'Mască subrețea:',
ids_pdpTimer_60seconds:'60 secunde',
ids_sim_pinDisable:'Funcția de validare automată a codului PIN este dezactivată.',
ids_sys_macAddress:'Adresă MAC',
ids_menu_connection:'Conexiune',
ids_dlg_pb_tooManyNumbers:'Pentru a începe modificarea, selectați doar un singur număr.',
ids_password:'Parolă',
ids_security_virtualServer:'Server virtual (redirecționare de port static)',
ids_security_ipFilterDes:'Pachetele de filtru care utilizează următoarele reguli specificate în protocol, port și adresă IP.',
ids_ussd_checkBlance:'Verificare credit',
ids_title_tr069:'TR069',
ids_sms_draft:'Schiță',
ids_wifi_encryption:'Criptare',
ids_title_ping:'Ping',
ids_foot_copyright:'Copyright 2016-2018 TCL Communication Ltd. Toate drepturile rezervate.',
ids_tr069_acsPw:'Parolă ACS',
ids_help_userManual:'Manual de utilizare',
ids_security_pfDescription:'Redirecționarea de port permite computerelor externe să acceseze WWW, FTP sau alte servicii oferite de LAN.',
ids_wifi_notSuppotMacFilter:'Procedura WPS (versiunea 2.0) nu poate fi activată dacă filtrul de adresă Mac este activat.',
ids_title_blockDevice:'Blocare dispozitiv',
ids_router_endGeaterStart:'Valoarea ultimei adrese IP trebuie să fie mai mare decât cea utilizată pentru „Prima adresă IP”.',
ids_net_2gOnly:'Numai 2G',
ids_clearCode_Twentynine:'Eroare autentificare',
ids_usage_day:'zi',
ids_wifi_wepShare:'Partajare',
ids_sms_messageSending:'Se trimite un SMS',
ids_wan_roamingPopCloseConntectTips:'Roaming-ul de date va fi dezactivat.',
ids_sd_currentFolder:'Dosar actual',
ids_wan_disconnected:'Deconectat',
ids_security_numRule:'<b>Observație:</b>numărul maxim de filtre IP care pot fi create este 16.',
ids_dns_manual_mode:'Mod manual DNS',
ids_login:'Conectare',
ids_security_PowerSavingTitle:'Economisire energie',
ids_security_lanIpAddr:'Adresă IP LAN',
ids_menu_settings:'Setări',
ids_wifi_disconWarning:'Această acțiune va duce la deconectarea funcției Wi-Fi. Sigur doriți să continuați?',
ids_wifi_wpsActiveWarn:'Procedura WPS este în curs. Încercați din nou peste două minute!',
ids_login_loginUserName:'Nume de utilizator pentru conectare',
ids_wifi_wepWifiCertification:'Cheia WEP este formată din 5 sau 13 sau 10 sau 26 de caractere.',
ids_connect:'Conectare',
ids_btn_block:'Blocare',
ids_pb_number:'NU.',
ids_login_wrongPwd:'Parolă greșită!',
ids_sms_smsForwarding:'Redirecționare SMS',
ids_sys_selectFilePrompt:'Selectați un fișier înainte de încărcare.',
ids_wifi_wifiSecurity:'Securitate Wi-Fi',
ids_btn_edit:'Modificați',
ids_security_firewallSwitch:'Comutare Firewall',
ids_router_endIP:'Ultima adresă IP',
ids_sys_imei:'IMEI',
ids_sim_remainTime:'Încercări rămase',
ids_update_Confirm:'Fișierul a fost descărcat, sunteți sigur că doriți să actualizați?',
ids_sim_pinConfirmed:'Codul PIN confirmat trebuie să fie identic cu noul cod PIN.',
ids_filter_urlAddress:'Adresă URL',
ids_validate:'Validare',
ids_security_subnetWarn:'Adresa IP LAN și „Adresa IP” trebuie să aparțină aceleiași subrețele.',
ids_sms_inputNum:'Introduceți un număr de mobil.',
ids_tr069_informInterval:'Interval(e) de informare',
ids_fota_haveNewVersion:'Este disponibilă o nouă versiune software. Dați clic pentru actualizare.',
ids_sim_pukRequiredTips:'Pentru mai multe informații, dați clic pe „Este necesar codul PUK” pentru a efectua întâi deblocarea.',
ids_sms_emptyMessageWarn:'Mesajul este gol. Sigur doriți să trimiteți acest mesaj gol?',
ids_sim_pck:'PCK',
ids_usage_clearHistory:'Sigur doriți să resetați toate statisticile?',
ids_hour:'oră',
ids_tr069_connRqAuth:'Autentificare pentru conectare',
ids_wifi_off:'Dezactivată',
ids_pb_storageStatus:'Stare mediu de stocare',
ids_wan_connectedRule:'Această setare nu poate fi utilizată în modul conectat. Dați clic pe „Deconectare” și încercați din nou.',
ids_menu_usage:'Utilizare',
ids_security_dmzDescription:'Dacă un computer nu poate rula aplicațiile din rețea prin dispozitivul gateway, activați funcția DMZ și introduceți mai jos adresa IP a computerului.',
ids_title_networkMode:'Mod rețea',
ids_wifi_wifiOffTime_5min:'5 minute',
ids_wifi_pbc:'PBC',
ids_error:'Eroare!',
ids_sim_changePinError:'Eroare schimbare cod PIN!',
ids_security_wanPort:'Port WAN',
ids_security_ipFilter:'Filtru IP',
ids_tr069_inputConReqUserName:'Introduceți numele de utilizator pentru conectare înainte de a-l salva.',
ids_tr069_informIntervalRule:'Intervalul de informare trebuie să fie între 0 și 2678400, inclusiv „0123456789”.',
ids_login_newPwd:'Parolă nouă',
ids_pdpTimer_10seconds:'10 secunde',
ids_security_virtualServerList:'Listă de servere virtuale',
ids_security_urlAddrNameWarn:'Această adresă URL există deja.',
ids_btn_select:'Selectați',
ids_router_endSameSubnet:'Ultima adresă IP și „Adresa IP” trebuie să aparțină aceleiași subrețele.',
ids_ussd_CodeEmpty:'Caseta de introducere nu poate rămâne necompletată!',
ids_sim_autoPinError:'Eroare la verificarea automată a codului PIN!',
ids_usage_cancelLimitTips:'Setați limita de date la 0 și salvați pentru a anula orice limită de date.',
ids_sim_simLocked:'Este necesar codul de blocare a cartelei SIM',
ids_icon_timeElapsed:'Timp scurs',
ids_sms_sendingPrompt:'Se trimite... Așteptați!',
ids_tr069_inputAcsPassword:'Introduceți parola ACS înainte de a o salva.',
ids_requestError:'Niciun răspuns. Este posibil ca dispozitivul să fie deconectat. Reporniți dispozitivul și încercați din nou.',
ids_profile_inputRule:'Numele APN și numărul de apelare trebuie să conțină caractere ASCII cuprinse între pozițiile 32 și 127, mai puțin următoarele: " : ; & .',
ids_net_active:'Activ',
ids_sms_numberWarning:'Textul introdus este prea lung. Ștergeți din text.',
ids_data:'Conexiune de date',
ids_pdpTimer:'Temporizator PDP',
ids_menu_sharing:'Partajare',
ids_sd_noSdCard:'Nicio cartelă SD',
ids_wifi_pbcDecription:'1. Dacă niciun client nu este conectat la router, apăsați lung butonul WPS de pe router și așteptați până când ledul Wi-Fi pâlpâie. Dacă la router este conectat cel puțin un client, deschideți un browser de pe dispozitivul conectat, accesați adresa http://192.168.0.1/, introduceți parola și dați clic pe opțiunea Mai multe > WPS. Apăsați tasta funcțională WPS.<br/>2. Pe dispozitivul pe care doriți să îl conectați la router (de exemplu, computer sau telefon inteligent) deschideți aplicația de configurare Wi-Fi care acceptă WPS (ar trebui să fie oferită de furnizorul acestui dispozitiv) și alegeți modul PBC sau apăsați butonul PBC (WPS) de pe carcasa dispozitivului, dacă acesta există.<br/>3. Conexiunea dintre router și client va fi stabilită automat în circa două minute.',
ids_sms_deleteSingleWarning:'Sigur doriți să ștergeți mesajul?',
ids_menu_more:'Mai multe',
ids_net_4gOnly:'Numai 4G',
ids_profileProtocal_none:'None',
ids_isSupportKickOff:'Alt utilizator este deja conectat, doriți totuși să vă conectați? Acest lucru va deconecta celălalt utilizator.',
ids_changePassword_Tips:'Numele dvs. de utilizator și parola din prezent sunt cele implicite. Vă recomandăm să schimbați parola actuală cu o parolă pe care să o rețineți ușor. <a class="userpass_link">&nbsp;Dați clic aici&nbsp;</a> pentru a schimba numele de utilizator și parola.',
ids_wifi_wifiSleep:'WiFi Sleep',
ids_security_upnpDescription:'UPnP permite dispozitivului să intre într-o rețea de dispozitive. Este un protocol distribuit cu arhitectură deschisă, bazat pe standarde consacrate, cum ar fi suita protocoalelor de internet (TCP/IP), HTTP, XML și SOAP.',
ids_sms_deleteAll:'Ștergeți tot',
ids_pb_location:'Loc',
ids_diagnostic:'Diagnostic',
ids_security_macAddrInvalid:'Adresa MAC este incorectă.',
ids_security_PowerSavingWiFiTips:'Funcția Wi-Fi se va opri automat dacă conexiunea este inactivă pentru o perioadă lungă de timp.',
ids_tr069_connRqUsername:'Nume de utilizator pentru conectare',
ids_security_PowerSavingWiFi:'Wi-Fi',
ids_profile_pwdRule:'Lungimea maximă a parolei este de 31 de caractere, nefiind acceptate caracterele următoarele: " : ; & .',
ids_tr069_inform:'Informare',
ids_locked_permanently:'Acest dispozitiv a fost blocat definitiv și nu mai poate fi deblocat.',
ids_sys_setRebootEvent:'Dispozitivul se repornește. Așteptați 60 de secunde, apoi reconectați-l la dispozitivul Wi-Fi.',
ids_sms_saveMode:'Mod de salvare',
ids_pb_add:'Adăugare',
ids_sim_spck:'SPCK',
ids_security_upnp:'UPnP',
ids_sms_encodingoptimization:'Optimizarea codării SMS',
ids_profile_inputDialNum:'Introduceți numărul de apelare!',
ids_dlg_pb_deleteWarning:'Sunteți sigur(ă) că doriți să ștergeți?',
ids_security_enableIp:'Activare filtru adresă IP',
ids_sms_mobileNum:'Număr de telefon mobil',
ids_security_urlFilterTitle:'Filtru URL',
ids_btn_setDefault:'Setați&nbsp;valoarea&nbsp;prestabilită',
ids_wan_connectedRuleIndia:'Vă rugăm să deconectați conexiunea de date înainte de a iniția Administrarea profilului',
ids_title_loginSettings:'Setări de conectare',
ids_profile_apn:'Nume punct de acces',
ids_pb_local:'Local',
ids_wan_roamingAutoConnect:'Conectare automată și în roaming',
ids_wifi_key:'Cod',
ids_login_userName:'administrator',
ids_wifi_offRule:'Funcția Wi-Fi este dezactivată momentan, deoarece niciun client nu s-a conectat de mult timp.  Dacă doriți să utilizați funcția Wi-Fi, apăsați oricare buton de pe dispozitiv pentru a o activa.',
ids_allow:'Permiteți',
ids_usage_MB:'MB',
ids_sim_simLockedTips:'Pentru mai multe informații, dați clic pe „Este necesar codul de blocare a cartelei SIM” pentru a efectua întâi deblocarea.',
ids_login_inputOldPwd:'Introduceți parola veche.',
ids_icon_downloaded:'Descărcat',
ids_sys_rebootWarn:'Sigur doriți să reporniți dispozitivul?',
ids_security_enableFirewall:'Activare Firewall',
ids_security_pfRangePortTip:'Numărul de port LAN nu este același ca numărul de port WAN!',
ids_wifi_wepRule:'Cheia WEP trebuie să conțină caractere ASCII cuprinse între pozițiile 32 și 127, mai puțin următoarele: " : ; & .',
ids_sd_viewFile:'Afișare fișier',
ids_icon_debit:'Volum',
ids_wifi_wpa2:'WPA2 PSK',
ids_sim_pinManagement:'Administrare cod PIN',
ids_security_upnpStatus:'Stare UPnP',
ids_HelplineNumber:'Număr de asistență:',
ids_login_confirmPwdRule:'Parola nouă nu este aceeași ca parola confirmată.',
ids_router_leaseTime:'Perioada de închiriere adrese IP DHCP',
ids_sd_usedTotal:'(Utilizat/Total)',
ids_usage_monthlyDataPlan:'Abonament lunar de date',
ids_title_wps:'WPS',
ids_sms_newMessage:'Mesaj nou',
ids_auto:'AUTOMAT',
ids_usage_setTimeLimit:'Setați limita de timp',
ids_wifi_wep:'WEP',
ids_net_status:'Stare',
ids_usage_minutes:'minute',
ids_wifi_wpsActive:'Funcția WPS este activă.',
ids_menu_usageSetting:'Setări de utilizare',
ids_login_otherLogin:'Există deja un utilizator conectat ca administrator. Încercați mai târziu.',
ids_btn_wan_disconnect:'Deconectare',
ids_tr069_inputAcsUserName:'Introduceți numele de utilizator ACS înainte de a-l salva.',
ids_security_ipFilterList:'Listă filtru IP',
ids_wifi_on:'Activată',
ids_day:'zi',
ids_net_gsm:'2G',
ids_usage_notAccurate:'Este posibil ca statisticile să nu fie precise.',
ids_sim_pukRequired:'Este necesar codul PUK',
ids_security_ipOption:'Opțiuni',
ids_net_lte:'4G',
ids_router_subnetEmpty:'Câmpul pentru masca de subrețea este gol. Introduceți-l din nou!',
ids_pdpTimer_5seconds:'5 secunde',
ids_wan_roamingPopWarningMessage:'Faceți clic pe <OK> pentru a utiliza date în roaming. Consultați furnizorul de rețea pentru a stabili prețurile',
ids_manual:'Manual',
ids_menu_connectDevice:'Dispozitiv(e) conectat(e)',
ids_profile_dialNumber:'Număr de apelare',
ids_menu_sms:'SMS',
ids_sys_hwVersion:'Versiune hardware',
ids_usage_mothlyDataTips:'Introduceți datele, utilizând cifre între 1 și 1024.',
ids_pdpTimer_90seconds:'90 secunde',
ids_title_macFilter:'Filtru MAC',
ids_netMode_Automatic4g3g2g:'Automat(4G & 3G & 2G)',
ids_sys_noFileChosen:'Nu au fost găsite fișiere',
ids_dlg_sms_mobileNumRule:'Introduceți un număr corect: doar cifre între 0 și 9 și semnul „+”, fără spații sau caractere speciale.',
ids_wan_connecting:'Se conectează...',
ids_profile_inputName:'Introduceți numele profilului înainte de a-l salva.',
ids_wan_Block:'Lista de adrese MAC este deja plină, iar această opțiune nu poate fi procesată.',
ids_icon_people:'Persoane',
ids_sim_autoValidate:'Validare automată',
ids_menu_language:'Limbă',
ids_wifi_wpsPinRule:'Codul PIN WPS trebuie să aibă între 4 și 8 cifre.',
ids_title_pinCodeSettings:'Setări cod PIN',
ids_net_searching:'Se caută...',
ids_wifi_wpaRule:'Cheia WPA PSK trebuie să conțină caractere ASCII cuprinse între pozițiile 32 și 127, mai puțin următoarele: " : ; & .',
ids_ussd_notSupport:'Nu se acceptă! Încercați din nou.',
ids_tr069_acsUrl:'Adresă URL ACS',
ids_sms_report:'Raport SMS',
ids_sim_cck:'CCK',
ids_security:'Securitate',
ids_enable:'Activare',
ids_wifi_wpaAes:'AES',
ids_btn_next:'Înainte',
ids_profile_profileName:'Nume profil',
ids_wifi_wepOpen:'Deschidere',
ids_wan_connectIPMode:'Modul IP al conexiunii',
ids_router_subnetInvalid:'Masca de subrețea este incorectă. Introduceți-o din nou!',
ids_pdpTimer_30seconds:'30 secunde',
ids_usage_min:'Min.',
ids_wan_connected:'Conectat'
}