var resourceInfo={
ids_fota_upgradingTips:'Schalten Sie das Gerät während der Aktualisierung nicht aus. Das Gerät startet nach der Aktualisierung neu.',
ids_usage_billingDay:'Abrechnungstag',
ids_sms_phoneNumberInvalid:'Ungültige Telefonnummer',
ids_btn_logout:'Abmelden',
ids_wifi_ssidBroadcast:'SSID-Broadcast',
ids_wifi_wpaDescription:'Der WPA-Pre-Shared Key (PSK) muss aus 8-63 ASCII-Zeichen oder 64 hexadezimalen Ziffern bestehen.',
ids_dlg_pb_nameRule:'Der Name darf folgende Zeichen nicht enthalten: \\ und \\\'.',
ids_usage_GB:'GB',
ids_UserNameRule32:'Der Benutzername darf maximal aus 32 Zeichen bestehen, ausgenommen: " : ; & .',
ids_pdpTimer_120seconds:'120 Sekunden',
ids_profile_profileNameRule:'Der Profilname kann aus maximal 31 Zeichen bestehen, ausgenommen: , " : ; \\ & % + < > ?',
ids_security_ipFilterDescription:'Der Wert für den Port muss zwischen 0 und 65.535 liegen.',
ids_back:'Zurück',
ids_usage_dataUsageReach:'Wenn die Datennutzung den monatlichen Datentarif erreicht',
ids_router_startIpInvalid:'Die Start-IP-Adresse ist ungültig. Geben Sie sie erneut ein.',
ids_iptype:'IP-Typ',
ids_net_selectWarn:'Wählen Sie ein Netz aus.',
ids_login_inputCurrPwd:'Das aktuelle Passwort ist falsch.',
ids_sim_autoPin:'Automatische PIN-Code-Überprüfung',
ids_wifi_offTip:'WLAN ist deaktiviert. Versuchen Sie es erneut, nachdem Sie das WLAN geöffnet haben.',
ids_net_3g4gOnly:'Nur 3G / 4G',
ids_wifi_wifiOffTime_30min:'30 Minuten',
ids_fota_batteryTips:'Der Ladestand der Batterie ist zu gering. Das Gerät kann nicht upgedatet werden.',
ids_wifi_wpa:'WPA-PSK',
ids_wifi_cipher:'Verschlüsselungsart',
ids_sim_initializing:'SIM wird initialisiert',
ids_success:'Erfolgreich',
ids_sim_lockCodeRule:'Der Code für die SIM-Sperre sollte 10 Ziffern lang sein.',
ids_sim_pinRequired:'PIN erforderlich',
ids_router_endIpInvalid:'Die End-IP-Adresse ist ungültig. Geben Sie sie erneut ein.',
ids_security_macFilterDescription:'Geräte mit Zugriff auf das WLAN beschränken und WLAN-Sicherheit erhöhen.',
ids_net_lteOnlyVal:'Nur LTE',
ids_security_PowerSavingSmartTips:'Alle LEDs bis auf die Haupt-LED schalten sich innerhalb von 30 Sekunden automatisch aus, wenn keine WLAN-Verbindung besteht oder der manuelle Betrieb aktiviert ist.',
ids_wan_tips:'Fehlgeschlagen. Überlauf bei der Nutzung. Sie können den monatlichen Datentarif zurücksetzen und erneut eine Verbindung herstellen.',
ids_wan_roamingWarningMessage:'Mit Data Roaming können Sie im Internet surfen, E-Mails, MMS und andere Datendienste im Ausland nutzen. Erkundigen Sie sich bei Ihrem Netzwerkanbieter nach Preisen',
ids_title_preferredDnsServer:'Bevorzugter DNS Server',
ids_modify:'Ändern',
ids_title_connectMode:'Verbindungsmodus',
ids_net_noService:'Kein Dienst',
ids_net_2g3gOnly:'Nur 2G / 3G',
ids_sms_chatInputConfirm:'Zum Abschluss Enter drücken',
ids_sms_mobileNumRule:'Die Mobiltelefonnummer kann maximal aus 20 Zeichen bestehen, darunter „+0123456789“. Geben Sie die Nummer erneut ein.',
ids_dlg_pb_NumberNullWarning:'Die Telefonnummer darf nicht leer sein.',
ids_usage_hours:'Stunde(n)',
ids_usage_timePassed:'Verstrichene Zeit',
ids_wifi_country:'Land',
ids_wifi_wlan_mode:'WLAN-Modus',
ids_net_umts:'3G',
ids_fail:'Ein Fehler ist aufgetreten.',
ids_wifi_wpsPin:'WPS-PIN',
ids_wan_inputDeviceName:'Gerätenamen eingeben',
ids_sms_sendFail:'Senden der SMS fehlgeschlagen',
ids_sim_pukCode:'PUK',
ids_sms_newMessageOn:'ungelesen von',
ids_tr069_inputConReqPassword:'Bitte geben Sie das Passwort für die Verbindungsanfrage ein, bevor Sie speichern.',
ids_sys_swVersion:'Softwareversion',
ids_sim_simlockError:'SIM-Lock-Fehler',
ids_security_ipFilterPort:'Der Wert für den Port muss zwischen 0 und 65.535 liegen.',
ids_wifi_inputSsid:'Geben Sie die SSID ein.',
ids_clearCode_Thirtythree:'Keine Dienstdaten',
ids_sim_confirmPinCode:'PIN bestätigen',
ids_security_dmzStatus:'DMZ-Status',
ids_security_macAddrNameWarn:'Die MAC-Adresse ist bereits vorhanden.',
ids_security_portRule:'Der Wert für den Port muss zwischen 1 und 65.535 liegen.',
ids_router_startIP:'Start-IP-Adresse',
ids_fotaUpdate_openRoaming_meg:'Durch das Herunterladen über eine Roaming-Verbindung können zusätzliche Kosten entstehen. Erkundigen Sie sich dazu bei Ihrem Netzbetreiber. Möchten Sie fortfahren?',
ids_net_forbid:'Verboten',
ids_btn_loginTimeout:'Erneut registrieren',
ids_security_wanIpAddr:'WAN-IP-Adresse',
ids_profile_userName:'Benutzername',
ids_profile_password:'Kennwort',
ids_btn_restore:'Wiederherstellen',
ids_tips_livechat:'Live-Chat',
ids_login_inputPwd:'Geben Sie das Passwort ein.',
ids_login_inputUserName:'Geben Sie den Nutzernamen ein.',
ids_pdpTimer_20seconds:'20 Sekunden',
ids_btn_previous:'Zurück',
ids_sys_restoreBackupWarn:'Bei dieser Aktion werden die Einstellungen aktualisiert, und das Gerät wird nach beendetem Hochladen neugestartet. Möchten Sie fortfahren?',
ids_security_ipLanWan:'Hinweis: Der Wertebereich des LAN / WAN-Anschlusses ist 0-65535 und 0 bedeutet beliebig.',
ids_usage_KB:'KB',
ids_login_remenberPassword:'Passwort speichern',
ids_security_firewallDes:'Diese Seite enthält Informationen zur Aktivierung der Firewall-Filterfunktionen. Der IP-Adressenfilter und die WAN-Port-Ping-Funktionen sind nur verfügbar, wenn die Firewall aktiviert ist.',
ids_title_wifiSettings:'WLAN-Einstellungen',
ids_sim_invalidSimCard:'Ungültige SIM-Karte',
ids_sim_unknown:'Unbekannt',
ids_wan_disconnecting:'Verbindung wird getrennt...',
ids_btn_delete:'Löschen',
ids_tr069_client:'TR-069-Client – Konfiguration',
ids_wifi_channel:'WLAN-Kanal',
ids_title_dnsSetting:'DNS',
ids_pb_name:'Name',
ids_btn_apply:'Anwenden',
ids_fota_latestVersion:'Dies ist bereits die neueste Version',
ids_security_urlAddrInvalid:'Die URL-Adresse ist ungültig.',
ids_wan_cannotBlock:'Für den MAC-Filter ist derzeit Zulassen eingestellt. Diese Option kann nicht ausgeführt werden.',
ids_deny:'Verweigern',
ids_sms_saveDraftSuccess:'SMS als Entwurf gespeichert',
ids_network_notAvailableFunctionWarn:'Bitte trennen Sie die Datenverbindung, bevor Sie die Profilverwaltung starten',
ids_usage_duration:'Dauer',
ids_sim_rck:'RCK',
ids_sms_deleteWarning:'Möchten Sie die Mitteilung(en) wirklich löschen?',
ids_icon_uploaded:'Hochgeladen',
ids_orange_sim_pinOperationWarn:'Während eine Internetverbindung besteht, können die PIN-Code-Einstellungen nicht geändert werden.',
ids_dlg_pb_mobileNumRule:'Die maximale Länge der Mobilfunknummer beträgt 40 Zeichen einschließlich +0123456789. Wiederholen Sie die Eingabe.',
ids_title_profilesManagement:'Profilverwaltung',
ids_wifi_wifiOffTime_20min:'20 Minuten',
ids_sim_lockForbidden:'SIM-Sperre verboten.',
ids_sim_pinRule:'Die PIN sollte aus 4-8 Ziffern bestehen.',
ids_security_dmzTips:'Dank DMZ kann das ausgewählte Gerät die Firewall-Funktionen des Gateways umgehen und es wird uneingeschränkter Zugriff über das Internet auf das Gerät ermöglicht.',
ids_router_startSameSubnet:'„Start-IP-Adresse“ und „IP-Adresse“ sollten zum selben Subnetz gehören.',
ids_btn_help:'Hilfe',
ids_menu_smsSettings:'SMS-Einstellung',
ids_profile_nameWarn:'Dieser Profilname existiert bereits.',
ids_wifi_wifiOffTime_10min:'10 Minuten',
ids_sim_newPinRule:'Der neue PIN-Code muss 4 bis 8 Ziffern umfassen.',
ids_sim_comfirmPinRule:'Die Bestätigungs-PIN muss 4 bis 8 Ziffern umfassen.',
ids_sim_enterValidCode:'Bitte geben Sie einen gültigen PIN-Code ein.',
ids_btn_send:'Senden',
ids_net_available:'Verfügbar',
ids_profile_numRule:'Hinweis: Sie können maximal 15 Profile erstellen.',
ids_gsm7_text:'GSM 7',
ids_dlg_sms_smsForwardNumEmpty:'Die Mobiltelefonnummer ist leer. Geben Sie die Nummer ein.',
ids_wifi_wepDescription:'Der WEP-Schlüssel besteht aus 5 oder 13 ASCII-Zeichen bzw. 10 oder 26 hexadezimalen Ziffern.',
ids_sd_sdCard:'Speicherkarte',
ids_sys_deviceName:'Gerätename',
ids_days:'Tage',
ids_sys_ipAddress:'IP-Adresse',
ids_login_nameOrPwdWrong:'Der Nutzername oder das Passwort ist falsch.',
ids_profile_userNameRule:'Der Benutzername darf maximal aus 31 Zeichen bestehen, ausgenommen: " : ; & .',
ids_wifi_cannotSet:'Diese Option kann nicht angewendet werden, weil WLAN derzeit deaktiviert ist.',
ids_router_ipAddrEmpty:'Die IP-Adresse ist leer. Geben Sie sie erneut ein.',
ids_wifi_pinDecription:'WPS-PIN (WPS-Einrichtung durch Eingabe eines bestimmten 8-stelligen Codes):</br>1. Falls mindestens ein Client mit dem Router verbunden ist, öffnen Sie den Browser auf dem verbundenen Gerät, rufen Sie http://192.168.0.1/ auf, geben Sie das Passwort ein und klicken Sie auf Mehr\\WPS. Geben Sie die WPS-PIN an.</br>2. Öffnen Sie auf dem Gerät, mit dem Sie den Router verbinden möchten (z. B. PC oder Smartphone) und das WPS unterstützt, das WLAN-Setup-Hilfsprogramm (erhalten Sie vom Händler dieses Geräts) und wählen Sie den WPS-PIN-Modus aus. Die 8-stellige WPS-PIN wird generiert.</br>3. Kehren Sie zur Weboberfläche des Routers zurück, geben Sie die 8-stellige WPS-PIN in das entsprechende Feld ein und klicken Sie auf Anwenden.</br>4. Die Verbindung zwischen dem Router und dem Client wird in ca. 2 Minuten automatisch hergestellt.',
ids_tr069_tips:'Wählen Sie die gewünschten Werte aus und klicken Sie auf „Anwenden/Speichern“, um die TR-069-Clientoptionen zu konfigurieren.',
ids_more_onlineUpdate:'Online-Update',
ids_security_btnAdd:'Hinzufügen',
ids_sms_autoForward:'SMS-Weiterleitung an das Mobiltelefon',
ids_sim_simLockCode:'SIM-Lock-Code',
ids_router_restartWarn:'Für diese Aktion müssen Sie das Gerät neustarten. Möchten Sie fortfahren?',
ids_sms_saveSimCard:'SIM-Karte',
ids_automatic:'Automatisch',
ids_security_portTips:'Hinweis: Definieren Sie den Port und die Portgruppe. Beispiel: 30 oder 65500-65510.',
ids_wifi_wpsNotSuppotSSIDHidden:'SSID ausgeblendet, WPS kann nicht festgelegt werden',
ids_netMode_Automatic3g2g:'Automatisch(3G & 2G)',
ids_wifi_apIsotation:'AP-Isolierung',
ids_security_portForwarding:'Port-Weiterleitung',
ids_btn_add:'Hinzufügen',
ids_usage_billingTimeTips:'Geben Sie einen Wert für den Tag von 1 bis 31 ein.',
ids_minutes:'Minuten',
ids_ussd_inputDescription:'Bitte geben USSD-Code',
ids_fota_upgrading:'Wird aktualisiert...',
ids_router_dhcpServer:'DHCP-Server',
ids_sim_pinRequiredTips:'Wählen Sie zum Erhalten weiterer Informationen zunächst PIN erforderlich aus, um das Gerät zu entsperren.',
ids_login_checkPwdRule:'Ungültiges Passwort. Das Anmeldepasswort darf maximal 16 Zeichen lang sein, einschließlich 0-9, a-z, A-Z,"-+!@$#^&*". Bitte geben Sie es erneut ein.',
ids_wifi_wifiOffTime:'WLAN zeitgesteuert ausschalten',
ids_sd_sdShareMode:'Modus Speicherkartenfreigabe',
ids_btn_continue:'Fortfahren',
ids_profile_protocal:'Protokoll',
ids_security_lanPort:'LAN-Port',
ids_dlg_sms_reInputCenterNum:'Die Nummer für die SMS-Zentrale ist ungültig. Versuchen Sie es erneut.',
ids_btn_backup:'Sichern',
ids_wan_connected_num:'Verbunden',
ids_sms_centerNum:'SMS-Center',
ids_fota_downloading:'Wird heruntergeladen...',
ids_wifi_wpaWpa2Psk:'WPA/WPA2 PSK',
ids_usage_of:'von',
ids_sys_rebootDecription:'Drücken Sie zum Neustarten des Geräts diese Taste.',
ids_title_about:'Info',
ids_sim_nck:'NCK',
ids_net_operator:'Betreiber',
ids_router_endIpEmpty:'Die End-IP-Adresse ist leer. Geben Sie sie erneut ein.',
ids_btn_cancel:'Abbrechen',
ids_dlg_pb_nameNullWarning:'Der Name darf nicht leer sein.',
ids_dlg_sms_inputCenterNum:'Die Nummer der SMS-Zentrale ist leer. Versuchen Sie es erneut.',
ids_ussd_rule:'Sie können nur Zahlen, * und # eingeben.',
ids_wifi_wifi:'WLAN',
ids_sms_selectSomeOptions:'Maximal 3 Kontakte',
ids_btn_new:'Neu',
ids_fota_findNewVersion:'Neue Version suchen',
ids_security_pfNumRule:'Hinweis: Sie können maximal 16 Port-Weiterleitungen erstellen.',
ids_wifi_showPwd:'Kennwort anzeigen',
ids_security_urlFilterList:'URL Filter Liste',
ids_loginTimeout:'Zeitüberschreitung bei der Anmeldung. Sie müssen sich erneut anmelden.',
ids_title_alternateDnsServer:'DNS Server wechseln',
ids_login_inputNewPwd:'Geben Sie das neue Kennwort ein.',
ids_fota_updateTitle:'Systemaktualisierungen',
ids_login_inputConfirmPwd:'Geben Sie das bestätigte Passwort ein.',
ids_hours:'Stunde(n)',
ids_wifi_maxUser:'Max. Benutzeranzahl',
ids_pb_addNew:'Hinzufügen',
ids_usage_timeLimit:'Zeitlimit',
ids_sim_pinCode:'PIN',
ids_wifi_wpaTkip:'TKIP',
ids_sim_autoPinState:'Aktueller Status',
ids_security_dmzTitle:'DMZ',
ids_security_dmzIpInvalid:'Die DMZ-IP-Adresse ist keine gültige IP-Adresse.',
ids_btn_unblock:'Blockierung aufheben',
ids_fota_checkUpdate:'Aktualisieren',
ids_title_advanced:'Erweiterte Einstellungen',
ids_security_ipFilterWarn:'Der IP-Filter ist bereits vorhanden.',
ids_fota_updateDescription:'Wählen Sie Aktualisieren aus, um die neue Version zu installieren.',
ids_btn_reset:'Zurücksetzen',
ids_tr069_acsUrlRule:'Format der ACS-URL: z.B.: http://ip address:port/xxx',
ids_show_again:'Diesen Hinweis nicht mehr anzeigen',
ids_usage_hrs:'Std',
ids_icon_battery:'Akku',
ids_sms_saveDevice:'Gerät',
ids_roamAppear:'Aktivieren Sie über den Schieberegler die Datennutzung während des Roamings. Informationen zu den geltenden Preisen erhalten Sie von Ihrem Netzwerkanbieter.',
ids_sys_chooseFile:'Datei wählen',
ids_btn_refresh:'Aktualisieren',
ids_pb_phoneBook:'Telefonbuch',
ids_net_select:'Netzauswahl',
ids_sim_pinError:'PIN-Fehler',
ids_sms_saveDraftFailed:'Speichern des Entwurfs fehlgeschlagen',
ids_sms_delivered:'Zugestellt',
ids_usage_autoDisconnected:'Verbindung automatisch getrennt',
ids_login_confirmPwd:'Passwort bestätigen',
ids_security_addMacAddress:'MAC-Adresse hinzufügen',
ids_sim_noSimCard:'Keine SIM-Karte',
ids_wifi_notSuppotWepWpa:'WPS ist nicht mit WEP, WPA, WPA2 TKIP verfügbar.',
ids_security_pfWarn:'Die Port-Weiterleitung ist bereits vorhanden.',
ids_fota_checking:'Überprüfung läuft…',
ids_dlg_pb_lenWarning:'Die Eingabe ist zu lang.',
ids_sim_newPinCode:'Neue PIN',
ids_sim_pinNotAvailable:'PIN-Code nicht verfügbar.',
ids_usage_clear:'Verlauf löschen',
ids_wifi_maxSsid:'Die SSID kann maximal aus 32 Zeichen bestehen, darunter 0-9, a-z, A-Z, „-“, „_“, „.“, „ “.',
ids_usage_startTimeTips:'Geben Sie einen Wert für die Daten von 0 bis 43200 ein.',
ids_wifi_pbcConfiguration:'Konfiguration auf Knopfdruck',
ids_usage_dataConsumption:'Datenverbrauch',
ids_disable:'Deaktivieren',
ids_ucs2Orgsm7_text:'UCS2 Or GSM7',
ids_login_loginPwd:'Anmeldekennwort',
ids_btn_save:'Speichern',
ids_wifi_802mode:'802.11-Modus',
ids_pb_phoneNumber:'Telefonnummer',
ids_ussd_timeOut:'Zeitüberschreitung Versuchen Sie es erneut.',
ids_btn_reboot:'Neustart',
ids_minute:'Minute',
ids_router_ipAddrInvalid:'Die IP-Adresse ist ungültig. Geben Sie sie erneut ein.',
ids_router_startIpEmpty:'Die Start-IP-Adresse ist leer. Geben Sie sie erneut ein.',
ids_sim_pinEnable:'Die automatische PIN-Überprüfung ist aktiviert.',
ids_sim_pinCodeOperation:'PIN-Code',
ids_security_dmzInvalidLanSubnet:'Die DMZ-IP-Adresse befindet sich nicht im LAN-Subnetz.',
ids_net_service:'Service',
ids_router_ipRule:'Fehler! Beachten Sie, dass die „10“ nach der eigenen Adresse die für das System reservierte IP darstellt. Sie darf nicht im DHCP-IP-Pool enthalten sein.',
ids_usage_roaming:'Roaming',
ids_title_ussd:'USSD',
ids_btn_ok:'OK',
ids_sys_resetDecription:'Auf Werkseinstellungen zurücksetzen.',
ids_tr069_inputInformInterval:'Bitte geben Sie vor dem Speichern das Zeitinterval für Benachrichtigungen ein.',
ids_security_dmzIpAddr:'DMZ-IP-Adresse',
ids_profile_inputApn:'Geben Sie den APN ein.',
ids_sys_restoreFactoryWarn:'Bei dieser Aktion werden die Werkseinstellungen wiederhergestellt, und das Gerät wird neugestartet. Möchten Sie fortfahren?',
ids_net_registing:'Registrierung wird durchgeführt...',
ids_sys_backupDecription:'Konfiguration herunterladen (sichern).',
ids_sms_selectAnOption:'Option auswählen',
ids_tr069_inputAcsUrl:'Bitte geben Sie die ACS-URL ein, bevor Sie speichern.',
ids_tr069_acsUsername:'ACS-Nutzername',
ids_pdpTimer_0seconds:'0 Sekunden',
ids_usage_home:'Heimnetz',
ids_profile_deleteWarn:'Möchten Sie das Profil wirklich löschen?',
ids_sms_smsFull:'Der SMS-Eingang ist voll. Löschen Sie einige SMS, um neue SMS senden und speichern zu können.',
ids_tr069_connRqPw:'Verbindungsanforderungs-Passwort',
ids_sim_pukError:'PUK-Fehler',
ids_sys_system:'System',
ids_security_PowerSavingSmart:'Smart',
ids_login_timeuseout:'Die Zeit zum Anmelden ist abgelaufen. Starten Sie das Gerät neu und versuchen Sie es erneut.',
ids_usage_minutesTimes:'Minute(n)',
ids_sim_pukRule:'Der PUK sollte aus 8 Ziffern bestehen.',
ids_net_3gOnly:'Nur 3G',
ids_sim_nsck:'NSCK',
ids_subnetMask:'Subnetzmaske',
ids_pdpTimer_60seconds:'60 Sekunden',
ids_sim_pinDisable:'Die automatische PIN-Überprüfung ist deaktiviert.',
ids_sys_macAddress:'MAC-Adresse',
ids_menu_connection:'Verbindung',
ids_dlg_pb_tooManyNumbers:'Wählen Sie zum Bearbeiten nur eine Nummer aus.',
ids_password:'Kennwort',
ids_security_virtualServer:'Virtueller Server (statische Port-Weiterleitung)',
ids_security_ipFilterDes:'Filtern Sie Pakete mithilfe der folgenden Regeln, die mit Protokoll, Port und IP-Adresse angegeben sind.',
ids_ussd_checkBlance:'Kontostand prüfen',
ids_title_tr069:'TR069',
ids_sms_draft:'Entwurf',
ids_wifi_encryption:'Verschlüsselung',
ids_title_ping:'Ping',
ids_foot_copyright:'Copyright 2016-2018 TCL COMMUNICATION LTD. ALLE RECHTE VORBEHALTEN.',
ids_tr069_acsPw:'ACS-Passwort',
ids_help_userManual:'Benutzerhandbuch',
ids_security_pfDescription:'Die Port-Weiterleitung ermöglicht externen Computern, auf WWW, FTP oder andere über das LAN bereitgestellte Dienste zuzugreifen.',
ids_wifi_notSuppotMacFilter:'WPS (Version 2.0) kann nicht aktiviert werden, falls der MAC-Adressfilter aktiv ist.',
ids_title_blockDevice:'Gerät sperren',
ids_router_endGeaterStart:'Die „End-IP-Adresse“ sollte länger sein als die „Start-IP-Adresse“.',
ids_net_2gOnly:'Nur 2G',
ids_clearCode_Twentynine:'Authentifizierungsfehler',
ids_usage_day:'Tag€',
ids_wifi_wepShare:'Shared',
ids_sms_messageSending:'SMS wird versendet',
ids_wan_roamingPopCloseConntectTips:'Daten-Roaming wird deaktiviert.',
ids_sd_currentFolder:'Aktueller Ordner',
ids_wan_disconnected:'Verbindung getrennt',
ids_security_numRule:'<b>Hinweis:</b> Sie können maximal 16 IP-Filter erstellen.',
ids_dns_manual_mode:'Manueller DNS Modus',
ids_login:'Anmelden',
ids_security_PowerSavingTitle:'Energiesparen',
ids_security_lanIpAddr:'LAN-IP-Adresse',
ids_menu_settings:'Einstellungen',
ids_wifi_disconWarning:'Bei dieser Aktion wird die WLAN-Verbindung deaktiviert. Möchten Sie dennoch fortfahren?',
ids_wifi_wpsActiveWarn:'Der WPS-Vorgang ist aktiv. Versuchen Sie es nach einigen Minuten erneut.',
ids_login_loginUserName:'Nutzername für die Anmeldung',
ids_wifi_wepWifiCertification:'Der WEP-Schlüssel besteht aus 5, 10, 13 oder 26 Ziffern.',
ids_connect:'Verbinden',
ids_btn_block:'Blockieren',
ids_pb_number:'Nr.',
ids_login_wrongPwd:'Falsches Passwort!',
ids_sms_smsForwarding:'SMS-Weiterleitung',
ids_sys_selectFilePrompt:'Wählen Sie vor dem Hochladen eine Datei aus.',
ids_wifi_wifiSecurity:'WLAN-Sicherheit',
ids_btn_edit:'Bearbeiten',
ids_security_firewallSwitch:'Firewall-Switch',
ids_router_endIP:'End-IP-Adresse',
ids_sys_imei:'IMEI',
ids_sim_remainTime:'Verbleibende Versuche',
ids_update_Confirm:'Die Datei wurde heruntergeladen. Möchten Sie nun updaten?',
ids_sim_pinConfirmed:'Die PIN zum Bestätigen muss mit der neuen PIN übereinstimmen.',
ids_filter_urlAddress:'URL Addresse',
ids_validate:'Überprüfen',
ids_security_subnetWarn:'LAN-IP-Adresse und IP-Adresse müssen zum selben Subnetz gehören.',
ids_sms_inputNum:'Geben Sie eine Mobiltelefonnummer ein.',
ids_tr069_informInterval:'Informationsintervall',
ids_fota_haveNewVersion:'Eine neue Software ist verfügbar. Aktualisieren Sie das Gerät.',
ids_sim_pukRequiredTips:'Wählen Sie zum Erhalten weiterer Informationen zunächst PUK erforderlich aus, um das Gerät zu entsperren.',
ids_sms_emptyMessageWarn:'Die Mitteilung ist leer. Möchten Sie diese leere Mitteilung wirklich senden?',
ids_sim_pck:'PCK',
ids_usage_clearHistory:'Möchten Sie wirklich alle Statistiken zurücksetzen?',
ids_hour:'Stunde',
ids_tr069_connRqAuth:'Authentifizierung für Verbindungs-Anfrage',
ids_wifi_off:'Aus',
ids_pb_storageStatus:'Speicherstatus',
ids_wan_connectedRule:'Diese Einstellung kann im verbundenen Modus nicht verwendet werden. Klicken Sie auf „Verbindung trennen“ und versuchen Sie es erneut.',
ids_menu_usage:'Nutzung',
ids_security_dmzDescription:'Kann ein Computer keine Netzwerkanwendungen über das Gateway ausführen, aktivieren Sie die DMZ-Funktion und geben Sie unten die IP-Adresse des Computers ein.',
ids_title_networkMode:'Netzmodus',
ids_wifi_wifiOffTime_5min:'5 Minuten',
ids_wifi_pbc:'PBC',
ids_error:'Fehler!',
ids_sim_changePinError:'Fehler beim Ändern der PIN',
ids_security_wanPort:'WAN-Port',
ids_security_ipFilter:'IP-Filter',
ids_tr069_inputConReqUserName:'Bitte geben Sie den Benutzernamen für die Verbindungsanfrage ein, bevor Sie speichern.',
ids_tr069_informIntervalRule:'Das Zeitinterval für Benachrichtigungen soll zwischen 0 und 2678400 liegen, einschließlich „0123456789“',
ids_login_newPwd:'Neues Kennwort',
ids_pdpTimer_10seconds:'10 Sekunden',
ids_security_virtualServerList:'Liste der virtuellen Server',
ids_security_urlAddrNameWarn:'Die URL-Adresse ist bereits vorhanden.',
ids_btn_select:'Auswählen',
ids_router_endSameSubnet:'„End-IP-Adresse“ und „IP-Adresse“ sollten zum selben Subnetz gehören.',
ids_ussd_CodeEmpty:'Das Eingabefeld darf nicht leer sein.',
ids_sim_autoPinError:'Fehler bei der automatischen PIN-Überprüfung',
ids_usage_cancelLimitTips:'Legen Sie das Datenlimit auf 0 fest und speichern Sie diese Einstellung, damit kein Datenlimit mehr gilt.',
ids_sim_simLocked:'SIM-Lock erforderlich',
ids_icon_timeElapsed:'Verstrichene Zeit',
ids_sms_sendingPrompt:'Versand läuft... Bitte warten.',
ids_tr069_inputAcsPassword:'Bitte geben Sie das ACS-Passwort ein, bevor Sie speichern.',
ids_requestError:'Keine Antwort. Die Verbindung zum Gerät wurde möglicherweise getrennt. Starten Sie das Gerät neu und versuchen Sie es erneut.',
ids_profile_inputRule:'Der Zugriffspunktname und die Rufnummer sollten aus 32 bis 127 ASCII-Zeichen bestehen, ausgenommen: " : ; & .',
ids_net_active:'Aktiv',
ids_sms_numberWarning:'Die Eingabe ist zu lang. Löschen Sie einige Buchstaben.',
ids_data:'Daten',
ids_pdpTimer:'PDP-Timer',
ids_menu_sharing:'Freigeben',
ids_sd_noSdCard:'Keine Speicherkarte',
ids_wifi_pbcDecription:'1. Falls kein Client mit dem Router verbunden ist, halten Sie die WPS-Taste am Router gedrückt und warten Sie, bis die WLAN-LED blinkt. Falls mindestens ein Client mit dem Router verbunden ist, öffnen Sie den Browser auf dem verbundenen Gerät, rufen Sie http://192.168.0.1/ auf, geben Sie das Passwort ein und klicken Sie auf Mehr\\WPS. Drücken Sie den WPS-Softkey.</br>2. Öffnen Sie auf dem Gerät, mit dem Sie den Router verbinden möchten (z. B. PC oder Smartphone) und das WPS unterstützt, das WLAN-Setup-Hilfsprogramm (erhalten Sie vom Händler dieses Geräts) und wählen Sie den PBC-Modus aus oder drücken Sie falls verfügbar die PBC-Taste (WPS) am Gerät.</br>3. Die Verbindung zwischen dem Router und dem Client wird in ca. 2 Minuten automatisch hergestellt.',
ids_sms_deleteSingleWarning:'Möchten Sie die Mitteilung(en) wirklich löschen?',
ids_menu_more:'Mehr',
ids_net_4gOnly:'Nur 4G',
ids_profileProtocal_none:'Keines',
ids_isSupportKickOff:'Andere Benutzer sind bereits angemeldet, möchten Sie sich trotzdem anmelden? Dadurch wird ein anderer Benutzer entfernt.',
ids_changePassword_Tips:'Der aktuelle Nutzername und das aktuelle Passwort sind standardmäßig eingestellt. Sie sollten das Passwort so ändern, dass Sie es sich leicht merken können. <a class="userpass_link">&nbsp;Klicken Sie hier&nbsp;</a>, um den Nutzernamen und das Passwort zu ändern.',
ids_wifi_wifiSleep:'WiFi Sleep',
ids_security_upnpDescription:'UPnP ermöglicht dem Gerät die Vernetzung mit anderen Geräten. Es handelt sich um ein verbreitetes, offenes Architekturprotokoll auf der Grundlage anerkannter Standards wie der Internet Protocol Suite (TCP/IP), HTTP, XML und SOAP.',
ids_sms_deleteAll:'Alle löschen',
ids_pb_location:'Ort',
ids_diagnostic:'Diagnose',
ids_security_macAddrInvalid:'Ungültige MAC-Adresse.',
ids_security_PowerSavingWiFiTips:'Die WLAN-Funktion wird automatisch ausgeschaltet, falls die Verbindung längere Zeit nicht aktiv war.',
ids_tr069_connRqUsername:'Verbindungsanforderungs-Nutzername',
ids_security_PowerSavingWiFi:'WLAN',
ids_profile_pwdRule:'Das Kennwort darf maximal aus 32 Zeichen bestehen, ausgenommen: " : ; &',
ids_tr069_inform:'Informieren',
ids_locked_permanently:'Dieses Gerät wurde dauerhaft gesperrt und kann nicht entsperrt werden.',
ids_sys_setRebootEvent:'Das Gerät startet neu. Warten Sie 60 Sekunden und stellen Sie anschließend erneut eine Verbindung zum WLAN-Gerät her.',
ids_sms_saveMode:'Speichermodus',
ids_pb_add:'Hinzufügen',
ids_sim_spck:'SPCK',
ids_security_upnp:'UPnP',
ids_sms_encodingoptimization:'SMS-Kodierungsoptimierung',
ids_profile_inputDialNum:'Geben Sie die Profilnummer ein.',
ids_dlg_pb_deleteWarning:'Wirklich löschen?',
ids_security_enableIp:'IP-Adressenfilter aktivieren',
ids_sms_mobileNum:'Mobiltelefonnummer',
ids_security_urlFilterTitle:'URL-Filter',
ids_btn_setDefault:'Standard&nbsp;festlegen',
ids_wan_connectedRuleIndia:'Bitte trennen Sie die Datenverbindung, bevor Sie die Profilverwaltung starten.',
ids_title_loginSettings:'Anmeldeeinstellungen',
ids_profile_apn:'APN',
ids_pb_local:'Lokal',
ids_wan_roamingAutoConnect:'Verbindung automatisch herstellen (auch beim Roaming)',
ids_wifi_key:'Schlüssel',
ids_login_userName:'admin',
ids_wifi_offRule:'WLAN ist derzeit deaktiviert, da längere Zeit kein Client verbunden war.  Aktivieren Sie das WLAN zur Verwendung manuell, indem Sie eine beliebige Taste am Gerät drücken.',
ids_allow:'Zulassen',
ids_usage_MB:'MB',
ids_sim_simLockedTips:'Wählen Sie zum Erhalten weiterer Informationen zunächst SIM-Lock erforderlich aus, um das Gerät zu entsperren.',
ids_login_inputOldPwd:'Geben Sie das alte Passwort ein.',
ids_icon_downloaded:'Heruntergeladen',
ids_sys_rebootWarn:'Möchten Sie das Gerät wirklich neustarten?',
ids_security_enableFirewall:'Firewall aktivieren',
ids_security_pfRangePortTip:'Die LAN-Portnummer entspricht nicht der WAN-Portnummer.',
ids_wifi_wepRule:'Der WEP-Schlüssel sollte aus ASCII-Zeichen zwischen 32 und 127 bestehen, ausgenommen: " : ; & .',
ids_sd_viewFile:'Datei anzeigen',
ids_icon_debit:'Soll',
ids_wifi_wpa2:'WPA2-PSK',
ids_sim_pinManagement:'PIN-Verwaltung',
ids_security_upnpStatus:'UPnP-Status',
ids_HelplineNumber:'Hotlinenummer:',
ids_login_confirmPwdRule:'Das neue Kennwort muss mit dem Kennwort zum Bestätigen übereinstimmen.',
ids_router_leaseTime:'DHCP-IP-Lease-Dauer',
ids_sd_usedTotal:'(Genutzt/insgesamt)',
ids_usage_monthlyDataPlan:'Monatlicher Datentarif',
ids_title_wps:'WPS',
ids_sms_newMessage:'Neue Mitteilung',
ids_auto:'AUTO',
ids_usage_setTimeLimit:'Zeitlimit festlegen',
ids_wifi_wep:'WEP',
ids_net_status:'Status',
ids_usage_minutes:'Minuten',
ids_wifi_wpsActive:'WPS aktiv.',
ids_menu_usageSetting:'Nutzungseinstellungen',
ids_login_otherLogin:'Der Administrator ist eingeloggt, Bitte versuchen Sie es später.',
ids_btn_wan_disconnect:'Verbindung trennen',
ids_tr069_inputAcsUserName:'Bitte geben Sie den ACS-Benutzernamen ein, bevor Sie speichern.',
ids_security_ipFilterList:'IP Filter Liste',
ids_wifi_on:'Ein',
ids_day:'Tag€',
ids_net_gsm:'2G',
ids_usage_notAccurate:'Die Statistiken sind möglicherweise nicht genau.',
ids_sim_pukRequired:'PUK erforderlich',
ids_security_ipOption:'Optionen',
ids_net_lte:'4G',
ids_router_subnetEmpty:'Sie Subnetzmaske ist leer. Geben Sie sie erneut ein.',
ids_pdpTimer_5seconds:'5 Sekunden',
ids_wan_roamingPopWarningMessage:'Klicken Sie auf <OK>, um Daten beim Roaming zu verwenden. Erkundigen Sie sich bei Ihrem Netzwerkanbieter nach Preisen',
ids_manual:'Manuell',
ids_menu_connectDevice:'Verbundene Geräte',
ids_profile_dialNumber:'Rufnummer',
ids_menu_sms:'SMS',
ids_sys_hwVersion:'Hardwareversion',
ids_usage_mothlyDataTips:'Geben Sie einen Wert für die Daten von 0 bis 1024 ein.',
ids_pdpTimer_90seconds:'90 Sekunden',
ids_title_macFilter:'MAC-Filter',
ids_netMode_Automatic4g3g2g:'Automatisch(4G & 3G & 2G)',
ids_sys_noFileChosen:'Keine ausgewählt',
ids_dlg_sms_mobileNumRule:'Geben Sie eine gültige Nummer ein: nur 0–9 und + sind zulässig, Leerzeichen und Sonderzeichen dürfen nicht verwendet werden.',
ids_wan_connecting:'Verbindung wird hergestellt...',
ids_profile_inputName:'Geben Sie vor dem Speichern der Profileinstellungen den Profilnamen ein.',
ids_wan_Block:'Die Liste der MAC-Adressen ist bereits voll. Diese Option kann nicht ausgeführt werden.',
ids_icon_people:'Kontakte',
ids_sim_autoValidate:'Automatische Eingabe',
ids_menu_language:'Sprache',
ids_wifi_wpsPinRule:'Die WPS-PIN sollte aus 4 bis 8 Ziffern bestehen.',
ids_title_pinCodeSettings:'PIN-Code-Einstellungen',
ids_net_searching:'Suche läuft...',
ids_wifi_wpaRule:'Der WPA-PSK sollte aus ASCII-Zeichen zwischen 32 und 127 bestehen, ausgenommen: " : ; & .',
ids_ussd_notSupport:'Nicht unterstützt Versuchen Sie es erneut.',
ids_tr069_acsUrl:'ACS-URL',
ids_sms_report:'SMS-Bericht',
ids_sim_cck:'CCK',
ids_security:'Sicherheit',
ids_enable:'Aktivieren',
ids_wifi_wpaAes:'AES',
ids_btn_next:'Weiter',
ids_profile_profileName:'Profilname',
ids_wifi_wepOpen:'OPEN',
ids_wan_connectIPMode:'Verbindung: IP-Modus',
ids_router_subnetInvalid:'Die Subnetzmaske ist ungültig. Geben Sie sie erneut ein.',
ids_pdpTimer_30seconds:'30 Sekunden',
ids_usage_min:'Min',
ids_wan_connected:'Verbunden'
}