var resourceInfo={
ids_fota_upgradingTips:'Μην απενεργοποιείτε τη συσκευή κατά τη διάρκεια της αναβάθμισης. Θα γίνει επανεκκίνηση της συσκευής μετά την αναβάθμιση.',
ids_usage_billingDay:'Ημέρα χρέωσης',
ids_sms_phoneNumberInvalid:'Ο αριθμός τηλεφώνου δεν είναι έγκυρος',
ids_btn_logout:'Αποσύνδεση',
ids_wifi_ssidBroadcast:'Μετάδοση SSID',
ids_wifi_wpaDescription:'Το WPA Pre-Shared Key (PSK) πρέπει να είναι 8-63 ASCII χαρακτήρες.',
ids_dlg_pb_nameRule:'Το όνομα δεν μπορεί να περιλαμβάνει τους παρακάτω χαρακτήρες:"\\","\\\'".',
ids_usage_GB:'GB',
ids_UserNameRule32:'Το μέγιστο μέγεθος του ονόματος πρόσβασης είναι 32, εκτός από: " : ; & .',
ids_pdpTimer_120seconds:'120 δευτερόλεπτα',
ids_profile_profileNameRule:'Το μέγιστο μέγεθος του ονόματος προφίλ είναι 31, εκτός από: , " : ; \\ & % + < > ?.',
ids_security_ipFilterDescription:'Το εύρος τιμών της θύρας είναι 0-65535.',
ids_back:'Πίσω',
ids_usage_dataUsageReach:'Όταν η χρήση δεδομένων εξαντλεί το μηνιαίο πρόγραμμα δεδομένων',
ids_router_startIpInvalid:'Η αρχική διεύθυνση IP είναι άκυρη. Παρακαλώ εισάγετε ξανά!',
ids_iptype:'Τύπος IP',
ids_net_selectWarn:'Παρακαλώ επιλέξτε δίκτυο!',
ids_login_inputCurrPwd:'Ο τρέχων κωδικός πρόσβασης είναι λανθασμένος.',
ids_sim_autoPin:'Αυτόματη επικύρωση κωδικού PIN',
ids_wifi_offTip:'Το Wi-Fi έχει απενεργοποιηθεί. Δοκιμάστε ξανά μετά την ενεργοποίηση του Wi-Fi.',
ids_net_3g4gOnly:'Μόνο 3G / 4G',
ids_wifi_wifiOffTime_30min:'30 λεπτά',
ids_fota_batteryTips:'Το επίπεδο της μπαταρίας είναι χαμηλό, δεν είναι δυνατή η αναβάθμιση της συσκευής',
ids_wifi_wpa:'WPA PSK',
ids_wifi_cipher:'Τύπος Cipher',
ids_sim_initializing:'Γίνεται προετοιμασία της SIM.',
ids_success:'Επιτυχής',
ids_sim_lockCodeRule:'Ο κωδικός κλειδώματος SIM πρέπει να είναι 10 ψηφία.',
ids_sim_pinRequired:'Απαιτείται PIN',
ids_router_endIpInvalid:'Η τελική διεύθυνση IP είναι άκυρη. Παρακαλώ εισάγετε ξανά!',
ids_security_macFilterDescription:'Έλεγχος και διαχείριση της συσκευής με πρόσβαση στο  WLAN (ενισχύει την ασφάλεια του WLAN).',
ids_net_lteOnlyVal:'Μόνο LTE',
ids_security_PowerSavingSmartTips:'Όλες οι ενδεικτικές λυχνίες LED εκτός από την ενδεικτική λυχνία LED ενεργοποίησης σβήνουν όταν δεν γίνει πρόσβαση στο Wi-Fi ή κάποια μη αυτόματη λειτουργία για διάστημα 30 δευτερολέπτων.',
ids_wan_tips:'Αποτυχία! Υπερχείλιση ιστορικού χρήσης, μπορείτε να κάνετε επαναφορά του μηνιαίου προγράμματος δεδομένων και να συνδεθείτε ξανά.',
ids_wan_roamingWarningMessage:'Η υπηρεσία Περιαγωγή δεδομένων σας επιτρέπει να περιηγείστε στο διαδίκτυο, να χρησιμοποιείτε μηνύματα ηλεκτρονικού ταχυδρομείου, MMS και άλλες υπηρεσίες δεδομένων ενώ βρίσκεστε στο εξωτερικό. Συμβουλευτείτε τον πάροχο δικτύου για τιμολόγηση',
ids_title_preferredDnsServer:'Preferred DNS Server',
ids_modify:'Τροποποίηση',
ids_title_connectMode:'Τρόπος σύνδεσης',
ids_net_noService:'Δεν υπάρχει υπηρεσία',
ids_net_2g3gOnly:'Μόνο 2G / 3G',
ids_sms_chatInputConfirm:'Παρακλούμε πιέστε ENTER για την ολοκλήρωση',
ids_sms_mobileNumRule:'Το μέγιστο μέγεθος του αριθμού τηλεφώνου είναι 20 ψηφία, συμπεριλαμβανομένων των +0123456789", παρακαλώ εισάγετε ξανά.',
ids_dlg_pb_NumberNullWarning:'Ο αριθμός τηλεφώνου δεν μπορεί να είναι κενός.',
ids_usage_hours:'Ώρες',
ids_usage_timePassed:'Υπέρβαση χρονικού ορίου',
ids_wifi_country:'Χώρα',
ids_wifi_wlan_mode:'Λειτουργία WLAN',
ids_net_umts:'3G',
ids_fail:'Απέτυχε!',
ids_wifi_wpsPin:'WPS PIN',
ids_wan_inputDeviceName:'εισαγάγετε όνομα συσκευής',
ids_sms_sendFail:'Η αποστολή του SMS απέτυχε',
ids_sim_pukCode:'Κώδικός PUK',
ids_sms_newMessageOn:'μη αναγνωσμένο από',
ids_tr069_inputConReqPassword:'Εισαγάγετε τον κωδικό πρόσβασης του αιτήματος σύνδεσης πριν το αποθηκεύσετε.',
ids_sys_swVersion:'Έκδοση λογισμικού',
ids_sim_simlockError:'Σφάλμα κλειδώματος SIM!',
ids_security_ipFilterPort:'Το εύρος τιμών της θύρας είναι 0-65535.',
ids_wifi_inputSsid:'Παρακαλώ εισάγετε το SSID.',
ids_clearCode_Thirtythree:'Δεν υπάρχουν δεδομένα υπηρεσιών',
ids_sim_confirmPinCode:'Κωδικός επιβεβαίωσης PIN',
ids_security_dmzStatus:'Κατάσταση DMZ',
ids_security_macAddrNameWarn:'Η διεύθυνση MAC υπάρχει ήδη.',
ids_security_portRule:'Το εύρος τιμών της θύρας είναι 1-65535.',
ids_router_startIP:'Έναρξη IP',
ids_fotaUpdate_openRoaming_meg:'Ενδέχεται να ισχύουν επιπλέον χρεώσεις για τη λήψη κατά την περιαγωγή, επικοινωνήστε με τον πάροχο δικτύου σας. Θέλετε να συνεχίσετε;',
ids_net_forbid:'Απογορευμένο',
ids_btn_loginTimeout:'επανεγγραφή',
ids_security_wanIpAddr:'Διεύθυνση IP WAN',
ids_profile_userName:'Όνομα χρήστη',
ids_profile_password:'Κωδικός πρόσβασης',
ids_btn_restore:'Επαναφορά',
ids_tips_livechat:'Συζήτηση σε πραγματικό χρόνο',
ids_login_inputPwd:'Εισαγάγετε τον κωδικό πρόσβασης.',
ids_login_inputUserName:'Εισαγάγετε το όνομα χρήστη.',
ids_pdpTimer_20seconds:'20 δευτερόλεπτα',
ids_btn_previous:'Προηγούμενο',
ids_sys_restoreBackupWarn:'Αυτή η ενέργεια θα ενημερώσει τις ρυθμίσεις και θα γίνει επανεκκίνηση της συσκευής όταν η φόρτωση θα ολοκληρωθεί. Είστε σίγουροι ότι θέλετε να συνεχίσετε;',
ids_security_ipLanWan:'Note: The value range of LAN/WAN Port is 0-65535 and 0 means any.',
ids_usage_KB:'KB',
ids_login_remenberPassword:'Απομνημόνευση κωδικού πρόσβασης',
ids_security_firewallDes:'Η σελίδα δίνει πληροφορίες πως θα ενεργοποιήσετε τις λειτουργίες φίλτρων του firewall. Οι λειτουργίες φίλτρων της διεύθυνσης IP είναι διαθέσιμες μόνο όταν είναι ενεργοποιημένο το firewall.',
ids_title_wifiSettings:'Ρυθμίσεις Wi-Fi',
ids_sim_invalidSimCard:'Άκυρη κάρτα SIM',
ids_sim_unknown:'Άγνωστο',
ids_wan_disconnecting:'Αποσύνδεση……',
ids_btn_delete:'Διαγραφή',
ids_tr069_client:'Συσκευή-πελάτης TR-069 – Διαμόρφωση',
ids_wifi_channel:'Κανάλι Wi-Fi',
ids_title_dnsSetting:'DNS',
ids_pb_name:'Όνομα',
ids_btn_apply:'Εφαρμογή',
ids_fota_latestVersion:'Έχετε ήδη την τελευταία έκδοση.',
ids_security_urlAddrInvalid:'Η διεύθυνση URL δεν είναι έγκυρη.',
ids_wan_cannotBlock:'Η ρύθμιση του φίλτρου Mac είναι "Να επιτρέπεται τώρα", δεν είναι δυνατή η επεξεργασία αυτής της επιλογής.',
ids_deny:'Απόρριψη',
ids_sms_saveDraftSuccess:'Το SMS αποθηκεύτηκε ως πρόχειρο',
ids_network_notAvailableFunctionWarn:'Παρακαλούμε όπως αποσυνδεθείτε από την υπηρεσία δεδομένων, πριν χρησιμοποιήσετε τις Ρυθμίσεις Προφίλ',
ids_usage_duration:'Διάρκεια',
ids_sim_rck:'RCK',
ids_sms_deleteWarning:'Είστε σίγουροι ότι θέλετε να διαγράψετε τα μηνύματα;',
ids_icon_uploaded:'Μεταφορτώσεις',
ids_orange_sim_pinOperationWarn:'Δεν μπορείτε να ενημερώσετε τις ρυθμίσεις κωδικού PIN ενώ είστε συνδεδεμένοι στο διαδίκτυο.',
ids_dlg_pb_mobileNumRule:'Η μέγιστη έκταση αριθμού τηλεφώνου είναι 40 ψηφία και θα πρέπει να περιλαμβάνει τους χαρακτήρες "+0123456789". Επαναλάβετε την εισαγωγή.',
ids_title_profilesManagement:'Διαχείριση προφίλ',
ids_wifi_wifiOffTime_20min:'20 λεπτά',
ids_sim_lockForbidden:'Το κλείδωμα SIM απαγορεύεται!',
ids_sim_pinRule:'Ο κώδικός PIN πρέπει να είναι 4-8 ψηφία.',
ids_security_dmzTips:'Το DMZ επιτρέπει στην επιλεγμένη συσκευή να παρακάμπτει τις λειτουργίες τείχους προστασίας της πύλης και καθιστά δυνατή την απεριόριστη πρόσβαση από το διαδίκτυο σε αυτή τη συσκευή.',
ids_router_startSameSubnet:'Η αρχική διεύθυνση IP και η διεύθυνση IP πρέπει να ανήκουν στο ίδιο υποδίκτυο.',
ids_btn_help:'Βοήθεια',
ids_menu_smsSettings:'Ρυθμίσεις SMS',
ids_profile_nameWarn:'Το όνομα προφίλ υπάρχει ήδη.',
ids_wifi_wifiOffTime_10min:'10 λεπτά',
ids_sim_newPinRule:'Ο νέος κωδικός PIN θα πρέπει να αποτελείται τουλάχιστον από 4-8 ψηφία.',
ids_sim_comfirmPinRule:'Ο κωδικός PIN επιβεβαίωσης θα πρέπει να αποτελείται τουλάχιστον από 4-8 ψηφία.',
ids_sim_enterValidCode:'Εισαγάγετε έναν έγκυρο κωδικό PIN.',
ids_btn_send:'Αποστολή',
ids_net_available:'Διαθέσιμο',
ids_profile_numRule:'Σημείωση: Ο μέγιστος αριθμός προφίλ που μπορείτε να δημιουργήσετε είναι 15.',
ids_gsm7_text:'GSM 7',
ids_dlg_sms_smsForwardNumEmpty:'Ο αριθμός κινητού τηλεφώνου είναι κενός. Εισαγάγετε τον αριθμό.',
ids_wifi_wepDescription:'Το Wep Key είναι 5 ή 13 ASCII χαρακτήρες, είτε 10 ή 26 δεκαεξαδικά ψηφία.',
ids_sd_sdCard:'Κάρτα SD',
ids_sys_deviceName:'Όνομα συσκευής',
ids_days:'Ημέρες',
ids_sys_ipAddress:'IP Address',
ids_login_nameOrPwdWrong:'Το όνομα χρήστη ή ο κωδικός πρόσβασης είναι λανθασμένα!',
ids_profile_userNameRule:'Το μέγιστο μέγεθος του ονόματος πρόσβασης είναι 31, εκτός από: " : ; & .',
ids_wifi_cannotSet:'Το Wi-Fi είναι απενεργοποιημένο τώρα, δεν μπορεί να γίνει επεξεργασία της επιλογής.',
ids_router_ipAddrEmpty:'Η διεύθυνση IP είναι κενή. Παρακαλώ εισάγετε ξανά!',
ids_wifi_pinDecription:'WPS PIN (ρύθμιση WPS με εισαγωγή του ειδικού 8ψήφιου κωδικού):<br/>1. Εάν τουλάχιστον μία συσκευή-πελάτης είναι συνδεδεμένη στο δρομολογητή, ανοίξτε ένα πρόγραμμα περιήγησης σε μια συνδεδεμένη συσκευή και μεταβείτε στη διεύθυνση http://192.168.0.1/, εισαγάγετε τον κωδικό πρόσβασής σας και κάντε κλικ στην επιλογή Περισσότερα> WPS. Επιλέξτε WPS PIN.<br/>2. Στη συσκευή που θέλετε να συνδέσετε στο δρομολογητή (π.χ. υπολογιστή ή smartphone) ανοίξτε το βοηθητικό πρόγραμμα ρύθμισης Wi-Fi το οποίο υποστηρίζει WPS (παρέχεται από τον προμηθευτή αυτής της συσκευής) και επιλέξτε λειτουργία WPS PIN. Θα δημιουργηθεί ένας 8ψήφιος κωδικός WPS PIN.<br/>3. Επιστρέψτε στη διεπαφή web του δρομολογητή, εισαγάγετε τον 8ψήφιο κωδικό WPS PIN στο πεδίο WPS PIN και κάντε κλικ στην επιλογή "Εφαρμογή".<br/>4. Η σύνδεση μεταξύ του δρομολογητή και της συσκευής-πελάτη θα πραγματοποιηθεί αυτόματα σε περίπου 2 λεπτά.',
ids_tr069_tips:'Επιλέξτε τις τιμές που επιθυμείτε και κάντε κλικ στην επιλογή “Εφαρμογή/Αποθήκευση” για να διαμορφώσετε τις επιλογές της συσκευής-πελάτη TR-069.',
ids_more_onlineUpdate:'Ενημέρωση μέσω διαδικτύου',
ids_security_btnAdd:'Προσθήκη',
ids_sms_autoForward:'Προώθηση SMS σε κινητό τηλέφωνο',
ids_sim_simLockCode:'Κωδικός κλειδώματος SIM',
ids_router_restartWarn:'Αυτή η ενέργεια απαίτει να γίνει επανεκκίνηση της συσκευής. Είστε σίγουροι ότι θέλετε να συνεχίσετε;',
ids_sms_saveSimCard:'Κάρτα SIM',
ids_automatic:'Αυτόματο',
ids_security_portTips:'Σημείωση: Καθορίστε την πύλη και την ομάδα της πύλης, για παράδειγμα, 30 ή 65500-65510.',
ids_wifi_wpsNotSuppotSSIDHidden:'Το SSID είναι κρυφό, δεν είναι δυνατός ο ορισμός WPS.',
ids_netMode_Automatic3g2g:'Αυτόματο(3G & 2G)',
ids_wifi_apIsotation:'AP Isolation',
ids_security_portForwarding:'Προώθηση πύλης',
ids_btn_add:'Προσθήκη',
ids_usage_billingTimeTips:'Εισαγάγετε μια ημέρα μεταξύ 1-31.',
ids_minutes:'Λεπτά',
ids_ussd_inputDescription:'Εισαγάγετε τον κωδικό USSD',
ids_fota_upgrading:'Γίνεται αναβάθμιση…',
ids_router_dhcpServer:'DHCP Server',
ids_sim_pinRequiredTips:'Για περισσότερες πληροφορίες, κάντε κλικ στην επιλογή "Απαιτείται PIN" για να ξεκλειδώσετε πρώτα τη συσκευή.',
ids_login_checkPwdRule:'Άκυρος κωδικός πρόσβασης! Το μέγεθος του κωδικού είναι 4-16, συμπεραλαμβανομένων των 0-9, a-z, A-Z,"-+!@$#^&*", παρακαλώ εισάγετε ξανά.',
ids_wifi_wifiOffTime:'Χρόνος απενεργοποίησης Wi-Fi',
ids_sd_sdShareMode:'Λειτουργία κοινής χρήσης SD',
ids_btn_continue:'Συνέχεια',
ids_profile_protocal:'Πρωτόκολλο',
ids_security_lanPort:'LAN Port',
ids_dlg_sms_reInputCenterNum:'Ο αριθμός κέντρου SMS είναι άκυρος. Παρακαλώ εισάγετε αριθμο!',
ids_btn_backup:'Αντίγραφο ασφαλείας',
ids_wan_connected_num:'Συνδεδεμένο',
ids_sms_centerNum:'Κέντρο SMS',
ids_fota_downloading:'Λήψη...',
ids_wifi_wpaWpa2Psk:'WPA/WPA2 PSK',
ids_usage_of:'από',
ids_sys_rebootDecription:'Πατήστε αυτό το πλήκτρο για επανεκκίνση της συσκευής.',
ids_title_about:'Πληροφορίες',
ids_sim_nck:'NCK',
ids_net_operator:'Πάροχος',
ids_router_endIpEmpty:'Η τελική διεύθυνση IP είναι κενή. Παρακαλώ εισάγετε ξανά!',
ids_btn_cancel:'Ακύρωση',
ids_dlg_pb_nameNullWarning:'Το όνομα δεν μπορεί να είναι κενό.',
ids_dlg_sms_inputCenterNum:'Ο αριθμός κέντρου SMS είναι κενός. Παρακαλώ εισάγετε αριθμο!',
ids_ussd_rule:'Μπορείτε να εισάγετε μόνο χαρακτήρες "*" "#" και αριθμούς.',
ids_wifi_wifi:'WiFi',
ids_sms_selectSomeOptions:'3 επαφές το πολύ',
ids_btn_new:'Νέο',
ids_fota_findNewVersion:'Εύρεση νέας έκδοσης',
ids_security_pfNumRule:'Σημείωση: Ο μέγιστος αριθμός προωθήσεων πύλης που μπορείτε να δημιουργήσετε είναι 16.',
ids_wifi_showPwd:'Εμφάνιση κωδικού πρόσβασης',
ids_security_urlFilterList:'URL Filter List',
ids_loginTimeout:'Λήξη χρονικού ορίου σύνδεσης. Συνδεθείτε ξανά.',
ids_title_alternateDnsServer:'Alternate DNS Server',
ids_login_inputNewPwd:'Παρακαλώ εισάγετε νέο κωδικό πρόσβασης.',
ids_fota_updateTitle:'Ενημερώσεις συστήματος',
ids_login_inputConfirmPwd:'Παρακαλώ εισάγετε νέο κωδικό επιβεβαίωσης.',
ids_hours:'Ώρες',
ids_wifi_maxUser:'Μέγιστος αριθμός χρηστών',
ids_pb_addNew:'Προσθήκη',
ids_usage_timeLimit:'Χρονικό όριο',
ids_sim_pinCode:'Κωδικός PIN',
ids_wifi_wpaTkip:'TKIP',
ids_sim_autoPinState:'Κατάσταση δικτύου',
ids_security_dmzTitle:'DMZ',
ids_security_dmzIpInvalid:'DMZ IP-adress är inte en giltig IP-adress.',
ids_btn_unblock:'Κατάργηση αποκλεισμού',
ids_fota_checkUpdate:'Ενημέρωση',
ids_title_advanced:'Ειδικές ρυθμίσεις',
ids_security_ipFilterWarn:'Το φίλτρο IP υπάρχει ήδη.',
ids_fota_updateDescription:'Κάντε κλικ στην επιλογή "Ενημέρωση" για να κάνετε ενημέρωση στη νέα έκδοση.',
ids_btn_reset:'Επαναφορά',
ids_tr069_acsUrlRule:'Μορφή url Acs: π.χ.:http://ip address:port/xxx',
ids_show_again:'Να μην εμφανιστεί ξανά αυτό το μήνυμα',
ids_usage_hrs:'Ώρες',
ids_icon_battery:'Μπαταρία',
ids_sms_saveDevice:'Συσκευή',
ids_roamAppear:'Σύρετε για να χρησιμοποιείτε δεδομένα κατά την περιαγωγή. Επικοινωνήστε με τον πάροχο δικτύου για να ενημερωθείτε σχετικά με την τιμολόγηση.',
ids_sys_chooseFile:'Επιλογή αρχείου',
ids_btn_refresh:'Ανανέωση',
ids_pb_phoneBook:'Τηλεφωνικός κατάλογος',
ids_net_select:'Επιλογή δικτύου',
ids_sim_pinError:'Σφάλμα κωδικού PIN!',
ids_sms_saveDraftFailed:'Αποτυχία αποθήκευσης προχείρου',
ids_sms_delivered:'Παραδόθηκε',
ids_usage_autoDisconnected:'Έγινε αυτόματη αποσύνδεση',
ids_login_confirmPwd:'Επιβεβαίωση κωδικού πρόσβασης',
ids_security_addMacAddress:'Προσθήκη διεύθυνσης MAC',
ids_sim_noSimCard:'Δεν υπάρχει κάρτα SIM',
ids_wifi_notSuppotWepWpa:'Το WPS δεν είναι διαθέσιμο με WEP, WPA, WPA2 TKIP!',
ids_security_pfWarn:'Η προώθηση πύλης υπάρχει ήδη.',
ids_fota_checking:'Έλεγχος…',
ids_dlg_pb_lenWarning:'Το μέγεθος της εισαγωγής είναι πολύ μεγάλο',
ids_sim_newPinCode:'Νέος κωδικός PIN',
ids_sim_pinNotAvailable:'Ο κώδικός PIN δεν είναι διαθέσιμος.',
ids_usage_clear:'Διαγραφή ιστορικού',
ids_wifi_maxSsid:'Το μέγιστο μέγεθος του SSID είναι 32 χαρακτήρες, συμπεριλαμβανομένων των 0-9, a-z, A-Z, "-", "_", "." ," ".',
ids_usage_startTimeTips:'Εισαγάγετε δεδομένα μεταξύ 1-43200.',
ids_wifi_pbcConfiguration:'Push Button Configuration',
ids_usage_dataConsumption:'Κατανάλωση δεδομένων',
ids_disable:'Απενεργοποίηση',
ids_ucs2Orgsm7_text:'UCS2 Or GSM7',
ids_login_loginPwd:'Κωδικός σύνδεσης',
ids_btn_save:'Αποθήκευση',
ids_wifi_802mode:'Λειτουργία 802.11',
ids_pb_phoneNumber:'Αριθμός τηλεφώνου',
ids_ussd_timeOut:'Λήξη χρονικού ορίου! Δοκιμάστε ξανά.',
ids_btn_reboot:'Επανεκκίνηση',
ids_minute:'Λεπτό',
ids_router_ipAddrInvalid:'Η διεύθυνση IP είναι άκυρη. Παρακαλώ εισάγετε ξανά!',
ids_router_startIpEmpty:'Η αρχική διεύθυνση IP είναι κενή. Παρακαλώ εισάγετε ξανά!',
ids_sim_pinEnable:'Η αυτόματη επικύρωση κωδικού PIN έχει ενεργοποιηθεί.',
ids_sim_pinCodeOperation:'Χειρισμός κωδικού PIN',
ids_security_dmzInvalidLanSubnet:'DMZ IP-adress är inte på LAN-subnätet.',
ids_net_service:'Υπηρεσία',
ids_router_ipRule:'Σφάλμα!',
ids_usage_roaming:'Περιαγωγή',
ids_title_ussd:'USSD',
ids_btn_ok:'OK',
ids_sys_resetDecription:'Επαναφορά εργοστασιακών ρυθμίσεων',
ids_tr069_inputInformInterval:'Εισαγάγετε το διάστημα ενημέρωσης πριν το αποθηκεύσετε.',
ids_security_dmzIpAddr:'DMZ διεύθυνση IP',
ids_profile_inputApn:'Παρακαλώ εισάγετε APN!',
ids_sys_restoreFactoryWarn:'Αυτή η ενέργεια θα επαναφέρει τις ρυθμίσεις και θα γίνει επανεκκίνηση της συσκευής. Είστε σίγουροι ότι θέλετε να συνεχίσετε;',
ids_net_registing:'Εγγραφή…',
ids_sys_backupDecription:'Λήψη(αντιγραφο ασφαλειας) διαμόρφωσης',
ids_sms_selectAnOption:'Ορίστε μια επιλογή',
ids_tr069_inputAcsUrl:'Εισαγάγετε το url acs πριν το αποθηκεύσετε.',
ids_tr069_acsUsername:'Όνομα χρήστη ACS',
ids_pdpTimer_0seconds:'0 δευτερόλεπτο',
ids_usage_home:'Αρχική οθόνη',
ids_profile_deleteWarn:'Είστε σίγουροι ότι θέλετε να το διαγράψετε;',
ids_sms_smsFull:'Ο χώρος των SMS είναι πλήρης, παρακαλω διαγράψτε κάποια SMS για να μπορείτε να αποστείλετε/αποθηκεύσετε νέα SMS.',
ids_tr069_connRqPw:'Κωδικός πρόσβασης αιτήματος σύνδεσης',
ids_sim_pukError:'Σφάλμα κωδικού PUK!',
ids_sys_system:'Σύστημα',
ids_security_PowerSavingSmart:'Έξυπνη',
ids_login_timeuseout:'Ο αριθμός συνδέσεων εξαντλήθηκε. Κάντε επανεκκίνηση και δοκιμάστε ξανά.',
ids_usage_minutesTimes:'λεπτό/ά',
ids_sim_pukRule:'Ο κώδικός PUK πρέπει να είναι 4-8 ψηφία.',
ids_net_3gOnly:'Μόνο 3G',
ids_sim_nsck:'NSCK',
ids_subnetMask:'Subnet Mask',
ids_pdpTimer_60seconds:'60 δευτερόλεπτα',
ids_sim_pinDisable:'Η αυτόματη επικύρωση κωδικού PIN έχει απενεργοποιηθεί.',
ids_sys_macAddress:'MAC Address',
ids_menu_connection:'Σύνδεση',
ids_dlg_pb_tooManyNumbers:'Για να ξεκινήσετε την επεξεργασία, επιλέξτε μόνο έναν αριθμό.',
ids_password:'Κωδικός πρόσβασης',
ids_security_virtualServer:'Εικονικός διακομιστής (προώθηση στατικής πύλης)',
ids_security_ipFilterDes:'Τα πακέτα φίλτρων χρησιμοποιούν τους ακόλουθους κανόνες με πρωτόκολλα, port και διεύθυνση IP.',
ids_ussd_checkBlance:'Έλεγχος υπολοίπου',
ids_title_tr069:'TR069',
ids_sms_draft:'Πρόχειρο',
ids_wifi_encryption:'Κρυπτογράφηση',
ids_title_ping:'Ping',
ids_foot_copyright:'Πνευματικά δικαιώματα 2016-2018 TCL Communication Ltd. ΜΕ την επιφύλαξη παντός δικαιώματος.',
ids_tr069_acsPw:'Κωδικός πρόσβασης ACS',
ids_help_userManual:'Εγχειρίδιο χρήστη',
ids_security_pfDescription:'Η προώθηση πύλης επιτρέπει σε εξωτερικούς υπολογιστές να αποκτήσουν πρόσβαση σε πρωτόκολλα WWW, FTP ή άλλες υπηρεσίες που παρέχονται από το LAN.',
ids_wifi_notSuppotMacFilter:'Η διαδικασία WPS (2.0 έκδοση) δεν μπορεί να ενεργοποιηθεί αν το φίλτρο του MAC address είναι ενεργοποιημένο',
ids_title_blockDevice:'Αποκλεισμός συσκευής',
ids_router_endGeaterStart:'Η τελική διεύθυνση IP πρέπει να είναι μεγαλύτετη από την αρχική διεύθυνση IP.',
ids_net_2gOnly:'Μόνο 2G',
ids_clearCode_Twentynine:'Αποτυχία ελέγχου ταυτότητας',
ids_usage_day:'Ημέρα',
ids_wifi_wepShare:'Μοίρασμα',
ids_sms_messageSending:'Γίνεται αποστολή ενός SMS',
ids_wan_roamingPopCloseConntectTips:'Η περιαγωγή δεδομένων θα απενεργοποιηθεί.',
ids_sd_currentFolder:'Τρέχων φάκελος',
ids_wan_disconnected:'Αποσυνδεδεμένο',
ids_security_numRule:'<b>Σημείωση:</b>Ο μέγιστος αριθμός φίλτρων IP που μπορείτε να δημιουργήσετε είναι 16.',
ids_dns_manual_mode:'DNS manual mode',
ids_login:'Σύνδεση',
ids_security_PowerSavingTitle:'Εξοικονόμηση ενέργειας',
ids_security_lanIpAddr:'Διεύθυνση IP LAN',
ids_menu_settings:'Ρυθμίσεις',
ids_wifi_disconWarning:'Αυτή η ενέργεια να αποσυνδέσει το Wi-Fi. Είστε σίγουροι ότι θέλετε να συνεχίσετε;',
ids_wifi_wpsActiveWarn:'Η διαδικασία WPS είναι σε εξέλιξη. Παρακαλώ δοκιμάστε ξανά μετα από 2 λεπτά!',
ids_login_loginUserName:'Όνομα χρήστη σύνδεσης',
ids_wifi_wepWifiCertification:'Οι τιμές του κλειδιού WEP είναι 5 ή 13 ή 10 ή 26.',
ids_connect:'Σύνδεση',
ids_btn_block:'Αποκλεισμός',
ids_pb_number:'ΟΧΙ.',
ids_login_wrongPwd:'Λάθος κώδικός πρόσβασης!',
ids_sms_smsForwarding:'Προώθηση SMS',
ids_sys_selectFilePrompt:'Παρακαλώ επιλέξτε ένα αρχείο πρίν την φόρτωση.',
ids_wifi_wifiSecurity:'Ασφάλεια Wi-Fi',
ids_btn_edit:'Επεξεργασία',
ids_security_firewallSwitch:'Εναλλαγή firewall',
ids_router_endIP:'Λήξη IP',
ids_sys_imei:'IMEI',
ids_sim_remainTime:'Υπολοιπόμενες προσπάθειες',
ids_update_Confirm:'Το αρχείο έχει ληφθεί, είστε σίγουροι ότι θέλετε να γίνει ενημέρωση;',
ids_sim_pinConfirmed:'Ο κωδικός επιβεβαίωσης PIN πρέπει να είναι ο ίδιος με τον νέο κωδικό PIN.',
ids_filter_urlAddress:'URL Address',
ids_validate:'Επικύρωση',
ids_security_subnetWarn:'Η διεύθυνση IP LAN και η "Διεύθυνση IP" θα πρέπει να ανήκουν στο ίδιο υποδίκτυο.',
ids_sms_inputNum:'Παρακαλώ εισάγετε ένα αριθμό τηλεφώνου.',
ids_tr069_informInterval:'Διάστημα/διαστήματα ενημέρωσης',
ids_fota_haveNewVersion:'Μια νέα έκδοση λογισμικού είναι διαθέσιμη, κάντε κλικ για να εγκαταστήσετε την ενημέρωση.',
ids_sim_pukRequiredTips:'Για περισσότερες πληροφορίες, κάντε κλικ στην επιλογή "Απαιτείται PUK" για να ξεκλειδώσετε πρώτα τη συσκευή.',
ids_sms_emptyMessageWarn:'Το μήνυμα είναι κενό. Είστε βέβαιοι ότι θέλετε να στείλετε αυτό το κενό μήνυμα;',
ids_sim_pck:'PCK',
ids_usage_clearHistory:'Είστε βέβαιοι ότι θέλετε να γίνει επαναφορά όλων των στατιστικών στοιχείων;',
ids_hour:'Ώρα',
ids_tr069_connRqAuth:'Έλεγχος ταυτότητας αιτήματος σύνδεσης',
ids_wifi_off:'Off',
ids_pb_storageStatus:'Κατάσταση χώρου αποθήκευσης',
ids_wan_connectedRule:'Δεν είναι δυνατή η χρήση αυτής της ρύθμισης στη συνδεδεμένη λειτουργία. Επιλέξτε “Αποσύνδεση” και δοκιμάστε ξανά.',
ids_menu_usage:'Χρήση',
ids_security_dmzDescription:'Αν το PC δεν μπορεί να εκτελέσει εφαρμογές δικτύου μέσω πύλης , ενεργοποιήστε την λειτουργία DMZ και εισάγετε την διεύθυνση IP του παρακάτω PC.',
ids_title_networkMode:'Λειτουργία δικτύου',
ids_wifi_wifiOffTime_5min:'5 λεπτά',
ids_wifi_pbc:'PBC',
ids_error:'Σφάλμα',
ids_sim_changePinError:'Σφάλμα αλλαγής κωδικού PIN!',
ids_security_wanPort:'WAN Port',
ids_security_ipFilter:'Φίλτρο IP',
ids_tr069_inputConReqUserName:'Εισαγάγετε το όνομα χρήστη του αιτήματος σύνδεσης πριν το αποθηκεύσετε.',
ids_tr069_informIntervalRule:'Το διάστημα πληροφόρησης θα πρέπει να είναι μεταξύ 0-2678400 και να περιλαμβάνει τους χαρακτήρες "0123456789".',
ids_login_newPwd:'Νέος κωδικός πρόσβασης',
ids_pdpTimer_10seconds:'10 δευτερόλεπτα',
ids_security_virtualServerList:'Λίστα εικονικών διακομιστών',
ids_security_urlAddrNameWarn:'Η διεύθυνση URL υπάρχει ήδη.',
ids_btn_select:'Επιλογή',
ids_router_endSameSubnet:'Η τελική διεύθυνση IP και η διεύθυνση IP πρέπει να ανήκουν στο ίδιο υποδίκτυο.',
ids_ussd_CodeEmpty:'Το πλαίσιο εισαγωγής δεν μπορεί να είναι κενό!',
ids_sim_autoPinError:'Σφάλμα αυτόματης επικύρωσης κωδικού PIN!',
ids_usage_cancelLimitTips:'Ρυθμίστε το όριο δεδομένων στο 0 και αποθηκεύστε το για να ακυρώσετε τα όρια δεδομένων.',
ids_sim_simLocked:'Απαιτείται κλείδωμα SIM',
ids_icon_timeElapsed:'Παρέλευση χρόνου',
ids_sms_sendingPrompt:'Αποστολή……, παρακαλώ περιμένετε!',
ids_tr069_inputAcsPassword:'Εισαγάγετε τον κωδικό πρόσβασης acs πριν το αποθηκεύσετε.',
ids_requestError:'Δεν ανταποκρίνεται, η συσκευή μπορεί να αποσυνδέθηκε, παρακαλώ επανεκκινήστε τη συσκευή και δοκιμάστε ξανά.',
ids_profile_inputRule:'Το APN & ο αριθμός κλήσης πρέπει να είναι με ASCII χαρακτήρες που κυμαίνονται από 32-127, εκτός από: " : ; & .',
ids_net_active:'Ενεργό',
ids_sms_numberWarning:'Το μέγεθος της εισαγωγής είναι πολύ μεγάλο. Διαγράψτε ορισμένα.',
ids_data:'Δεδομένα',
ids_pdpTimer:'Χρονόμετρο PDP',
ids_menu_sharing:'Μοίρασμα',
ids_sd_noSdCard:'Δεν υπάρχει κάρτα SD',
ids_wifi_pbcDecription:'1. Εάν δεν συνδεθεί κάποια συσκευή-πελάτης στο δρομολογητή, πιέστε παρατεταμένα το κουμπί WPS στο δρομολογητή και περιμένετε έως ότου αρχίσει να αναβοσβήνει η λυχνία LED Wi-Fi. Εάν τουλάχιστον μία συσκευή-πελάτης είναι συνδεδεμένη στο δρομολογητή, ανοίξτε ένα πρόγραμμα περιήγησης σε μια συνδεδεμένη συσκευή και μεταβείτε στη διεύθυνση http://192.168.0.1/, εισαγάγετε τον κωδικό πρόσβασής σας και κάντε κλικ στην επιλογή Περισσότερα> WPS. Πατήστε το προγραμματιζόμενο κουμπί WPS.<br/>2. Στη συσκευή που θέλετε να συνδέσετε στο δρομολογητή (π.χ. υπολογιστή ή smartphone) ανοίξτε το βοηθητικό πρόγραμμα ρύθμισης Wi-Fi το οποίο υποστηρίζει WPS (παρέχεται από τον προμηθευτή αυτής της συσκευής) και επιλέξτε λειτουργία PBC ή πατήστε το κουμπί PBC (WPS) στη συσκευή, εφόσον υπάρχει.<br/>3. Η σύνδεση μεταξύ του δρομολογητή και της συσκευής-πελάτη θα πραγματοποιηθεί αυτόματα σε περίπου 2 λεπτά.',
ids_sms_deleteSingleWarning:'Είστε σίγουροι ότι θέλετε να διαγράψετε τα μηνύματα;',
ids_menu_more:'Περισσότερα',
ids_net_4gOnly:'Μόνο 4G',
ids_profileProtocal_none:'None',
ids_isSupportKickOff:'Ένας άλλος χρήστης έχει ήδη συνδεθεί, θέλετε να συνεχίσετε? Αυτό θα αποσυνδέσει τον προηγούμενο χρήστη.',
ids_changePassword_Tips:'Το τρέχον όνομα χρήστη και ο κωδικός πρόσβασης αποτελούν την προεπιλεγμένη ρύθμιση, συνιστούμε να αλλάξετε τον κωδικό πρόσβασής σας σε έναν που μπορείτε να απομνημονεύσετε εύκολα. <a class="userpass_link">&nbsp;Κάντε κλικ εδώ&nbsp;</a> για να αλλάξετε το όνομα χρήστη και τον κωδικό πρόσβασης.',
ids_wifi_wifiSleep:'WiFi Sleep',
ids_security_upnpDescription:'Το UPnP επιτρέπει στη συσκευή τη σύνδεση με άλλες συσκευές. Είναι ένα διανεμημένο πρωτόκολλο ανοικτής αρχιτεκτονικής που βασίζεται σε καθιερωμένα πρότυπα όπως Internet Protocol Suite (TCP/IP), HTTP, XML και SOAP.',
ids_sms_deleteAll:'Διαγραφή όλων',
ids_pb_location:'Τοποθεσία',
ids_diagnostic:'Διαγνωστικός έλεγχος',
ids_security_macAddrInvalid:'H MAC address είναι άκυρη.',
ids_security_PowerSavingWiFiTips:'Το Wi-Fi θα απενεργοποιηθεί αυτόματα εάν η σύνδεση είναι αδρανής για μεγάλο διάστημα.',
ids_tr069_connRqUsername:'Όνομα χρήστη αιτήματος σύνδεσης',
ids_security_PowerSavingWiFi:'Wi-Fi',
ids_profile_pwdRule:'Το μέγιστο μέγεθος του κώδικού πρόσβασης είναι 31,εκτός από: " : ; & .',
ids_tr069_inform:'Ενημέρωση',
ids_locked_permanently:'Αυτή η συσκευή έχει κλειδωθεί μόνιμα και δεν μπορεί να ξεκλειδωθεί!',
ids_sys_setRebootEvent:'Η συσκευή κάνει επανεκκίνηση, παρακαλώ περιμένετε 60 δευτ., έπειτα συνδεθείτε με την συσκευή Wi-Fi.',
ids_sms_saveMode:'Τρόπος αποθήκευσης',
ids_pb_add:'Προσθήκη',
ids_sim_spck:'SPCK',
ids_security_upnp:'UPnP',
ids_sms_encodingoptimization:'Βελτιστοποίηση κωδικοποίησης SMS',
ids_profile_inputDialNum:'Παρακαλώ εισάγετε αριθμό κλήσης!',
ids_dlg_pb_deleteWarning:'Είστε βέβαιοι ότι επιθυμείτε να γίνει διαγραφή;',
ids_security_enableIp:'Ενεργοποίηση φίλτρου διεύθυνσης IP',
ids_sms_mobileNum:'Αριθμός κινητού τηλεφώνου',
ids_security_urlFilterTitle:'Φίλτρο URL',
ids_btn_setDefault:'Ορισμός προεπιλογής',
ids_wan_connectedRuleIndia:'Παρακαλούμε όπως αποσυνδεθείτε από την υπηρεσία δεδομένων, πριν χρησιμοποιήσετε τις Ρυθμίσεις Προφίλ',
ids_title_loginSettings:'Ρυθμίσεις σύνδεσης',
ids_profile_apn:'APN',
ids_pb_local:'Τοπικό',
ids_wan_roamingAutoConnect:'Αυτόματη σύνδεση όταν υπάρχει περιαγωγή.',
ids_wifi_key:'Key',
ids_login_userName:'διαχειριστής',
ids_wifi_offRule:'Το Wi-Fi είναι απενεργοποιημένο αυτή τη στιγμή, καθώς δεν συνδέθηκε καμία συσκευή-πελάτης για μεγάλο διάστημα.  Ενεργοποιήστε μη αυτόματα το Wi-Fi πατώντας οποιοδήποτε κουμπί στη συσκευή, εάν θέλετε να χρησιμοποιήσετε το Wi-Fi.',
ids_allow:'Αποδοχή',
ids_usage_MB:'MB',
ids_sim_simLockedTips:'Για περισσότερες πληροφορίες, κάντε κλικ στην επιλογή "Απαιτείται κλείδωμα SIM" για να ξεκλειδώσετε πρώτα τη συσκευή.',
ids_login_inputOldPwd:'Εισαγάγετε τον προηγούμενο κωδικό πρόσβασης.',
ids_icon_downloaded:'Λήψεις',
ids_sys_rebootWarn:'Είστε σίγουροι ότι θέλετε να επανεκκινήσετε τη συσκευή;',
ids_security_enableFirewall:'Ενεργοποίηση firewall',
ids_security_pfRangePortTip:'Ο αριθμός πύλης LAN δεν είναι ο ίδιος με τον αριθμό πύλης WAN!',
ids_wifi_wepRule:'Το WEP Key πρέπει να είναι ASCII χαρακτήρες που κυμαίνοναι από 32-127, εκτός από: " : ; & .',
ids_sd_viewFile:'Προβολή αρχείου',
ids_icon_debit:'Χρέωση',
ids_wifi_wpa2:'WPA2 PSK',
ids_sim_pinManagement:'Διαχείριση κωδικού PIN',
ids_security_upnpStatus:'Κατάσταση UPnP',
ids_HelplineNumber:'Αριθμός γραμμής βοήθειας:',
ids_login_confirmPwdRule:'Ο νέος κωδικός πρόσβασης δεν είναι ο ίδιος με το κωδικό επιβεβαίωσης.',
ids_router_leaseTime:'DHCP IP Lease Time',
ids_sd_usedTotal:'(Χρησιμοποιούμενος/Συνολικός)',
ids_usage_monthlyDataPlan:'Μηνιαίο πρόγραμμα δεδομένων',
ids_title_wps:'WPS',
ids_sms_newMessage:'Νέο μήνυμα',
ids_auto:'AUTO',
ids_usage_setTimeLimit:'Ορισμός χρονικού ορίου',
ids_wifi_wep:'WEP',
ids_net_status:'Κατάσταση',
ids_usage_minutes:'Λεπτά',
ids_wifi_wpsActive:'Το WPS είναι ενεργό.',
ids_menu_usageSetting:'Ρυθμίσεις χρήσης',
ids_login_otherLogin:'Ο διαχειριστής έχει συνδεθεί, Παρακαλώ δοκιμάστε αργότερα.',
ids_btn_wan_disconnect:'Αποσύνδεση',
ids_tr069_inputAcsUserName:'Εισαγάγετε το όνομα χρήστη acs πριν το αποθηκεύσετε.',
ids_security_ipFilterList:'IP Filter List',
ids_wifi_on:'On',
ids_day:'Ημέρα',
ids_net_gsm:'2G',
ids_usage_notAccurate:'Τα στατιστικά στοιχεία ενδέχεται να μην είναι ακριβή.',
ids_sim_pukRequired:'Απαιτείται PUK',
ids_security_ipOption:'Επιλογές',
ids_net_lte:'4G',
ids_router_subnetEmpty:'Η subnet Mask είναι κενή. Παρακαλώ εισάγετε ξανά!',
ids_pdpTimer_5seconds:'5 δευτερόλεπτα',
ids_wan_roamingPopWarningMessage:'Κάντε κλικ στο <OK> για να χρησιμοποιήσετε δεδομένα κατά την περιαγωγή. Συμβουλευτείτε τον πάροχο δικτύου για τιμολόγηση',
ids_manual:'Χειροκίνητο',
ids_menu_connectDevice:'Συνδεμένες συσκευές',
ids_profile_dialNumber:'Αριθμός κλήσης',
ids_menu_sms:'SMS',
ids_sys_hwVersion:'Έκδοση hardware',
ids_usage_mothlyDataTips:'Εισαγάγετε δεδομένα μεταξύ 1-1024.',
ids_pdpTimer_90seconds:'90 δευτερόλεπτα',
ids_title_macFilter:'MAC Filter',
ids_netMode_Automatic4g3g2g:'Αυτόματο(4G & 3G & 2G)',
ids_sys_noFileChosen:'Δεν έχει επιλεγεί αρχείο',
ids_dlg_sms_mobileNumRule:'Εισαγάγετε έναν έγκυρο αριθμό: Χρησιμοποιήστε μόνο τους χαρακτήρες 0-9 και "+", χωρίς κενά ή ειδικούς χαρακτήρες.',
ids_wan_connecting:'Σύνδεση…….',
ids_profile_inputName:'Παρακαλώ εισάγετε το όνομα προφίλ προτού το αποθηκέυσετε.',
ids_wan_Block:'Η λίστα διευθύνσεων MAC είναι ήδη πλήρης, δεν είναι δυνατή η επεξεργασία αυτής της επιλογής.',
ids_icon_people:'Άτομα',
ids_sim_autoValidate:'Αυτόματη επικύρωση',
ids_menu_language:'Γλώσσα',
ids_wifi_wpsPinRule:'Ο κωδικός PIN WPS πρέπει να είναι 4 ή 8 ψηφία.',
ids_title_pinCodeSettings:'Ρυθμίσεις κωδικού PIN',
ids_net_searching:'Αναζήτηση…',
ids_wifi_wpaRule:'Το WPA PSK πρέπει να είναι ASCII χαρακτήρες που κυμαίνοναι από 32-127, εκτός από: " : ; & .',
ids_ussd_notSupport:'Δεν υποστηρίζεται! Δοκιμάστε ξανά.',
ids_tr069_acsUrl:'URL ACS',
ids_sms_report:'Αναφορά SMS',
ids_sim_cck:'CCK',
ids_security:'Ασφάλεια',
ids_enable:'Ενεργοποίηση',
ids_wifi_wpaAes:'AES',
ids_btn_next:'Επόμενο',
ids_profile_profileName:'Όνομα προφίλ',
ids_wifi_wepOpen:'Άνοιγμα',
ids_wan_connectIPMode:'Λειτουργία σύνδεσης IP',
ids_router_subnetInvalid:'Η subnet Mask είναι άκυρη. Παρακαλώ εισάγετε ξανά!',
ids_pdpTimer_30seconds:'30 δευτερόλεπτα',
ids_usage_min:'Ελάχιστο',
ids_wan_connected:'Συνδεδεμένο'
}