var resourceInfo={
ids_fota_upgradingTips:'Non spegnere durante l\'aggiornamento. Il dispositivo verrà riavviato dopo l\'aggiornamento.',
ids_usage_billingDay:'Giorno fatturazione',
ids_sms_phoneNumberInvalid:'Numero di telefono non valido',
ids_btn_logout:'Disconnetti',
ids_wifi_ssidBroadcast:'Trasmissione SSID',
ids_wifi_wpaDescription:'La chiave WPA-PSK (Pre-Shared Key) deve contenere tra 8 e 63 caratteri ASCII o 64 cifre esadecimali.',
ids_dlg_pb_nameRule:'Il nome non può includere i seguenti caratteri: "\\\\", "\\".',
ids_usage_GB:'GB',
ids_UserNameRule32:'La lunghezza massima del nome utente è 32 caratteri, ad eccezione di: " : ; & .',
ids_pdpTimer_120seconds:'120 secondi',
ids_profile_profileNameRule:'La lunghezza massima del nome profilo è 31 caratteri, ad eccezione di: , " : ; \\ & % + < > ?.',
ids_security_ipFilterDescription:'L’intervallo di valori del Port è 0-65535',
ids_back:'Indietro',
ids_usage_dataUsageReach:'Quando il traffico dati raggiunge il tetto mensile',
ids_router_startIpInvalid:'L\'indirizzo IP iniziale non è valido. Digitarlo di nuovo.',
ids_iptype:'Tipo IP',
ids_net_selectWarn:'Selezionare una rete.',
ids_login_inputCurrPwd:'La password corrente è errata.',
ids_sim_autoPin:'Convalida automatica codice PIN',
ids_wifi_offTip:'WiFi disabilitato, riprovare dopo averlo riattivato.',
ids_net_3g4gOnly:'Solo 3G / 4G',
ids_wifi_wifiOffTime_30min:'30 minuti',
ids_fota_batteryTips:'Livello batteria troppo basso per aggiornare il dispositivo',
ids_wifi_wpa:'WPA-PSK',
ids_wifi_cipher:'Tipo di crittografia',
ids_sim_initializing:'Inizializzazione SIM',
ids_success:'Operazione riuscita',
ids_sim_lockCodeRule:'Il codice SIM Lock deve essere composto da 10 cifre.',
ids_sim_pinRequired:'PIN necessario',
ids_router_endIpInvalid:'L\'indirizzo IP finale non è valido. Digitarlo di nuovo.',
ids_security_macFilterDescription:'Consente la gestione del dispositivo tramite connessione Wi-Fi e ne migliora la sicurezza.',
ids_net_lteOnlyVal:'Solo LTE',
ids_security_PowerSavingSmartTips:'Tutte le spie LED si spengono automaticamente, tranne la spia LED Accensione, quando non è presente una connessione Wi-Fi o non si effettuano operazioni manuali entro 30 secondi.',
ids_wan_tips:'Fallito! Azzerare piano dati mensile e riconnettere.',
ids_wan_roamingWarningMessage:'Il roaming dati consente di navigare sul Web, utilizzare e-mail, MMS e altri servizi di dati all\'estero. Verificare con il proprio operatore di rete per i prezzi',
ids_title_preferredDnsServer:'Server DNS preferito',
ids_modify:'Modifica',
ids_title_connectMode:'Modalità di connessione',
ids_net_noService:'Nessun servizio',
ids_net_2g3gOnly:'Solo 2G/3G',
ids_sms_chatInputConfirm:'Premere Invio per completare',
ids_sms_mobileNumRule:'La lunghezza massima per un numero di cellulare è di 20 cifre, compresi i caratteri "+0123456789". Immettere nuovamente il numero.',
ids_dlg_pb_NumberNullWarning:'Il campo numero di telefono non deve essere vuoto',
ids_usage_hours:'ore',
ids_usage_timePassed:'Tempo trascorso',
ids_wifi_country:'Paese',
ids_wifi_wlan_mode:'Modalità Wlan',
ids_net_umts:'3G',
ids_fail:'Operazione non riuscita!',
ids_wifi_wpsPin:'PIN WPS',
ids_wan_inputDeviceName:'immettere nome dispositivo',
ids_sms_sendFail:'Invio SMS non riuscito',
ids_sim_pukCode:'PUK',
ids_sms_newMessageOn:'non letto di',
ids_tr069_inputConReqPassword:'Immettere password richiesta di connessione prima di salvare',
ids_sys_swVersion:'Versione software',
ids_sim_simlockError:'Errore blocco SIM.',
ids_security_ipFilterPort:'L’intervallo di valori del Port è 0-65535',
ids_wifi_inputSsid:'Immettere il SSID.',
ids_clearCode_Thirtythree:'Nessun servizio dati',
ids_sim_confirmPinCode:'Conferma PIN',
ids_security_dmzStatus:'stato DMZ',
ids_security_macAddrNameWarn:'Indirizzo MAC già esistente.',
ids_security_portRule:'L\'intervallo di valori della porta è 1-65535.',
ids_router_startIP:'IP iniziale',
ids_fotaUpdate_openRoaming_meg:'Sono possibili ulteriori addebiti per il download in roaming. Verificare con l\'operatore. Continuare?',
ids_net_forbid:'Non consentito',
ids_btn_loginTimeout:'registrare di nuovo',
ids_security_wanIpAddr:'Indirizzo IP WAN',
ids_profile_userName:'Nome utente',
ids_profile_password:'Password',
ids_btn_restore:'ripristina',
ids_tips_livechat:'Chat live',
ids_login_inputPwd:'Immettere la password.',
ids_login_inputUserName:'Immettere il nome utente.',
ids_pdpTimer_20seconds:'20 secondi',
ids_btn_previous:'Precedente',
ids_sys_restoreBackupWarn:'Questa azione aggiornerà le impostazioni e riavvierà il dispositivo al termine del caricamento; continuare?',
ids_security_ipLanWan:'Nota: l’intervallo valori di Port LAN/WAN è 0-65535 e 0 significa qualunque',
ids_usage_KB:'KB',
ids_login_remenberPassword:'Ricorda password',
ids_security_firewallDes:'In questa pagina sono riportate le informazioni relative all\'attivazione delle funzioni di filtro del firewall. Le funzioni di filtro dell\'indirizzo IP sono disponibili solo quando il firewall è attivato.',
ids_title_wifiSettings:'Impostazioni Wi-Fi',
ids_sim_invalidSimCard:'Scheda SIM non valida',
ids_sim_unknown:'sconosciuto',
ids_wan_disconnecting:'Disconnessione in corso…',
ids_btn_delete:'Elimina',
ids_tr069_client:'Client TR-069 – Configurazione',
ids_wifi_channel:'Canale Wi-Fi',
ids_title_dnsSetting:'DNS',
ids_pb_name:'Nome',
ids_btn_apply:'Applica',
ids_fota_latestVersion:'Questa è già la versione più recente.',
ids_security_urlAddrInvalid:'Indirizzo URL non valido.',
ids_wan_cannotBlock:'Il Filtro MAC è Permetti ora, non è possibile processare questa opzione.',
ids_deny:'Rifiuta',
ids_sms_saveDraftSuccess:'SMS salvato come bozza',
ids_network_notAvailableFunctionWarn:'Disconnettere la connessione dati prima di iniziare la gestione del profilo',
ids_usage_duration:'Durata',
ids_sim_rck:'RCK',
ids_sms_deleteWarning:'Elimina SMS?',
ids_icon_uploaded:'Caricati',
ids_orange_sim_pinOperationWarn:'Impossibile agriornare impostaz PIN durante la connessione ad internet.',
ids_dlg_pb_mobileNumRule:'La lunghezza massima del numero di cellulare è 40 cifre, che comprendono "+0123456789". Immetterlo di nuovo.',
ids_title_profilesManagement:'Gestione profilo',
ids_wifi_wifiOffTime_20min:'20 minuti',
ids_sim_lockForbidden:'Blocco Sim non consentito!',
ids_sim_pinRule:'Il codice PIN deve essere compreso tra 4 e 8 cifre.',
ids_security_dmzTips:'DMZ consente al dispositivo selezionato di superare le funzioni del firewall del gateway, consentendo un accesso illimitato da Internet al dispositivo stesso.',
ids_router_startSameSubnet:'L\'indirizzo IP iniziale e l\'indirizzo IP devono appartenere alla stessa sottorete.',
ids_btn_help:'Guida',
ids_menu_smsSettings:'Impostazioni SMS',
ids_profile_nameWarn:'Nome profilo già esistente.',
ids_wifi_wifiOffTime_10min:'10 minuti',
ids_sim_newPinRule:'Il nuovo codice PIN deve essere composto da 4-8 cifre.',
ids_sim_comfirmPinRule:'Il codice PIN di conferma deve essere composto da 4-8 cifre.',
ids_sim_enterValidCode:'Inserire un PIN valido.',
ids_btn_send:'Invia',
ids_net_available:'Disponibile',
ids_profile_numRule:'Nota: il numero massimo di profili che è possibile creare è 15.',
ids_gsm7_text:'GSM 7',
ids_dlg_sms_smsForwardNumEmpty:'Numero di cellulare è vuoto. Immettere il numero.',
ids_wifi_wepDescription:'La chiave WEP è composta da 5 o 13 caratteri ASCII oppure da 10 o 26 cifre esadecimali.',
ids_sd_sdCard:'SD Card',
ids_sys_deviceName:'Nome dispositivo',
ids_days:'giorni',
ids_sys_ipAddress:'Indirizzo IP',
ids_login_nameOrPwdWrong:'Nome utente o password errati',
ids_profile_userNameRule:'La lunghezza massima del nome utente è 31 caratteri, ad eccezione di: " : ; & .',
ids_wifi_cannotSet:'La rete Wi-Fi è attualmente disattivata, di conseguenza non è possibile eseguire l\'operazione.',
ids_router_ipAddrEmpty:'Il campo Indirizzo IP è vuoto. Digitarlo di nuovo !',
ids_wifi_pinDecription:'PIN WPS (configurazione WPS con l\'inserimento di un codice speciale a 8 caratteri):</br>1. Se al router è collegato almeno un client, aprire il browser sul dispositivo collegato e accedere alla pagina http://192.168.0.1/, inserire la password e fare clic su Altro > WPS. Selezionare PIN WPS.</br>2. Sul dispositivo che si desidera collegare al router (es. PC o smartphone), aprire la Utility di configurazione Wi-Fi compatibile con il WPS (che deve essere fornita dal venditore del dispositivo) e selezionare la modalità PIN WPS. Viene generato un PIN WPS a 8 caratteri.</br>3. Tornare all\'interfaccia Web del router, inserire il PIN WPS a 8 caratteri nel campo PIN WPS e fare clic su Applica.</br>4. Il collegamento tra il router e il client viene instaurato automaticamente in 2 minuti circa.',
ids_tr069_tips:'Selezionare i valori desiderati e fare clic su "Applica/Salva" per configurare le opzioni del client TR-069.',
ids_more_onlineUpdate:'Aggiornamento online',
ids_security_btnAdd:'Aggiungi',
ids_sms_autoForward:'Inoltro di SMS al telefono cellulare',
ids_sim_simLockCode:'Codice blocco SIM',
ids_router_restartWarn:'Questa azione richiede il riavvio del dispositivo, continuare?',
ids_sms_saveSimCard:'scheda SIM',
ids_automatic:'Automatica',
ids_security_portTips:'Nota: specificare la porta e il gruppo di porte, ad esempio: 30 o 65500-65510.',
ids_wifi_wpsNotSuppotSSIDHidden:'SSID nascosta, WPS non disponibile.',
ids_netMode_Automatic3g2g:'Automatico(3G & 2G)',
ids_wifi_apIsotation:'Isolamento AP',
ids_security_portForwarding:'Port Forwarding',
ids_btn_add:'Aggiungi',
ids_usage_billingTimeTips:'Immettere il giorno compreso tra 1-31.',
ids_minutes:'minuti',
ids_ussd_inputDescription:'Si prega di codice di ingresso USSD',
ids_fota_upgrading:'Aggiornamento in corso...',
ids_router_dhcpServer:'Server DHCP',
ids_sim_pinRequiredTips:'Per ulteriori informazioni, prima fare clic su "PIN necessario" per sbloccare.',
ids_login_checkPwdRule:'Password non valida. La password di accesso deve contenere 4-16 caratteri, compresi 0-9, a-z, A-Z e i caratteri speciali "-+!@$#^&*". Ripetere l\\',
ids_wifi_wifiOffTime:'Ora di spegnimento Wi-Fi',
ids_sd_sdShareMode:'Modo condividi SD',
ids_btn_continue:'Continua',
ids_profile_protocal:'Autenticazione',
ids_security_lanPort:'Porta LAN',
ids_dlg_sms_reInputCenterNum:'Il numero del centro SMS non è valido. Riprovare.',
ids_btn_backup:'esegui',
ids_wan_connected_num:'Connesso',
ids_sms_centerNum:'Centro SMS',
ids_fota_downloading:'Download in corso…',
ids_wifi_wpaWpa2Psk:'WPA/WPA2 PSK',
ids_usage_of:'di',
ids_sys_rebootDecription:'Fare clic su questo pulsante per riavviare il dispositivo.',
ids_title_about:'Informazioni',
ids_sim_nck:'NCK',
ids_net_operator:'Operatore',
ids_router_endIpEmpty:'Il campo Indirizzo IP finale è vuoto. Digitarlo di nuovo.',
ids_btn_cancel:'Annulla',
ids_dlg_pb_nameNullWarning:'Il campo nome non deve esserse vuoto',
ids_dlg_sms_inputCenterNum:'Il numero del centro SMS è vuoto. Riprovare.',
ids_ussd_rule:'Possono essere inseriti solo “*”“#”e numeri.',
ids_wifi_wifi:'Wi-Fi',
ids_sms_selectSomeOptions:'3 contatti al massimo',
ids_btn_new:'Nuovo',
ids_fota_findNewVersion:'Trova nuova versione',
ids_security_pfNumRule:'Nota: è possibile creare fino a un massimo di 16 Inoltri porte.',
ids_wifi_showPwd:'Mostra password',
ids_security_urlFilterList:'Lista filtro URL',
ids_loginTimeout:'Accesso scaduto. È necessario accedere nuovamente',
ids_title_alternateDnsServer:'Server DNS alternativo',
ids_login_inputNewPwd:'Immettere la nuova password.',
ids_fota_updateTitle:'Aggiornamenti sistema',
ids_login_inputConfirmPwd:'Introduzca la contraseña confirmada.',
ids_hours:'ore',
ids_wifi_maxUser:'Numero massimo di utenti',
ids_pb_addNew:'Aggiungi',
ids_usage_timeLimit:'Limite orario',
ids_sim_pinCode:'PIN',
ids_wifi_wpaTkip:'TKIP',
ids_sim_autoPinState:'Stato corrente',
ids_security_dmzTitle:'DMZ',
ids_security_dmzIpInvalid:'L\'indirizzo IP DMZ non è un indirizzo IP valido.',
ids_btn_unblock:'Sblocca',
ids_fota_checkUpdate:'Aggiorna',
ids_title_advanced:'Impostazione avanzata',
ids_security_ipFilterWarn:'Il filtro IP esiste già.',
ids_fota_updateDescription:'fare clic su "Aggiorna" per aggiornare alla nuova versione.',
ids_btn_reset:'Reimposta',
ids_tr069_acsUrlRule:'Formato ACS url: eg:http://ip address:port/xxx',
ids_show_again:'Non mostrare più',
ids_usage_hrs:'Hrs',
ids_icon_battery:'Batteria',
ids_sms_saveDevice:'Dispositivo',
ids_roamAppear:'Scorrere per utilizzare i dati durante il roaming. Verificare i costi con il provider di rete.',
ids_sys_chooseFile:'Scegli file',
ids_btn_refresh:'Aggiorna',
ids_pb_phoneBook:'Rubrica',
ids_net_select:'Selezione rete',
ids_sim_pinError:'Errore PIN.',
ids_sms_saveDraftFailed:'Salvataggio bozza non riuscito',
ids_sms_delivered:'Consegnato',
ids_usage_autoDisconnected:'Disconnessione automatica',
ids_login_confirmPwd:'Conferma password',
ids_security_addMacAddress:'Aggiungi indirizzo MAC',
ids_sim_noSimCard:'Nessuna scheda SIM',
ids_wifi_notSuppotWepWpa:'WPS non disponibile in WEP, WPA, WPA2 TKIP!',
ids_security_pfWarn:'Il Port Forwarding esiste già.',
ids_fota_checking:'Controllo in corso…',
ids_dlg_pb_lenWarning:'L\'input è troppo lungo',
ids_sim_newPinCode:'Nuovo PIN',
ids_sim_pinNotAvailable:'Codice PIN non disponibile.',
ids_usage_clear:'Cancella cronologia',
ids_wifi_maxSsid:'La lunghezza massima per il codice SSID è di  32 caratteri, inclusi numeri da 0 a 9, lettera da "a" a "z" (maiuscole e minuscole) e i seguenti simboli: "-", "_", ".", " ".',
ids_usage_startTimeTips:'Immettere i dati compresi tra 1-43200.',
ids_wifi_pbcConfiguration:'Configurazione',
ids_usage_dataConsumption:'Consumo dati',
ids_disable:'Disabilita',
ids_ucs2Orgsm7_text:'UCS2 Or GSM7',
ids_login_loginPwd:'Password di accesso',
ids_btn_save:'Salva',
ids_wifi_802mode:'Modalità 802.11',
ids_pb_phoneNumber:'Numero di telefono',
ids_ussd_timeOut:'Tempo scaduto! Fare Click su indietro per riprovare.',
ids_btn_reboot:'Riavvia',
ids_minute:'minuto',
ids_router_ipAddrInvalid:'L\'indirizzo IP non è valido. Digitarlo di nuovo !',
ids_router_startIpEmpty:'Il campo Indirizzo IP iniziale è vuoto. Digitarlo di nuovo.',
ids_sim_pinEnable:'Convalida automatica PIN attivata.',
ids_sim_pinCodeOperation:'Operazione codice PIN',
ids_security_dmzInvalidLanSubnet:'L\'indirizzo IP DMZ non si trova nella subnet LAN.',
ids_net_service:'Servizio',
ids_router_ipRule:'Errore. Attenzione: il numero 10 dopo l\'indirizzo Home (Home address) rappresenta l\'IP preriservato di sistema e non è possibile includerlo nel DHCP IP Pool.',
ids_usage_roaming:'Roaming',
ids_title_ussd:'USSD',
ids_btn_ok:'OK',
ids_sys_resetDecription:'Reimposta i valori predefiniti.',
ids_tr069_inputInformInterval:'Immettere intervallo prima di salvare',
ids_security_dmzIpAddr:'indirizzo DMZ IP',
ids_profile_inputApn:'Immettere l\'APN.',
ids_sys_restoreFactoryWarn:'Questa azione riporterà le impostazioni sui valori predefiniti e riavvierà il dispositivo; continuare?',
ids_net_registing:'Registrazione in corso…',
ids_sys_backupDecription:'Scarica (esegui backup) la configurazione.',
ids_sms_selectAnOption:'Seleziona un\'opzione',
ids_tr069_inputAcsUrl:'Immettere ACS URL prima di salvare',
ids_tr069_acsUsername:'Nome utente ACS',
ids_pdpTimer_0seconds:'0 secondi',
ids_usage_home:'Home',
ids_profile_deleteWarn:'Confermate di volerlo cancellare?',
ids_sms_smsFull:'La casella SMS è piena. Eliminare alcuni SMS per inviarne/salvarne di nuovi.',
ids_tr069_connRqPw:'Password richiesta di connessione',
ids_sim_pukError:'Errore PUK.',
ids_sys_system:'Sistema',
ids_security_PowerSavingSmart:'Smart',
ids_login_timeuseout:'Tentativi di accesso terminati. Riavviare e riprovare.',
ids_usage_minutesTimes:'min.',
ids_sim_pukRule:'Il codice PUK deve essere composto da 8 cifre.',
ids_net_3gOnly:'Solo 3G',
ids_sim_nsck:'NSCK',
ids_subnetMask:'Subnet mask',
ids_pdpTimer_60seconds:'60 secondi',
ids_sim_pinDisable:'Convalida automatica PIN disattivata.',
ids_sys_macAddress:'Indirizzo MAC',
ids_menu_connection:'Connessione',
ids_dlg_pb_tooManyNumbers:'Per cominciare a modificare selezionare solo un numero',
ids_password:'Password',
ids_security_virtualServer:'Server virtuale (port forwarding statico)',
ids_security_ipFilterDes:'Filtrare i pacchetti in base a protocollo, porta e indirizzo IP, secondo le regole specificate riportate di seguito.',
ids_ussd_checkBlance:'Controlla equilibrio',
ids_title_tr069:'TR069',
ids_sms_draft:'Bozza',
ids_wifi_encryption:'Crittografia',
ids_title_ping:'Ping',
ids_foot_copyright:'Copyright 2016-2018 TCL Communication Ltd. Tutti i diritti riservati.',
ids_tr069_acsPw:'Password ACS',
ids_help_userManual:'Manuale utente',
ids_security_pfDescription:'L\'inoltro porte consente ai computer esterni di accedere a WWW, FTP o ad altri servizi forniti dalla rete LAN.',
ids_wifi_notSuppotMacFilter:'La procedura WPS (versione 2.0) non può essere attivata se il filtro Mac address è abilitato.',
ids_title_blockDevice:'Blocca dispositivo',
ids_router_endGeaterStart:'L\'indirizzo IP finale deve essere maggiore dell\'indirizzo IP iniziale.',
ids_net_2gOnly:'Solo 2G',
ids_clearCode_Twentynine:'Errore di autenticazione',
ids_usage_day:'giorno',
ids_wifi_wepShare:'WEP-Shared',
ids_sms_messageSending:'È in corso l\'invio di un SMS',
ids_wan_roamingPopCloseConntectTips:'Il roaming dati verrà disattivato',
ids_sd_currentFolder:'Cartella corrente',
ids_wan_disconnected:'Disconnesso',
ids_security_numRule:'<b>Nota:</b>è possibile creare un numero massimo di 16 filtri IP.',
ids_dns_manual_mode:'Modo manuale DNS',
ids_login:'Accedi',
ids_security_PowerSavingTitle:'Risparmio energetico',
ids_security_lanIpAddr:'Indirizzo IP LAN',
ids_menu_settings:'Impostazioni',
ids_wifi_disconWarning:'Questa azione comporta la disconnessione della rete Wi-Fi. Continuare?',
ids_wifi_wpsActiveWarn:'Procedura WPS in corso. Attendere 2 minuti e riprovare!',
ids_login_loginUserName:'Nome utente di accesso',
ids_wifi_wepWifiCertification:'La chiave WEP è 5 o 13 o 10 o 26.',
ids_connect:'Connetti',
ids_btn_block:'Blocca',
ids_pb_number:'NO',
ids_login_wrongPwd:'Password errata',
ids_sms_smsForwarding:'Inoltro di SMS',
ids_sys_selectFilePrompt:'Selezionare un file prima di procedere al caricamento.',
ids_wifi_wifiSecurity:'Sicurezza Wi-Fi',
ids_btn_edit:'Modifica',
ids_security_firewallSwitch:'Interruttore Firewall',
ids_router_endIP:'IP finale',
ids_sys_imei:'IMEI',
ids_sim_remainTime:'Tentativi residui',
ids_update_Confirm:'File scaricato, aggiornare?',
ids_sim_pinConfirmed:'Il codice PIN di conferma deve corrispondere al nuovo codice PIN.',
ids_filter_urlAddress:'Indirizzo URL',
ids_validate:'Convalida',
ids_security_subnetWarn:'Indirizzo IP LAN e "Indirizzo IP" devono appartenere alla stessa subnet.',
ids_sms_inputNum:'Immettere il numero di cellulare.',
ids_tr069_informInterval:'Intervallo Inform',
ids_fota_haveNewVersion:'Nuovo SW disponibile. Fare clic per aggiornare.',
ids_sim_pukRequiredTips:'Per ulteriori informazioni, prima fare clic su "PUK necessario" per sbloccare.',
ids_sms_emptyMessageWarn:'Il messaggio è vuoto. Inviarlo comunque?',
ids_sim_pck:'PCK',
ids_usage_clearHistory:'Reimpostare tutte le statistiche?',
ids_hour:'ora',
ids_tr069_connRqAuth:'Autenticazione richiesta di connessione',
ids_wifi_off:'Disattivato',
ids_pb_storageStatus:'Stato memoria',
ids_wan_connectedRule:'Non è possibile utilizzare questa impostazione nella modalità di collegamento. Fare clic su "Disconnetti" e riprovare.',
ids_menu_usage:'Utilizzo',
ids_security_dmzDescription:'Se un PC non è in grado di eseguire le applicazioni di rete tramite il gateway, attivare la funzione DMZ e immettere l\'indirizzo IP del PC sotto.',
ids_title_networkMode:'Modalità rete',
ids_wifi_wifiOffTime_5min:'5 minuti',
ids_wifi_pbc:'PBC',
ids_error:'Errore!',
ids_sim_changePinError:'Cambia errore PIN.',
ids_security_wanPort:'Porta WAN',
ids_security_ipFilter:'Filtro IP',
ids_tr069_inputConReqUserName:'Immetere nome utente per richiesta connesione prima di salvare',
ids_tr069_informIntervalRule:'L\'intervallo deve essere 0-2678400,inclusi "0123456789".',
ids_login_newPwd:'Nuova password',
ids_pdpTimer_10seconds:'10 secondi',
ids_security_virtualServerList:'Elenco server virtuali',
ids_security_urlAddrNameWarn:'L\'indirizzo URL esiste già.',
ids_btn_select:'Seleziona',
ids_router_endSameSubnet:'L\'indirizzo IP finale e l\'indirizzo IP devono appartenere alla stessa sottorete.',
ids_ussd_CodeEmpty:'Il campo immissione non può essere vuoto!',
ids_sim_autoPinError:'Errore verifica automatica PIN.',
ids_usage_cancelLimitTips:'Imposta limite dati 0 per cancellare qualunque limite dati.',
ids_sim_simLocked:'Blocco SIM necessario',
ids_icon_timeElapsed:'Tempo trascorso',
ids_sms_sendingPrompt:'Invio in corso, attendere.',
ids_tr069_inputAcsPassword:'Immettere password ACS prima di salvare',
ids_requestError:'Nessuna risposta. Il dispositivo potrebbe non essere connesso. Riavviare il dispositivo e riprovare.',
ids_profile_inputRule:'APN & Numero del profilo deve contenere caratteri ASCII compresi tra 32 e 127, ad eccezione di: " : ; & .',
ids_net_active:'Attivo',
ids_sms_numberWarning:'Il testo immesso è troppo lungo. Eliminarne una parte.',
ids_data:'Dati',
ids_pdpTimer:'Timer PDP',
ids_menu_sharing:'Condivisione',
ids_sd_noSdCard:'Nessuna scheda SD',
ids_wifi_pbcDecription:'1. Se al router non è collegato alcun client, tenere premuto il pulsante WPS sul router e attendere finché il LED Wi-Fi lampeggia. Se al router è collegato almeno un client, aprire il browser sul dispositivo collegato e accedere alla pagina http://192.168.0.1/, inserire la password e fare clic su Altro > WPS. Premere il pulsante software WPS.</br>2. Sul dispositivo che si desidera collegare al router (es. PC o smartphone), aprire la Utility di configurazione Wi-Fi compatibile con il WPS (che deve essere fornita dal venditore del dispositivo) e selezionare la modalità PBC o premere il pulsante PBC (WPS) sul dispositivo, se disponibile.</br>3. Il collegamento tra il router e il client viene instaurato automaticamente in 2 minuti circa.',
ids_sms_deleteSingleWarning:'Elimina SMS?',
ids_menu_more:'Altro',
ids_net_4gOnly:'Solo 4G',
ids_profileProtocal_none:'None',
ids_isSupportKickOff:'Un altro utente ha già effettuato l\'accesso, accedere comunque? Questa operazione causerà la disconnessione dell\'altro utente.',
ids_changePassword_Tips:'Il nome utente e la password attuali sono quelli predefiniti. Si consiglia di modificare la password con una parola di facile memorizzazione. Fare <a class="userpass_link">&nbsp;clic qui&nbsp;</a> per modificare nome utente e password.',
ids_wifi_wifiSleep:'WiFi Sleep',
ids_security_upnpDescription:'La tecnologia UPnP consente il networking tra i dispositivi. Si tratta di un protocollo distribuito e ad architettura aperta basato su standard definiti, quali la suite di protocolli Internet (TCP/IP), HTTP, XML e SOAP.',
ids_sms_deleteAll:'Elimina tutto',
ids_pb_location:'Destinazione',
ids_diagnostic:'Diagnostica',
ids_security_macAddrInvalid:'Indirizzo MAC non valido.',
ids_security_PowerSavingWiFiTips:'Il Wi-Fi si disattiverà automaticamente se la connessione rimane inattiva per un lungo periodo.',
ids_tr069_connRqUsername:'Nome utente richiesta di connessione',
ids_security_PowerSavingWiFi:'Wi-Fi',
ids_profile_pwdRule:'La lunghezza massima della password è 31 caratteri, ad eccezione di: " : ; & .',
ids_tr069_inform:'Inform',
ids_locked_permanently:'Questo dispositivo è stato bloccato permanentemente e non può essere sbloccato.',
ids_sys_setRebootEvent:'È in corso il riavvio del dispositivo, attendere 60 secondi quindi fare riconnettersi al dispositivo Wi-Fi.',
ids_sms_saveMode:'Modalità di salvataggio',
ids_pb_add:'Aggiungi',
ids_sim_spck:'SPCK',
ids_security_upnp:'UPnP',
ids_sms_encodingoptimization:'SMS Encoding Optimization',
ids_profile_inputDialNum:'Immettere il numero del profilo.',
ids_dlg_pb_deleteWarning:'Cancellare?',
ids_security_enableIp:'Abilita filtro indirizzo IP',
ids_sms_mobileNum:'Numero di telefono cellulare',
ids_security_urlFilterTitle:'Filtro URL',
ids_btn_setDefault:'Imp.&nbsp;predef.',
ids_wan_connectedRuleIndia:'Disconnettere la connessione dati prima di iniziare la gestione del profilo.',
ids_title_loginSettings:'Impostazioni accesso',
ids_profile_apn:'APN',
ids_pb_local:'Locale',
ids_wan_roamingAutoConnect:'Connessione automatica anche in roaming',
ids_wifi_key:'Chiave',
ids_login_userName:'admin',
ids_wifi_offRule:'WiFi al momento disabilitato dal momento che nessun client si è connesso per lungo tempo. Abilitare manualmente il WiFi premendo un tasto del dispositivo per utilizzarlo.',
ids_allow:'Consenti',
ids_usage_MB:'MB',
ids_sim_simLockedTips:'Per ulteriori informazioni, prima fare clic su "Blocco SIM necessario" per sbloccare.',
ids_login_inputOldPwd:'Immettere la vecchia password.',
ids_icon_downloaded:'Scaricati',
ids_sys_rebootWarn:'Riavviare il dispositivo?',
ids_security_enableFirewall:'Attiva firewall',
ids_security_pfRangePortTip:'Il numero della porta LAN è diverso da quello della porta WAN.',
ids_wifi_wepRule:'La chiave WEP deve essere composta da caratteri ASCII compresi tra 32 e 127,escluso: " : ; & .',
ids_sd_viewFile:'Visualizza file',
ids_icon_debit:'Addebita',
ids_wifi_wpa2:'WPA2-PSK',
ids_sim_pinManagement:'Gestione PIN',
ids_security_upnpStatus:'Stato UPnP',
ids_HelplineNumber:'Numero assistenza telefonica',
ids_login_confirmPwdRule:'La nuova password e la password di conferma devono corrispondere.',
ids_router_leaseTime:'Durata del lease dell\'indirizzo IP DHCP',
ids_sd_usedTotal:'(Utilizzato/Totale)',
ids_usage_monthlyDataPlan:'Programma dati mensili',
ids_title_wps:'WPS',
ids_sms_newMessage:'Nuovo messaggio',
ids_auto:'AUTO',
ids_usage_setTimeLimit:'Imposta limite orario',
ids_wifi_wep:'WEP',
ids_net_status:'Stato',
ids_usage_minutes:'minuti',
ids_wifi_wpsActive:'WPS attivato.',
ids_menu_usageSetting:'Impostazioni utilizzo',
ids_login_otherLogin:'L\'amministratore è già autenticato. Riprovare più tardi.',
ids_btn_wan_disconnect:'Disconnesso',
ids_tr069_inputAcsUserName:'Immettere ACS URL prima di salvare',
ids_security_ipFilterList:'Lista filtri IP',
ids_wifi_on:'Attivato',
ids_day:'giorno',
ids_net_gsm:'2G',
ids_usage_notAccurate:'Le statistiche potrebbero non essere accurate.',
ids_sim_pukRequired:'PUK necessario',
ids_security_ipOption:'Opzioni',
ids_net_lte:'4G',
ids_router_subnetEmpty:'Il campo Subnet mask è vuoto. Digitarlo di nuovo!',
ids_pdpTimer_5seconds:'5 secondi',
ids_wan_roamingPopWarningMessage:'Fai clic su <OK> per utilizzare i dati durante il roaming. Verificare con il proprio operatore di rete per i prezzi',
ids_manual:'Manuale',
ids_menu_connectDevice:'Dispositivo connesso',
ids_profile_dialNumber:'Numero del profilo',
ids_menu_sms:'SMS',
ids_sys_hwVersion:'Versione hardware',
ids_usage_mothlyDataTips:'Immettere i dati compresi tra 1-1024.',
ids_pdpTimer_90seconds:'90 secondi',
ids_title_macFilter:'Filtro MAC',
ids_netMode_Automatic4g3g2g:'Automatico(4G & 3G & 2G)',
ids_sys_noFileChosen:'Nessun file è stato scelto',
ids_dlg_sms_mobileNumRule:'Immettere un numero valido: solo 0-9 e "+", nessuno spazio né caratteri speciali.',
ids_wan_connecting:'Connessione in corso...',
ids_profile_inputName:'Immettere il nome del profilo prima di salvare le impostazioni del profilo.',
ids_wan_Block:'La lista degli indirizzi MAC è piena, non è possibile processare questa opzione.',
ids_icon_people:'Persone',
ids_sim_autoValidate:'Validazione automatica',
ids_menu_language:'Lingua',
ids_wifi_wpsPinRule:'Il codice PIN WPS deve essere compreso tra 4 e 8 cifre.',
ids_title_pinCodeSettings:'Impostazioni codice PIN',
ids_net_searching:'Ricerca in corso…',
ids_wifi_wpaRule:'WPA PSK deve contenere caratteri ASCII compresi tra 32 e 127, ad eccezione di: " : ; &',
ids_ussd_notSupport:'Non supportato! Fare Click su indietro per riprovare.',
ids_tr069_acsUrl:'URL ACS',
ids_sms_report:'Rapporto di consegna SMS',
ids_sim_cck:'CCK',
ids_security:'Protezione',
ids_enable:'Abilita',
ids_wifi_wpaAes:'AES',
ids_btn_next:'Successivo',
ids_profile_profileName:'Nome profilo',
ids_wifi_wepOpen:'WEP-OPEN',
ids_wan_connectIPMode:'Modalità Connessione IP',
ids_router_subnetInvalid:'La Subnet mask non è valida. Digitarla di nuovo!',
ids_pdpTimer_30seconds:'30 secondi',
ids_usage_min:'Min',
ids_wan_connected:'Connesso'
}