var resourceInfo={
ids_fota_upgradingTips:'N’éteignez pas pendant la mise à niveau. L’appareil redémarrera après l’opération.',
ids_usage_billingDay:'Date de facturation',
ids_sms_phoneNumberInvalid:'Numéro de téléphone non valide',
ids_btn_logout:'Déconnex.',
ids_wifi_ssidBroadcast:'Diffusion SSID',
ids_wifi_wpaDescription:'La clé pré-partagée WPA (PSK) doit comporter entre 8 et 63 caractères ASCII ou 64 caractères hexadécimaux.',
ids_dlg_pb_nameRule:'Le nom ne peut pas comporter les caractères suivants :"\\","\\\'".',
ids_usage_GB:'GB',
ids_UserNameRule32:'Le nom d\'utilisateur ne peut pas comporter plus de 32 caractères, ni les caractères suivants:  " : ; & .',
ids_pdpTimer_120seconds:'120 secondes',
ids_profile_profileNameRule:'Le nom de profil ne peut pas comporter plus de 31 caractères, ni les caractères suivants:  , " : ; \\ & % + < > ?',
ids_security_ipFilterDescription:'La plage de valeurs du port est comprise entre 0 et 65535.',
ids_back:'Retour',
ids_usage_dataUsageReach:'Si le plafond du forfait data mensuel est atteint.',
ids_router_startIpInvalid:'L\'adresse IP de début est non valide. Veuillez réessayer !',
ids_iptype:'Type IP',
ids_net_selectWarn:'Sélectionnez un réseau !',
ids_login_inputCurrPwd:'Le mot de passe est incorrect.',
ids_sim_autoPin:'Validation auto du code PIN',
ids_wifi_offTip:'La connexion wifi est désactivée, veuillez l\'activer.',
ids_net_3g4gOnly:'3G / 4G uniquement',
ids_wifi_wifiOffTime_30min:'30 minutes',
ids_fota_batteryTips:'La batterie est basse, l’équipement ne pourra pas être mis à jour.',
ids_wifi_wpa:'WPA PSK',
ids_wifi_cipher:'Type de chiffrement',
ids_sim_initializing:'Initialisation SIM',
ids_success:'Opération réussie',
ids_sim_lockCodeRule:'Le code de verrouillage SIM doit comporter 10 chiffres.',
ids_sim_pinRequired:'Code PIN obligatoire',
ids_router_endIpInvalid:'L\'adresse IP de fin est non valide. Veuillez réessayer !',
ids_security_macFilterDescription:'Permet de contrôler et gérer les appareils ayant accès au WLAN (améliore la sécurité du WLAN).',
ids_net_lteOnlyVal:'LTE uniquement',
ids_security_PowerSavingSmartTips:'Toutes les voyants s\'éteignent automatiquement à l\'exception du voyant d\'alimentation en cas d\'absence d\'accès WI-FI ou de fonctionnement manuel pendant 30 s.',
ids_wan_tips:'Erreur ! Mémoire pleine , vous pouvez réinitialiser le plan data mensuel et vous reconnecter.',
ids_wan_roamingWarningMessage:'Data Roaming vous permet de naviguer sur le Web, d\'utiliser le courrier électronique, le MMS et d\'autres services de données à l\'étranger. Vérifiez auprès de votre fournisseur de réseau pour les prix',
ids_title_preferredDnsServer:'Serveur DNS préféré',
ids_modify:'Modifier',
ids_title_connectMode:'Mode de connexion',
ids_net_noService:'Aucun service',
ids_net_2g3gOnly:'2G / 3G uniquement',
ids_sms_chatInputConfirm:'Veuillez appuyer Entrer pour compléter',
ids_sms_mobileNumRule:'Le numéro du portable doit se limiter à 20 caractères, code international compris, par exemple, « +0123456789 ». Recomposez-le.',
ids_dlg_pb_NumberNullWarning:'Le numéro de téléphone doit être renseigné.',
ids_usage_hours:'heures',
ids_usage_timePassed:'Durée d’utilisation',
ids_wifi_country:'Pays',
ids_wifi_wlan_mode:'Mode Wi-Fi',
ids_net_umts:'3G',
ids_fail:'Échec!',
ids_wifi_wpsPin:'PIN WPS',
ids_wan_inputDeviceName:'Attribuez un nom à l’appareil.',
ids_sms_sendFail:'Échec de l\'envoi du SMS',
ids_sim_pukCode:'PUK',
ids_sms_newMessageOn:'non lu de',
ids_tr069_inputConReqPassword:'Saisissez le mot de passe pour la demande de connexion avant de l’enregistrer.',
ids_sys_swVersion:'Version logicielle',
ids_sim_simlockError:'Erreur de blocage de la SIM !',
ids_security_ipFilterPort:'La plage de valeurs du port est comprise entre 0 et 65535.',
ids_wifi_inputSsid:'Indiquez le SSID.',
ids_clearCode_Thirtythree:'Aucune données de service',
ids_sim_confirmPinCode:'Confirmer PIN',
ids_security_dmzStatus:'État DMZ',
ids_security_macAddrNameWarn:'L\'adresse MAC existe déjà.',
ids_security_portRule:'La valeur du port doit être comprise entre 1 et 65535.',
ids_router_startIP:'IP de début',
ids_fotaUpdate_openRoaming_meg:'Le téléchargement en itinérance peut entraîner des frais supplémentaires, veuillez-le vérifier auprès de votre opérateur. Voulez-vous continuer ?',
ids_net_forbid:'Interdit',
ids_btn_loginTimeout:'réenregistrer',
ids_security_wanIpAddr:'Adresse IP du réseau étendu',
ids_profile_userName:'Nom d\'utilisateur',
ids_profile_password:'Mot de passe',
ids_btn_restore:'Restaurer',
ids_tips_livechat:'Chat en direct',
ids_login_inputPwd:'Saisissez le mot de passe.',
ids_login_inputUserName:'Saisissez le nom d\'utilisateur.',
ids_pdpTimer_20seconds:'20 secondes',
ids_btn_previous:'Retour',
ids_sys_restoreBackupWarn:'Une fois le chargement terminé, les réglages seront mis à jour et l\'appareil redémarré. Voulez-vous vraiment continuer ?',
ids_security_ipLanWan:'Note: The value range of LAN/WAN Port is 0-65535 and 0 means any.',
ids_usage_KB:'KB',
ids_login_remenberPassword:'Mémoriser le mot de passe',
ids_security_firewallDes:'Cette page fournit des informations sur la façon d’activer le filtrage par pare-feu. Cette fonction n’est disponible que si le pare-feu est activé.',
ids_title_wifiSettings:'Paramètres Wi-Fi',
ids_sim_invalidSimCard:'Carte SIM non valide',
ids_sim_unknown:'inconnu',
ids_wan_disconnecting:'Déconnexion…',
ids_btn_delete:'Supprimer',
ids_tr069_client:'Client TR-069 – Configuration',
ids_wifi_channel:'Canal Wi-Fi',
ids_title_dnsSetting:'DNS',
ids_pb_name:'Nom',
ids_btn_apply:'Appliquer',
ids_fota_latestVersion:'Il s’agit déjà de la dernière version.',
ids_security_urlAddrInvalid:'Adresse URL incorrecte.',
ids_wan_cannotBlock:'Le filtre MAC est activé, cette option ne peut être utilisée.',
ids_deny:'Refuser',
ids_sms_saveDraftSuccess:'SMS enregistré dans les brouillons',
ids_network_notAvailableFunctionWarn:'Veuillez désactiver la connexion de données avant de lancer la gestion de profil',
ids_usage_duration:'Durée',
ids_sim_rck:'RCK',
ids_sms_deleteWarning:'Supprimer SMS?',
ids_icon_uploaded:'Envois',
ids_orange_sim_pinOperationWarn:'Vous ne pouvez pas modifier les paramètres de code PIN si vous êtes connecté à Internet.',
ids_dlg_pb_mobileNumRule:'La longueur maximale du numéro de mobile est de 40 chiffres, incluant « +0123456789 », recommencez votre saisie.',
ids_title_profilesManagement:'Gestion des profils',
ids_wifi_wifiOffTime_20min:'20 minutes',
ids_sim_lockForbidden:'Verrouillage SIM interdit !',
ids_sim_pinRule:'Le code PIN doit comporter entre 4 et 8 chiffres.',
ids_security_dmzTips:'La fonction DMZ permet à l\'appareil sélectionné de contourner le pare-feu de la passerelle et d\'accéder à l\'Internet de cet appareil sans restriction.',
ids_router_startSameSubnet:'L\'adresse IP de début et l\'adresse IP doivent appartenir au même sous-réseau.',
ids_btn_help:'Aide',
ids_menu_smsSettings:'Réglages SMS',
ids_profile_nameWarn:'Ce nom de profil existe déjà.',
ids_wifi_wifiOffTime_10min:'10 minutes',
ids_sim_newPinRule:'Le nouveau code PIN doit comporter 4 à 8 chiffres.',
ids_sim_comfirmPinRule:'La confirmation du code PIN doit comporter 4 à 8 chiffres.',
ids_sim_enterValidCode:'Saisissez un code PIN valide.',
ids_btn_send:'Envoyer',
ids_net_available:'Disponible',
ids_profile_numRule:'Remarque: vous pouvez créer jusqu\'à 15 profils.',
ids_gsm7_text:'GSM 7',
ids_dlg_sms_smsForwardNumEmpty:'Le numéro de mobile n\'est pas renseigné. Veuillez saisir le numéro.',
ids_wifi_wepDescription:'La clé WEP doit comporter 5 ou 13 caractères ASCII, ou 10 ou 26 chiffres hexadécimaux.',
ids_sd_sdCard:'Carte SD',
ids_sys_deviceName:'Nom de l\'appareil',
ids_days:'jours',
ids_sys_ipAddress:'Adresse IP',
ids_login_nameOrPwdWrong:'Le nom d’utilisateur ou le mot de passe est incorrect !',
ids_profile_userNameRule:'Le nom d\'utilisateur ne peut pas comporter plus de 31 caractères, ni les caractères suivants:  " : ; & .',
ids_wifi_cannotSet:'La fonction Wi-Fi est désactivée. Cette option ne peut pas être traitée.',
ids_router_ipAddrEmpty:'L\'adresse IP est vide. Veuillez réessayer !',
ids_wifi_pinDecription:'Code PIN WPS (configuration WPS en saisissant le code spécial à 8 chiffres) :</br>1. Si au moins un client est connecté au routeur, ouvrez le navigateur sur le dispositif connecté, accédez à l’adresse http://192.168.0.1/, saisissez le mot de passe, puis cliquez sur Plus > WPS. Sélectionnez PIN WPS.</br>2. Sur le dispositif que vous voulez connecter au routeur (par exemple, un PC ou un smartphone), ouvrez l’utilitaire de configuration Wi-Fi qui prend en charge les connexions WPS (normalement fourni avec l’appareil en question), puis choisissez le mode PIN WPS. Le code PIN WPS à 8 chiffres est alors généré.</br>3. Revenez à la page du routeur, saisissez le code PIN WPS à 8 chiffres dans le champ correspondant, puis cliquez sur Appliquer.</br>4. La connexion entre le routeur et le client s’établit automatiquement dans les 2 minutes.',
ids_tr069_tips:'Sélectionnez les valeurs de votre choix, puis cliquez sur « Appliquer/Enregistrer » pour configurer les options du client TR-069.',
ids_more_onlineUpdate:'Mise à jour en ligne',
ids_security_btnAdd:'Ajouter',
ids_sms_autoForward:'Transfert de SMS au téléphone mobile',
ids_sim_simLockCode:'Code blocage SIM',
ids_router_restartWarn:'Votre appareil devra être redémarré. Voulez-vous vraiment continuer ?',
ids_sms_saveSimCard:'carte SIM',
ids_automatic:'Automatique',
ids_security_portTips:'Remarque : indiquez le numéro de port et le groupe de port, par exemple : 30 ou 65500-65510.',
ids_wifi_wpsNotSuppotSSIDHidden:'Réseau (SSID) caché, impossible d\'activer le WPS.',
ids_netMode_Automatic3g2g:'(3G & 2G)automatique',
ids_wifi_apIsotation:'Isolement de PA',
ids_security_portForwarding:'Transfert de port',
ids_btn_add:'Ajouter',
ids_usage_billingTimeTips:'Jour de facturation, compris entre 1 et 31.',
ids_minutes:'minutes',
ids_ussd_inputDescription:'Entrer le code USSD',
ids_fota_upgrading:'Mise à niveau…',
ids_router_dhcpServer:'Serveur DHCP',
ids_sim_pinRequiredTips:'Pour en savoir plus, cliquez sur « Code PIN obligatoire » pour déverrouiller.',
ids_login_checkPwdRule:'Mot de passe invalide: La longueur du mot de passe de connexion est de 4-16, y compris 0-9, a-z, A-Z, "- +! @ $ # ^ & *".',
ids_wifi_wifiOffTime:'Heure de désactivation Wi-FI',
ids_sd_sdShareMode:'Accès au contenus de la carte SD',
ids_btn_continue:'Continuer',
ids_profile_protocal:'Protocole',
ids_security_lanPort:'Port réseau local',
ids_dlg_sms_reInputCenterNum:'Le numéro du centre de SMS n\'est pas valide. Veuillez réessayer.',
ids_btn_backup:'sauvegarder',
ids_wan_connected_num:'Connecté',
ids_sms_centerNum:'Centre des SMS',
ids_fota_downloading:'Téléchargement …',
ids_wifi_wpaWpa2Psk:'WPA/WPA2 PSK',
ids_usage_of:'sur',
ids_sys_rebootDecription:'Cliquez sur ce bouton pour redémarrer l\'appareil.',
ids_title_about:'À propos',
ids_sim_nck:'NCK',
ids_net_operator:'Opérateur',
ids_router_endIpEmpty:'L\'adresse IP de fin est vide. Veuillez réessayer !',
ids_btn_cancel:'Annuler',
ids_dlg_pb_nameNullWarning:'Le nom doit être renseigné.',
ids_dlg_sms_inputCenterNum:'Le numéro du centre de SMS n\'est pas renseigné. Veuillez réessayer.',
ids_ussd_rule:'Seuls les "*" "#" et les chiffres peuvent être saisis.',
ids_wifi_wifi:'Wi-Fi',
ids_sms_selectSomeOptions:'3 contacts maximum',
ids_btn_new:'Nouveau',
ids_fota_findNewVersion:'Rechercher nouvelle version',
ids_security_pfNumRule:'Remarque : vous pouvez créer jusqu\'à 16 numéros de Transfert de port.',
ids_wifi_showPwd:'Afficher le mot de passe',
ids_security_urlFilterList:'URL Filter List',
ids_loginTimeout:'Délai de connexion dépassé, reconnexion nécessaire',
ids_title_alternateDnsServer:'Serveur DNS alternatif',
ids_login_inputNewPwd:'Saisissez le nouveau mot de passe.',
ids_fota_updateTitle:'Mises à jour du système',
ids_login_inputConfirmPwd:'Immettere la password di conferma.',
ids_hours:'heures',
ids_wifi_maxUser:'Nb max. d\'utilisateurs',
ids_pb_addNew:'Ajouter',
ids_usage_timeLimit:'Durée max.',
ids_sim_pinCode:'PIN',
ids_wifi_wpaTkip:'TKIP',
ids_sim_autoPinState:'Etat actuel',
ids_security_dmzTitle:'DMZ',
ids_security_dmzIpInvalid:'L’adresse IP DMZ n’est pas une adresse IP valide.',
ids_btn_unblock:'Débloquer',
ids_fota_checkUpdate:'Mettre à jour',
ids_title_advanced:'Réglages avancés',
ids_security_ipFilterWarn:'Le filtrage d’adresses IP existe déjà.',
ids_fota_updateDescription:'cliquez sur « Mettre à jour » pour installer la nouvelle version.',
ids_btn_reset:'Réinitialiser',
ids_tr069_acsUrlRule:'Format de l’URL de l’ACS : http://adresse IP:port/xxx',
ids_show_again:'Ne plus afficher',
ids_usage_hrs:'Hrs',
ids_icon_battery:'Batterie',
ids_sms_saveDevice:'Appareil',
ids_roamAppear:'Faites glisser pour utiliser la connexion Internet à l’étranger. Consultez les tarifs auprès de votre opérateur.',
ids_sys_chooseFile:'Sélectionner&nbsp;un&nbsp;fichier',
ids_btn_refresh:'Actualiser',
ids_pb_phoneBook:'Répertoire',
ids_net_select:'Sélection du réseau',
ids_sim_pinError:'Erreur de code PIN !',
ids_sms_saveDraftFailed:'Échec de la sauvegarde du brouillon',
ids_sms_delivered:'Envoyé',
ids_usage_autoDisconnected:'Déconnexion automatique',
ids_login_confirmPwd:'Confirmation',
ids_security_addMacAddress:'Ajouter l’adresse MAC',
ids_sim_noSimCard:'Aucune carte SIM',
ids_wifi_notSuppotWepWpa:'WPS indisponible sous TKIP WEP, WPA, WPA2 !',
ids_security_pfWarn:'Le transfert de port existe déjà.',
ids_fota_checking:'Vérification…',
ids_dlg_pb_lenWarning:'Le nom saisi est trop long.',
ids_sim_newPinCode:'Nouveau PIN',
ids_sim_pinNotAvailable:'Code PIN non disponible.',
ids_usage_clear:'Effacer l’historique',
ids_wifi_maxSsid:'Le SSID doit se limiter à 32 caractères, de 0 à 9, de a à z, de A à Z et aux caractères « - », « _ », « . » et l’espace.',
ids_usage_startTimeTips:'Forfait données mensuel, compris entre  1 et 43200.',
ids_wifi_pbcConfiguration:'Bouton de configuration PBC',
ids_usage_dataConsumption:'Volume data consommée',
ids_disable:'Désactiver',
ids_ucs2Orgsm7_text:'UCS2 Or GSM7',
ids_login_loginPwd:'Mot de passe de connexion',
ids_btn_save:'Enregistrer',
ids_wifi_802mode:'Mode 802.11',
ids_pb_phoneNumber:'Numéro de téléphone',
ids_ussd_timeOut:'Temps perdu! S\'il vous plaît essayer à nouveau.',
ids_btn_reboot:'Redémar.',
ids_minute:'minute',
ids_router_ipAddrInvalid:'L\'adresse IP est non valide. Veuillez réessayer !',
ids_router_startIpEmpty:'L\'adresse IP de début est vide. Veuillez réessayer !',
ids_sim_pinEnable:'La validation auto. du code PIN est activée.',
ids_sim_pinCodeOperation:'Opération de code PIN',
ids_security_dmzInvalidLanSubnet:'L’adresse IP DMZ ne s’inscrit pas dans le sous-réseau du réseau local.',
ids_net_service:'Service',
ids_router_ipRule:'Erreur ! L\'adresse IP ne peut pas se terminer par le chiffre 10 car ce nombre est pré-réservé par le système et ne peut être inclut au pool des adresse IP DHCP.',
ids_usage_roaming:'Itinérance',
ids_title_ussd:'USSD',
ids_btn_ok:'OK',
ids_sys_resetDecription:'Restaurer les réglages par défaut.',
ids_tr069_inputInformInterval:'Saisissez l’intervalle d’état avant de l’enregistrer.',
ids_security_dmzIpAddr:'Adresse IP DMZ',
ids_profile_inputApn:'Indiquez le nom du point d\'accès !',
ids_sys_restoreFactoryWarn:'Les réglages usines seront restaurés et l\'appareil redémarré. Voulez-vous vraiment continuer ?',
ids_net_registing:'Enregistrement…',
ids_sys_backupDecription:'Télécharger (sauvegarder) la configuration.',
ids_sms_selectAnOption:'Sélectionner une option',
ids_tr069_inputAcsUrl:'Saisissez l’URL de l’ACS avant de l’enregistrer.',
ids_tr069_acsUsername:'Nom d’utilisateur ACS',
ids_pdpTimer_0seconds:'0 seconde',
ids_usage_home:'Accueil',
ids_profile_deleteWarn:'Supprimer profil?',
ids_sms_smsFull:'La boîte aux SMS est pleine. Supprimez-en pour pouvoir en envoyer/enregistrer des nouveaux.',
ids_tr069_connRqPw:'Mot de passe de la demande de connexion',
ids_sim_pukError:'Erreur du code PUK !',
ids_sys_system:'système',
ids_security_PowerSavingSmart:'Prédictif',
ids_login_timeuseout:'Le temps de connexion a expiré, veuillez redémarrer et réessayer.',
ids_usage_minutesTimes:'min.',
ids_sim_pukRule:'Le code PUK doit comporter 8 chiffres.',
ids_net_3gOnly:'3G uniquement',
ids_sim_nsck:'NSCK',
ids_subnetMask:'Masque de sous-réseau',
ids_pdpTimer_60seconds:'60 secondes',
ids_sim_pinDisable:'La validation auto. du code PIN est désactivée.',
ids_sys_macAddress:'Adresse MAC',
ids_menu_connection:'Connexion',
ids_dlg_pb_tooManyNumbers:'Pour commencer la modification, sélectionnez un seul chiffre.',
ids_password:'Mot de passe',
ids_security_virtualServer:'Serveur virtuel (transfert de port statique)',
ids_security_ipFilterDes:'Filtrez les paquets à l’aide des règles suivantes indiquées avec le protocole, le port et l’adresse IP.',
ids_ussd_checkBlance:'Verifier le Solde',
ids_title_tr069:'TR069',
ids_sms_draft:'Brouillons',
ids_wifi_encryption:'Cryptage',
ids_title_ping:'Ping',
ids_foot_copyright:'Copyright 2016-2018 TCL COMMUNICATION LTD. TOUS DROITS RÉSERVÉS.',
ids_tr069_acsPw:'Mot de passe ACS',
ids_help_userManual:'Manuel utilisateur',
ids_security_pfDescription:'La fonction de Transfert de port permet aux ordinateurs externes d\'accéder aux sites WWW, FTP ou autres services fournis par le réseau local.',
ids_wifi_notSuppotMacFilter:'La procédure WPS (version 2.0) ne peut être activé si le filtre de l\'adresse MAC est activée.',
ids_title_blockDevice:'Bloquer l’appareil',
ids_router_endGeaterStart:'L\'adresse IP de fin doit être supérieure à l\'adresse IP de début.',
ids_net_2gOnly:'2G uniquement',
ids_clearCode_Twentynine:'Échec d\'authentification',
ids_usage_day:'jour',
ids_wifi_wepShare:'WEP-Shared',
ids_sms_messageSending:'Un SMS est en cours d’envoi',
ids_wan_roamingPopCloseConntectTips:'L\'itinérance des données sera désactivée.',
ids_sd_currentFolder:'Dossier actif',
ids_wan_disconnected:'Déconnecté',
ids_security_numRule:'<b>Remarque :</b> le nombre max. de filtrage d’adresses IP que vous pouvez créer est de 16.',
ids_dns_manual_mode:'DNS manual mode',
ids_login:'Connexion',
ids_security_PowerSavingTitle:'Économie d\'énergie',
ids_security_lanIpAddr:'Adresse IP du réseau local',
ids_menu_settings:'Réglages',
ids_wifi_disconWarning:'La connexion Wi-Fi va être interrompue. Voulez-vous tout de même continuer ?',
ids_wifi_wpsActiveWarn:'Procédure WPS en cours. Patientez 2 minutes, puis essayez à nouveau.',
ids_login_loginUserName:'Nom d\'utilisateur de connexion',
ids_wifi_wepWifiCertification:'La clé WEP doit comporter 5, 13, 10 ou 26 caractères.',
ids_connect:'Connecter',
ids_btn_block:'Bloquer',
ids_pb_number:'NON.',
ids_login_wrongPwd:'Mauvais Mot de Passe',
ids_sms_smsForwarding:'Transfert SMS',
ids_sys_selectFilePrompt:'Sélectionnez un fichier avant le chargement.',
ids_wifi_wifiSecurity:'Wi-Fi_Sécurité',
ids_btn_edit:'Modifier',
ids_security_firewallSwitch:'Interrupteur Pare-feu',
ids_router_endIP:'IP de fin',
ids_sys_imei:'IMEI',
ids_sim_remainTime:'Essais restants',
ids_update_Confirm:'Le fichier a bien été téléchargé, voulez-vous l’installer maintenant ?',
ids_sim_pinConfirmed:'Le code PIN de confirmation doit être le même que le nouveau code PIN.',
ids_filter_urlAddress:'URL Address',
ids_validate:'Valider',
ids_security_subnetWarn:'Les champs « Adresse IP du réseau local » et « Adresse IP » doivent appartenir au même sous-réseau.',
ids_sms_inputNum:'Indiquez le numéro de portable.',
ids_tr069_informInterval:'Intervalle d’information',
ids_fota_haveNewVersion:'Une nouvelle version est disponible. Cliquez sur Mettre à jour.',
ids_sim_pukRequiredTips:'Pour en savoir plus, cliquez sur « Code PUK obligatoire » pour déverrouiller.',
ids_sms_emptyMessageWarn:'Le message est vide. Voulez-vous envoyer ce message vide ?',
ids_sim_pck:'PCK',
ids_usage_clearHistory:'Voulez-vous réinitialiser toutes les statistiques ?',
ids_hour:'heure',
ids_tr069_connRqAuth:'Authentification de la demande de connexion',
ids_wifi_off:'Désactivé',
ids_pb_storageStatus:'État du stockage',
ids_wan_connectedRule:'Ce paramètre est inutilisable en mode connecté. Cliquez sur « Déconnecter », puis réessayez.',
ids_menu_usage:'Utilisation',
ids_security_dmzDescription:'Si un PC ne peut pas exécuter d\'applications réseau en transitant par la passerelle, activez la fonction DMZ, puis saisissez l\'adresse IP du PC mentionné ci-dessus.',
ids_title_networkMode:'Mode réseau',
ids_wifi_wifiOffTime_5min:'5 minutes',
ids_wifi_pbc:'PBC',
ids_error:'Erreur!',
ids_sim_changePinError:'Erreur de changement du code PIN !',
ids_security_wanPort:'Port réseau étendu',
ids_security_ipFilter:'Filtre IP',
ids_tr069_inputConReqUserName:'Saisissez le nom d’utilisateur de la demande de connexion avant de l’enregistrer.',
ids_tr069_informIntervalRule:'L’intervalle d’état doit être numérique, de 0 à 2 678 400, ne comportant que les chiffres 0123456789.',
ids_login_newPwd:'Nouveau mot de passe',
ids_pdpTimer_10seconds:'10 secondes',
ids_security_virtualServerList:'Liste des serveurs virtuels',
ids_security_urlAddrNameWarn:'Cette adresse URL existe déjà.',
ids_btn_select:'Sélection',
ids_router_endSameSubnet:'L\'adresse IP de fin et l\'adresse IP doivent appartenir au même sous-réseau.',
ids_ussd_CodeEmpty:'Boîte d\'entrée ne peut pas être vide!',
ids_sim_autoPinError:'Erreur de vérification auto. du code PIN !',
ids_usage_cancelLimitTips:'Régler à 0 puis sauvegardez si vous ne souhaitez pas restreindre ce forfait.',
ids_sim_simLocked:'Blocage de la SIM obligatoire',
ids_icon_timeElapsed:'Temps écoulé',
ids_sms_sendingPrompt:'Envoi en cours..., veuillez patienter !',
ids_tr069_inputAcsPassword:'Saisissez le mot de passe de l’ACS avant de l’enregistrer.',
ids_requestError:'Aucune réponse, l\'appareil a sans doute été déconnecté. Veuillez le redémarrer et recommencer.',
ids_profile_inputRule:'La clé APN & Numéro du profil doit comporter entre 32 et 127 caractères ASCII, à l\'exception de: " : ; & .',
ids_net_active:'Actif',
ids_sms_numberWarning:'Le texte saisi est trop long. Veuillez raccourcir.',
ids_data:'Données',
ids_pdpTimer:'PDP Timer',
ids_menu_sharing:'Partage',
ids_sd_noSdCard:'Carte SD absente',
ids_wifi_pbcDecription:'1. Si aucun client n’est connecté au routeur, maintenez la touche WPS sur le routeur enfoncée jusqu’à ce que le voyant Wi-Fi clignote. Si au moins un client est connecté au routeur, ouvrez le navigateur sur le dispositif connecté, accédez à l’adresse http://192.168.0.1/, saisissez le mot de passe, puis cliquez sur Plus > WPS. Appuyez sur la touche WPS.</br>2. Sur le dispositif que vous voulez connecter au routeur (par exemple, un PC ou un smartphone), ouvrez l’utilitaire de configuration Wi-Fi qui prend en charge les connexions WPS (normalement fourni avec l’appareil en question), puis choisissez le mode PBC ou appuyez sur la touche PBC (WPS) sur le dispositif, selon les cas.</br>3. La connexion entre le routeur et le client s’établit automatiquement dans les 2 minutes.',
ids_sms_deleteSingleWarning:'Supprimer SMS?',
ids_menu_more:'Autres',
ids_net_4gOnly:'4G uniquement',
ids_profileProtocal_none:'None',
ids_isSupportKickOff:'Autre utilisateur déjà connecté, voulez-vous toujours vous connecter? Cela désactivera l\'utilisateur.',
ids_changePassword_Tips:'Le nom d\'utilisateur et le mot de passe actuels sont ceux définis par défaut, nous vous conseillons de les changer. Veuillez <a class="userpass_link">&nbsp;cliquer ici&nbsp;</a> pour modifier le nom d\'utilisateur et le mot de passe.',
ids_wifi_wifiSleep:'WiFi Sleep',
ids_security_upnpDescription:'Le mode UPnP autorise la mise en réseau entre deux appareils. Il s\'agit d\'un protocole d\'architecture ouvert et distribué s\'appuyant sur des normes établies tel que la suite des protocoles Internet (TCP/IP), HTTP, XML et SOAP.',
ids_sms_deleteAll:'Tout supprimer',
ids_pb_location:'Localisation',
ids_diagnostic:'Diagnostique',
ids_security_macAddrInvalid:'Adresse MAC non valide.',
ids_security_PowerSavingWiFiTips:'La fonction Wi-Fi se désactive automatiquement si la connexion est en veille pendant une période prolongée.',
ids_tr069_connRqUsername:'Nom d’utilisateur de la demande de connexion',
ids_security_PowerSavingWiFi:'Wi-Fi',
ids_profile_pwdRule:'Le mot de passe ne peut pas comporter plus de 31 caractères, ni les caractères suivants :  " : ; & .',
ids_tr069_inform:'Informer',
ids_locked_permanently:'Cet appareil a été verrouillé de façon définitive. Il n\'est plus possible de le débloquer !',
ids_sys_setRebootEvent:'Cet appareil est en train de redémarrer. Patientez pendant 60 secondes avant de reconnectez-vous à l\'appareil Wi-Fi.',
ids_sms_saveMode:'Mode d\'enregistrement',
ids_pb_add:'Ajouter',
ids_sim_spck:'SPCK',
ids_security_upnp:'UPnP',
ids_sms_encodingoptimization:'Optimisation de l\'encodage SMS',
ids_profile_inputDialNum:'Indiquez le numéro du profil !',
ids_dlg_pb_deleteWarning:'Voulez-vous vraiment supprimer ?',
ids_security_enableIp:'Activer le filtrage d’adresses IP',
ids_sms_mobileNum:'N° téléphone mobile',
ids_security_urlFilterTitle:'Filtre des URL',
ids_btn_setDefault:'Par&nbsp;défaut',
ids_wan_connectedRuleIndia:'Veuillez désactiver la connexion de données avant de lancer la gestion de profil',
ids_title_loginSettings:'Paramètres de connexion',
ids_profile_apn:'Nom du point d\'accès',
ids_pb_local:'Local',
ids_wan_roamingAutoConnect:'Connexion automatique à l\'étranger',
ids_wifi_key:'Mot de passe Wifi',
ids_login_userName:'admin',
ids_wifi_offRule:'Le Wifi a été désactivé suite à une longue période d\'inutilisation. Veuillez  réactiver manuellement en appuyant sur n\'importe quel bouton.',
ids_allow:'Autoriser',
ids_usage_MB:'MB',
ids_sim_simLockedTips:'Pour en savoir plus, cliquez sur « Blocage de la SIM obligatoire » pour déverrouiller.',
ids_login_inputOldPwd:'Saisissez l’ancien mot de passe.',
ids_icon_downloaded:'Téléchargements',
ids_sys_rebootWarn:'Voulez-vous vraiment redémarrer cet appareil ?',
ids_security_enableFirewall:'Activer le pare-feu',
ids_security_pfRangePortTip:'Le numéro de port du réseau local doit être identique à celui du réseau étendu.',
ids_wifi_wepRule:'La clé WEP doit se composer de caractères ASCII allant de 32 à 127, sauf pour: " : ; & .',
ids_sd_viewFile:'Afficher le fichier',
ids_icon_debit:'Débit',
ids_wifi_wpa2:'WPA2 PSK',
ids_sim_pinManagement:'Gestion PIN',
ids_security_upnpStatus:'État UPnP',
ids_HelplineNumber:'Numéro d\'assistance :',
ids_login_confirmPwdRule:'Le nouveau mot de passe et le mot de passe de confirmation doivent être identiques.',
ids_router_leaseTime:'Durée de bail DHCP',
ids_sd_usedTotal:'(Utilisé/Total)',
ids_usage_monthlyDataPlan:'Forfait data mensuel',
ids_title_wps:'WPS',
ids_sms_newMessage:'Nouveau message',
ids_auto:'AUTO',
ids_usage_setTimeLimit:'Indiquer la durée max.',
ids_wifi_wep:'WEP',
ids_net_status:'État',
ids_usage_minutes:'minutes',
ids_wifi_wpsActive:'WPS actif.',
ids_menu_usageSetting:'Paramètres d’usage',
ids_login_otherLogin:'Un administrateur est deja connecté, Essayez plus tard.',
ids_btn_wan_disconnect:'Déconnecté',
ids_tr069_inputAcsUserName:'Saisissez le nom d’utilisateur de l’ACS avant de l’enregistrer.',
ids_security_ipFilterList:'IP Filter List',
ids_wifi_on:'Activé',
ids_day:'jour',
ids_net_gsm:'2G',
ids_usage_notAccurate:'Les statistiques peuvent ne pas être exactes.',
ids_sim_pukRequired:'Code PUK obligatoire',
ids_security_ipOption:'Options',
ids_net_lte:'4G',
ids_router_subnetEmpty:'Le masque de sous-réseau est vide. Veuillez réessayer !',
ids_pdpTimer_5seconds:'5 secondes',
ids_wan_roamingPopWarningMessage:'Cliquez sur <OK> pour utiliser les données en itinérance. Vérifiez auprès de votre fournisseur de réseau pour les prix',
ids_manual:'Manuel',
ids_menu_connectDevice:'Appareil connecté',
ids_profile_dialNumber:'Numéro du profil',
ids_menu_sms:'SMS',
ids_sys_hwVersion:'Version matérielle',
ids_usage_mothlyDataTips:'Forfait données mensuel, compris entre 1 et 1024.',
ids_pdpTimer_90seconds:'90 secondes',
ids_title_macFilter:'Filtre MAC',
ids_netMode_Automatic4g3g2g:'(4G & 3G & 2G)automatique',
ids_sys_noFileChosen:'Aucun fichier sélectionné',
ids_dlg_sms_mobileNumRule:'Indiquez un numéro valide : 0 à 9 et \'+\' uniquement, aucun espace ou caractère spécial.',
ids_wan_connecting:'Connexion…',
ids_profile_inputName:'Saisissez le nom de profil avant d\'enregistrer ses réglages.',
ids_wan_Block:'La liste d\'adresses MAC est pleine, cette option ne peut être utilisée.',
ids_icon_people:'Contacts',
ids_sim_autoValidate:'Saisie automatique',
ids_menu_language:'Langue',
ids_wifi_wpsPinRule:'Le code PIN WPS doit comporter entre 4 et 8 caractères.',
ids_title_pinCodeSettings:'Paramètres de code PIN',
ids_net_searching:'Recherche…',
ids_wifi_wpaRule:'La clé WPA PSK doit comporter entre 32 et 127 caractères ASCII, à l\'exception de:" : ; & .',
ids_ussd_notSupport:'Non supporté! S\'il vous plaît essayez à nouveau.',
ids_tr069_acsUrl:'URL de l’ACS',
ids_sms_report:'rapport SMS',
ids_sim_cck:'CCK',
ids_security:'Sécurité',
ids_enable:'Activer',
ids_wifi_wpaAes:'AES',
ids_btn_next:'Suivant',
ids_profile_profileName:'Nom du profil',
ids_wifi_wepOpen:'WEP-OPEN',
ids_wan_connectIPMode:'Mode de connexion IP',
ids_router_subnetInvalid:'Le masque de sous-réseau est non valide. Veuillez réessayer !',
ids_pdpTimer_30seconds:'30 secondes',
ids_usage_min:'Min',
ids_wan_connected:'Connecté'
}